### ISSUE TITLE
where(_.inAssignment), where(_.inAssignment.source), and where(_.inAssignment.target) produce identical outputs

### ISSUE THREAD

**Issue by jryerb** [joernio/joern#1008]
For the example code:
```
int test()
{
    int var1;
    int var2;

    var1 = (long)(var2 + 20);

    return 0;
}
```
The following queries and results are:
```
joern> importCode("./test") 
...
joern> cpg.local.referencingIdentifiers.inAssignment.target.code.l 
res150: List[String] = List("var1", "var1")
...
joern> cpg.local.referencingIdentifiers.inAssignment.source.code.l 
res151: List[String] = List("(long)(var2 + 20)", "(long)(var2 + 20)")
...
joern> cpg.local.referencingIdentifiers.where(_.inAssignment).code.l 
res154: List[String] = List("var1", "var2")
...
joern> cpg.local.referencingIdentifiers.where(_.inAssignment.target).code.l 
res152: List[String] = List("var1", "var2")
...
joern> cpg.local.referencingIdentifiers.where(_.inAssignment.source).code.l 
res153: List[String] = List("var1", "var2")
```
So it appears that while the queries for target and source differentiate correctly, when using them in a where step they are not applied after the inAssignment step.

**Comment by mpollmeier** [comment]
I think I understand your confusion here. Let me try to explain by clarifying what the `where` step does: it's a filter step, it keeps all elements for which there is at least one result in the given subtraversal. 
To phrase your bottom traversal in english: `cpg.local.referencingIdentifiers.where(_.inAssignment.source).code` means "for all locals, find me their referencing identifiers which are part of an assignment, in which there _is a_ source, and get me their code". 

Is it possible that you wanted to express "in which _it is the_ source", or am I on the wrong path here?

**Comment by jryerb** [comment]
Yep, in which it is/is in the source or target is the path I'm on. The there is a source vs it is/is in the source was the distinction I was missing.
