### ISSUE TITLE
A question about a full CPG of a function

### ISSUE THREAD

**Issue by BodyCSoulN** [joernio/joern#1040]
Hello, thanks for your strong tool.
I have a question about it.
I have a file with only one function in it.
If I want to get a complete CPG of this function, what should I do?
Maybe when to stop query is a confused problem>
Thanks!

**Comment by ursachec** [comment]
Hi there. The documentation shows you how to generate the CPG for a file with one function in it https://docs.joern.io/quickstart

**Comment by BodyCSoulN** [comment]
> Hi there. The documentation shows you how to generate the CPG for a file with one function in it https://docs.joern.io/quickstart

I am sorry.
I still use a old version of joern.
Below is its documentation.
https://joern.readthedocs.io/en/latest/index.html
In the old version of joern, the cpg is save at a neo4j database. 
So I want to know how to get a complete CPG of a function in a neo4j database.

**Comment by ursachec** [comment]
I'd suggest you use the latest version of Joern. We're a small team of contributors and can't provide support for deprecated versions

**Comment by mpollmeier** [comment]
> This version of joern has been discontinued.
> Joern lives on at https://github.com/ShiftLeftSecurity/joern

https://github.com/octopus-platform/joern

**Comment by BodyCSoulN** [comment]
> I'd suggest you use the latest version of Joern. We're a small team of contributors and can't provide support for deprecated versions
Thanks!

**Comment by BodyCSoulN** [comment]
> > This version of joern has been discontinued.
> > Joern lives on at https://github.com/ShiftLeftSecurity/joern
> 
> https://github.com/octopus-platform/joern

Thanks so much.
