### ISSUE TITLE
Global variables not detected

### ISSUE THREAD

**Issue by sciencemanx** [joernio/joern#108]
```c
int x;

int main() {
    return 0;
}
```
shows no reference to variable x when run through joern.

Looking at fuzzyc2cpg [1](https://github.com/ShiftLeftSecurity/fuzzyc2cpg/blob/master/src/main/antlr4/io/shiftleft/fuzzyc2cpg/Module.g4#L76) and [2](https://github.com/ShiftLeftSecurity/fuzzyc2cpg/blob/master/src/main/antlr4/io/shiftleft/fuzzyc2cpg/Module.g4#L21), it appears this should be handled.

**Comment by fabsx00** [comment]
Yes, this should be handled. What do you mean by "shows no references to" exactly?

**Comment by sciencemanx** [comment]
@fabsx00 "shows no references to" means that "x" "int x" etc. does not exist in the cpg.zip database.  

Additionally, I have found that while the database created from
```c
typedef int size_t;
void *malloc(size_t x);
```
contains to information (or any reference to) malloc, the following does
```c
typedef int size_t;
void *malloc(size_t x) {

}
```

**Comment by sciencemanx** [comment]
Therefore, it appears that any declarations are skipped while definitions are added to the database.

**Comment by GlassAndOneHalf** [comment]
In regards to the first item, it seems that we only processes top-level identifier declarations if they are `typedef`s. See https://github.com/ShiftLeftSecurity/fuzzyc2cpg/blob/master/src/main/scala/io/shiftleft/fuzzyc2cpg/astnew/AstToCpgConverter.scala#L593-L594

At first glance, it seems we will need to change the existing code to create a `LOCAL` or `IDENTIFIER` node at the top level of the AST. Alternatively we start construction of the CFG with by beginning with a "global scope" pushed on the scope stack (currently the scope stack is initialized to be empty), and then add any corresponding nodes as before.

As for the second item (erased function declarations), with the code you have provided I am unable to reproduce the issue you are having:

Code:
```c
typedef int size_t;
void *malloc(size_t x);
```
Query:
```
joern> cpg.method.l 
res12: List[Method] = List(
  Method(
    id -> 8L,
    name -> "malloc",
    fullName -> "malloc",
    isExternal -> false,
    signature -> "void*(size_t)",
    astParentType -> null,
    astParentFullName -> null,
    lineNumber -> Some(2),
    columnNumber -> Some(0),
    lineNumberEnd -> Some(2),
    columnNumberEnd -> Some(22),
    order -> null,
    hasMapping -> None,
    depthFirstOrder -> None,
    binarySignature -> None
  )
)
```

**Comment by GlassAndOneHalf** [comment]
See https://github.com/ShiftLeftSecurity/fuzzyc2cpg/pull/156

**Comment by itsacoderepo** [comment]
@sciencemanx 

Current version of joern (v1.1.440) is handling `x` as a local.   

Based on your initial code snippet, you should be able to query for `x` with:
```
joern> cpg.local.l
res4: List[Local] = List(
  Local(
    id -> 3074457345618258674L,
    closureBindingId -> None,
    code -> "int x",
    columnNumber -> None,
    dynamicTypeHintFullName -> ArraySeq(),
    lineNumber -> Some(value = 1),
    name -> "x",
    order -> 1,
    typeFullName -> "int"
  )
)
```

Closing..
