### ISSUE TITLE
Incorrect CFG for for-stmt

### ISSUE THREAD

**Issue by a0x77n** [joernio/joern#1093]
Hi all,
the control flow generated for the for-stmt in the following snippet is incorrect:

```
void foo() {
  for (int x=1,y=1; x; --x) {}
}
```

The for-stmt has 7 children (2 locals, 2 assignments, condition, loop expr, body), which makes sense to me. However, the `CfgCreator` skips the two locals and takes the third child (first assignment) as init expr, the fourth child (second assignment) as condition, and so on.

Alwin

**Comment by max-leuthaeuser** [comment]
Thanks for the report. 
The linked PR fixes this issue.
