### ISSUE TITLE
Mac homebrew forumla

### ISSUE THREAD

**Issue by CaledoniaProject** [joernio/joern#1107]
Can you create a Mac homebrew formula?

**Comment by iandinwoodie** [comment]
I've added a homebrew formula for this project and the [PR](https://github.com/Homebrew/homebrew-core/pull/120622) is currently pending review.

**Comment by mpollmeier** [comment]
Thank you! 
@max-leuthaeuser can you take a look at the discussion about the astgen fork please?
I'll quickly check if we have any issues with JDK17.

**Comment by iandinwoodie** [comment]
Just to note, I lifted the JDK 11 restriction in the Homebrew formula. However, we will still need to address their astgen concerns which @max-leuthaeuser seems to be on top of.

**Comment by mpollmeier** [comment]
it's deforked: https://github.com/joernio/astgen
![grafik](https://user-images.githubusercontent.com/506752/212835114-c2626a4a-65d9-403e-b196-ae759605fc5f.png)

**Comment by mpollmeier** [comment]
we've also just upgraded our default JDK to 17: https://github.com/joernio/joern/pull/2182

**Comment by iandinwoodie** [comment]
The Homebrew formula is now available! The command to install joern is:

```bash
brew install joern
```
