### ISSUE TITLE
Compalitible with Windows? Steps for installation in Windows

### ISSUE THREAD

**Issue by kiranravindran90** [joernio/joern#1118]
Is Joern compatible with Windows 10? If yes, what are the steps to be followed? I couldnt find the steps for Windows in the documentation or not sure if I am missing something.

**Comment by max-leuthaeuser** [comment]
All frontends and the joern cli are compatible, yes.

Just `git clone` the repo and run `sbt stage` there. You will find executables, e.g.,:
- for joern cli: `path\to\joern\joern-cli\target\universal\stage\bin\ammonite-bridge`
- for c2cpg: `path\to\joern\joern-cli\frontends\c2cpg\target\universal\stage\bin`

**Comment by kiranravindran90** [comment]
Thank you for the steps. I tried this steps but getting this error (shown below).
__________________________________________________________________________
$ sbt stage
Picked up _JAVA_OPTIONS: -Xmx512M
copying runtime jar...
mkdir: cannot create directory ‘’: No such file or directory
Picked up _JAVA_OPTIONS: -Xmx512M
Error occurred during initialization of VM
Initial heap size set to a larger value than the maximum heap size
Picked up _JAVA_OPTIONS: -Xmx512M
Error occurred during initialization of VM
Initial heap size set to a larger value than the maximum heap size
__________________________________________________________________________

I am not sure if this is because of the available amount of memory.
If I have to configure JVM to avoid this error, what would be the recommended memory size?

**Comment by mpollmeier** [comment]
looks like you should clear or redefine some of your environment variables...

**Comment by max-leuthaeuser** [comment]
Try to set -Xmx to something larger, 4G or 8G should do it depending on your system.
