### ISSUE TITLE
Empty DDG

### ISSUE THREAD

**Issue by shijy16** [joernio/joern#1126]
I am trying to dump DDG of a cpg.bin.zip generated from LLVM IR using llvm2cpg as described in doc.
There are some warnings in the import stage:
````
joern> importCpg("cpg.bin.zip") 
Creating project `cpg.bin.zip` for CPG at `cpg.bin.zip` 
You have provided a legacy proto CPG. Attempting conversion.
2022-03-20 17:04:23.571 WARN PropertyErrorRegister$: Property UNRECOGNIZED is deprecated for io.shiftleft.codepropertygraph.generated.nodes.MetaDataDb.
2022-03-20 17:04:23.638 WARN PropertyErrorRegister$: Property UNRECOGNIZED is deprecated for io.shiftleft.codepropertygraph.generated.nodes.CallDb.
2022-03-20 17:04:23.648 WARN PropertyErrorRegister$: Property UNRECOGNIZED is deprecated for io.shiftleft.codepropertygraph.generated.nodes.MethodRefDb.
Creating working copy of CPG to be safe
Loading base CPG from: /home/sjy/code/workspace/cpg.bin.zip/cpg.bin.tmp
Adding default overlays to base CPG 
The graph has been modified. You may want to use the `save` command to persist changes to disk.  All changes will also be saved collectively on exit
res0: Option[Cpg] = Some(value = io.shiftleft.codepropertygraph.generated.Cpg@298f7b0a)
````
It seems okay.
But when I export DDG with the following commands, I get empty graph:
````
run.dumpddg
cpg.method("FunctionA").dotDdg.p
````
The DDG be like:
````
digraph "FunctionA" {
}
````
The CDG seems okay btw.

**Comment by shijy16** [comment]
I figured that I missed the following command before trying to get DDG:
````
run.ossdataflow
````
It is clearly described in the doc... Sorry for bothering.

**Comment by mzzsmf** [comment]
> 我正在尝试转储 cpg 的 DDG.bin.zip使用 llvm2cpg 从 LLVM IR 生成，如文档中所述。在导入阶段有一些警告：
> 
> ```
> joern> importCpg("cpg.bin.zip") 
> Creating project `cpg.bin.zip` for CPG at `cpg.bin.zip` 
> You have provided a legacy proto CPG. Attempting conversion.
> 2022-03-20 17:04:23.571 WARN PropertyErrorRegister$: Property UNRECOGNIZED is deprecated for io.shiftleft.codepropertygraph.generated.nodes.MetaDataDb.
> 2022-03-20 17:04:23.638 WARN PropertyErrorRegister$: Property UNRECOGNIZED is deprecated for io.shiftleft.codepropertygraph.generated.nodes.CallDb.
> 2022-03-20 17:04:23.648 WARN PropertyErrorRegister$: Property UNRECOGNIZED is deprecated for io.shiftleft.codepropertygraph.generated.nodes.MethodRefDb.
> Creating working copy of CPG to be safe
> Loading base CPG from: /home/sjy/code/workspace/cpg.bin.zip/cpg.bin.tmp
> Adding default overlays to base CPG 
> The graph has been modified. You may want to use the `save` command to persist changes to disk.  All changes will also be saved collectively on exit
> res0: Option[Cpg] = Some(value = io.shiftleft.codepropertygraph.generated.Cpg@298f7b0a)
> ```
> 
> 似乎没问题。但是当我使用以下命令导出DDG时，我得到空图形：
> 
> ```
> run.dumpddg
> cpg.method("FunctionA").dotDdg.p
> ```
> 
> DDG是这样的：
> 
> ```
> digraph "FunctionA" {
> }
> ```
> 
> 顺便说一句，CDG似乎还可以。

你好，我想问一下llvm2cpg应该怎么安装，我之前没有安装经验，也没有找到详细的安装流程，麻烦了

**Comment by shijy16** [comment]
> > 我正在尝试转储 cpg 的 DDG.bin.zip使用 llvm2cpg 从 LLVM IR 生成，如文档中所述。在导入阶段有一些警告：
> > ```
> > joern> importCpg("cpg.bin.zip") 
> > Creating project `cpg.bin.zip` for CPG at `cpg.bin.zip` 
> > You have provided a legacy proto CPG. Attempting conversion.
> > 2022-03-20 17:04:23.571 WARN PropertyErrorRegister$: Property UNRECOGNIZED is deprecated for io.shiftleft.codepropertygraph.generated.nodes.MetaDataDb.
> > 2022-03-20 17:04:23.638 WARN PropertyErrorRegister$: Property UNRECOGNIZED is deprecated for io.shiftleft.codepropertygraph.generated.nodes.CallDb.
> > 2022-03-20 17:04:23.648 WARN PropertyErrorRegister$: Property UNRECOGNIZED is deprecated for io.shiftleft.codepropertygraph.generated.nodes.MethodRefDb.
> > Creating working copy of CPG to be safe
> > Loading base CPG from: /home/sjy/code/workspace/cpg.bin.zip/cpg.bin.tmp
> > Adding default overlays to base CPG 
> > The graph has been modified. You may want to use the `save` command to persist changes to disk.  All changes will also be saved collectively on exit
> > res0: Option[Cpg] = Some(value = io.shiftleft.codepropertygraph.generated.Cpg@298f7b0a)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 似乎没问题。但是当我使用以下命令导出DDG时，我得到空图形：
> > ```
> > run.dumpddg
> > cpg.method("FunctionA").dotDdg.p
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > DDG是这样的：
> > ```
> > digraph "FunctionA" {
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 顺便说一句，CDG似乎还可以。
> 
> 你好，我想问一下llvm2cpg应该怎么安装，我之前没有安装经验，也没有找到详细的安装流程，麻烦了

在llvm2cpg的仓库 https://github.com/ShiftLeftSecurity/llvm2cpg 的release页面直接下载二进制程序就能用

**Comment by damaoooo** [comment]
你好，请问您用的是什么版本呢，我发现最新版的Joern已经不支持读取llvm2cpg的cpg文件了

**Comment by shijy16** [comment]
> 你好，请问您用的是什么版本呢，我发现最新版的Joern已经不支持读取llvm2cpg的cpg文件了

应该是1.1.628，当时的最新版

**Comment by itsacoderepo** [comment]
Hello @shijy16 @mzzsmf @damaoooo!

please keep the conversation in english, other people might also want to understand it.
