### ISSUE TITLE
Points-to Analysis

### ISSUE THREAD

**Issue by lorenz9314** [joernio/joern#1128]
I was wondering whether or not Joern performs a points-to analysis (e.g. Andersen's points-to analysis) to infer data dependencies. The only clue I could find as to what kind of analysis is done, was a comment in the file `DataFlowProblem.scala` referring to the dragon book and as far as I know the book doesn't consider pointers in their analysis.

I am sorry, I realize I could likely find the answer by myself, but I have little time to do so. Thus I was hoping someone could give me a quick answer to this. Thanks in advance!

**Comment by DavidBakerEffendi** [comment]
This is currently being introduced slowly via #1249 and #1344

**Comment by lorenz9314** [comment]
Good to know, thanks for the info. Looking forward to trying out the results!
