### ISSUE TITLE
Use python work with Joern

### ISSUE THREAD

**Issue by BodyCSoulN** [joernio/joern#1170]
Hi, 
Thanks for your great job. I have some questions about joern.
Could I use python to generate the CPG of codes and analysis CPG with python?
Could I use python to get a full CPG of a function or manipulate CPG with python?

**Comment by peng-hui** [comment]
You can use `joern-parse` and `joern-export` to generate dot files for CPG and other graphs. Then you can use python the analyze the dot files. For example, you can use networkx.

**Comment by BodyCSoulN** [comment]
Thanks for your answering.

You helped me a lot.
