### ISSUE TITLE
how to handle the goto statement ?

### ISSUE THREAD

**Issue by hrshy0629** [joernio/joern#1196]
when I want to parse my code.  I get some issues.
 If your code uses "goto" in C language, the Joern does not parse the statement.
I try to use two methods such as c2cpg.sh **.c and then importCpg and  importCode in Joern-cli. But both ways do not parse "goto" statement.
How can I handle the issue?

**Comment by max-leuthaeuser** [comment]
Goto is definitely supported.
See e.g.,: 
 - https://github.com/joernio/joern/blob/master/joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/standard/ControlStructureTests.scala
 - https://github.com/joernio/joern/blob/master/joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/CfgCreationPassTests.scala#L285

**Comment by hrshy0629** [comment]
Ok, I'll check it carefully.
