### ISSUE TITLE
Bash file in Windows - CreateProcess error=193, %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by kiranravindran90** [joernio/joern#1221]
While I tried to create a project, I am getting this below error. I believe its probable because of Windows trying to execute Bash files. But not sure what would be a work around.

Error message :
_____________________________________________________
**java.io.IOException: Cannot run program ".......\joern-master\joern-cli\target\universal\stage\c2cpg.sh": CreateProcess error=193, %1 is not a valid Win32 application**
  java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
  java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
  scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:85)
  scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:117)
  scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:116)
  io.joern.console.cpgcreation.CpgGenerator.runShellCommand(CpgGenerator.scala:27)
  io.joern.console.cpgcreation.CCpgGenerator.generate(CCpgGenerator.scala:21)
  io.joern.console.cpgcreation.CpgGeneratorFactory.runGenerator(CpgGeneratorFactory.scala:63)
  io.joern.console.cpgcreation.ImportCode.$anonfun$apply$5(ImportCode.scala:132)
  scala.Option.flatMap(Option.scala:283)
  io.joern.console.cpgcreation.ImportCode.io$joern$console$cpgcreation$ImportCode$$apply(ImportCode.scala:130)
  io.joern.console.cpgcreation.ImportCode.apply(ImportCode.scala:38)
  ammonite.$sess.cmd1$.<clinit>(cmd1.sc:1)
java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
  java.lang.ProcessImpl.create(Native Method)
  java.lang.ProcessImpl.<init>(ProcessImpl.java:487)
  java.lang.ProcessImpl.start(ProcessImpl.java:154)
  java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
  java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
  scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:85)
  scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:117)
  scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:116)
  io.joern.console.cpgcreation.CpgGenerator.runShellCommand(CpgGenerator.scala:27)
  io.joern.console.cpgcreation.CCpgGenerator.generate(CCpgGenerator.scala:21)
  io.joern.console.cpgcreation.CpgGeneratorFactory.runGenerator(CpgGeneratorFactory.scala:63)
  io.joern.console.cpgcreation.ImportCode.$anonfun$apply$5(ImportCode.scala:132)
  scala.Option.flatMap(Option.scala:283)
  io.joern.console.cpgcreation.ImportCode.io$joern$console$cpgcreation$ImportCode$$apply(ImportCode.scala:130)
  io.joern.console.cpgcreation.ImportCode.apply(ImportCode.scala:38)
  ammonite.$sess.cmd1$.<clinit>(cmd1.sc:1)
_____________________________________________________________________

**Comment by simIDe** [comment]
Hi, 
I'm having the same issue. Did you find a way to manage it?

**Comment by max-leuthaeuser** [comment]
We currently do not provide a Windows version of the shell scripts required to run the individual frontends, i.e., a .bat file.
Until this is fixed: I recommend to simply run the frontends standalone via their shell script within the Git Shell for Windows. And import the CPG into joern afterwards.
