### ISSUE TITLE
Wrong type of the static variable，missing `static`

### ISSUE THREAD

**Issue by YoungBrady** [joernio/joern#1256]
Hi, I used the latest version of joern(v1.1.717) to parse the following code:
```
void test()
{
static int a,b,c;
}
```
but the type of `a` is int,missing `static`,and other types like `const` has the same problem
```
joern> importCode.c.fromString(s"""void test() { static int a = 5; }  """)
...

joern> cpg.local.name("a").typ.referencedTypeDecl.fullName.l
res1: List[String] = List("int")

cpg.local.name("a").typ.referencedTypeDecl.modifier.l
res2: List[Modifier] = List()
```

**Comment by max-leuthaeuser** [comment]
The type name is int, yes. But the locals code field will contain static.

**Comment by mpollmeier** [comment]
Interestingly, the code field doesn't contain `static`.

```
joern> cpg.local.l
res1: List[Local] = List(
  Local(
    id -> 9L,
    closureBindingId -> None,
    code -> "int a",
    columnNumber -> None,
    dynamicTypeHintFullName -> ArraySeq(),
    lineNumber -> Some(value = 1),
    name -> "a",
    order -> 1,
    typeFullName -> "int"
  )
)


cpg.all.property[String]("CODE").filter(_.contains("static")).l
res2: List[String] = List()
```

Anyway, the main thing is that it's documented and on your list. 
Thanks @YoungBrady for reporting!

**Comment by max-leuthaeuser** [comment]
Ah yes, we strip those away here: https://github.com/joernio/joern/blob/2a54c3b2faf41d66f48cd9f2e6bc59b449b274fa/joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala#L146

This is on purpose as we do not want to have `static int` and `int` as distinct types floating around. Nevertheless, the modifier should be there.

**Comment by max-leuthaeuser** [comment]
The code field contains the modifier now.
