### ISSUE TITLE
javasrc2cpg: detect configFiles and create nodes

### ISSUE THREAD

**Issue by mpollmeier** [joernio/joern#1265]
In order to detect e.g. hardcoded secrets in configFiles, java2cpg creates `ConfigFile` nodes, and javasrc2cpg should do the same eventually. 

e.g.
https://github.com/ShiftLeftSecurity/HelloShiftLeft -> java2cpg -> `cpg.configFile.size` -> 162

**Comment by johannescoetzee** [comment]
This was added in https://github.com/joernio/joern/pull/1638. For the HelloShiftLeft project, javasrc2cpg only finds the 4 config files in the repo and does not find anything for the dependencies. We could look for those when fetching dependency jars, but that feels like unnecessary extra complexity (please correct me if I'm wrong here)
