### ISSUE TITLE
How to get the CPG nodes and edges?

### ISSUE THREAD

**Issue by BodyCSoulN** [joernio/joern#1280]
Hi,
Thanks for your greate job.

I want to get the nodes and edges of a cpg?

It seems like there not such a method.

What should I do?

**Comment by mpollmeier** [comment]
`cpg.all`, `cpg.graph.nodes` are two of many ways to get the nodes. Edges mostly exist as connections between nodes, so if you want to keep it generic, you can run `.outE` or `.inE` or `.bothE` on any node. 

Does that make sense?

**Comment by BodyCSoulN** [comment]
Thank for your answering.

I remeber that joern could offer the `.CSV` files of the nodes and edges of a CPG.

Which version of it?

**Comment by mpollmeier** [comment]
we don't currently support import/export formats, but i happen to be working on it at the moment, ETA next week I guess

**Comment by BodyCSoulN** [comment]
Thanks for your patient answering.

Hope it coming soon!

Thanks!
