### ISSUE TITLE
A problem about `int &` in c++

### ISSUE THREAD

**Issue by YoungBrady** [joernio/joern#1297]
Source code:
```
static void badSource(int &data)
{
    ……
}

void bad()
{
   ……
    badSource(data);
   ……
}
```

the type of data is` int*`,I think it is wrong
```
joern> cpg.method("badSource").parameter.l 
res12: List[MethodParameterIn] = List(
  MethodParameterIn(
    id -> 9L,
    code -> "int &data",
    columnNumber -> Some(value = 23),
    dynamicTypeHintFullName -> ArraySeq(),
    evaluationStrategy -> "BY_VALUE",
    index -> 1,
    isVariadic -> false,
    lineNumber -> Some(value = 29),
    name -> "data",
    order -> 1,
    typeFullName -> "int*"
  )
```
In the `bad` function,there is a call `badSource`,but it's callee is wrong,I guess the reason is the wrong type `int*`

**Comment by YoungBrady** [comment]
@[max-leuthaeuser](https://github.com/max-leuthaeuser) the callee of `badSource` is still wrong in joern(v1.1.751），is there any plan to solve this  problem?
```
joern> cpg.call.id(47).callee.l 
res10: List[Method] = List(
  Method(
    id -> 222L,
    astParentFullName -> "<global>",
    astParentType -> "NAMESPACE_BLOCK",
    code -> "<empty>",
    columnNumber -> None,
    columnNumberEnd -> None,
    filename -> "<empty>",
    fullName -> "badSource",
    hash -> None,
    isExternal -> true,
    lineNumber -> None,
    lineNumberEnd -> None,
    name -> "badSource",
    order -> 0,
    signature -> ""
  )
)
```

**Comment by max-leuthaeuser** [comment]
> @[max-leuthaeuser](https://github.com/max-leuthaeuser) the callee of `badSource` is still wrong in joern(v1.1.751），is there any plan to solve this problem?
> 
> ```
> joern> cpg.call.id(47).callee.l 
> res10: List[Method] = List(
>   Method(
>     id -> 222L,
>     astParentFullName -> "<global>",
>     astParentType -> "NAMESPACE_BLOCK",
>     code -> "<empty>",
>     columnNumber -> None,
>     columnNumberEnd -> None,
>     filename -> "<empty>",
>     fullName -> "badSource",
>     hash -> None,
>     isExternal -> true,
>     lineNumber -> None,
>     lineNumberEnd -> None,
>     name -> "badSource",
>     order -> 0,
>     signature -> ""
>   )
> )
> ```

Looks like a different problem.
Could you create a new issue only for that please?
