### ISSUE TITLE
Code analysis with joern-tools

### ISSUE THREAD

**Issue by marius-benthin** [joernio/joern#1323]
I am trying to update a system that uses an old version (**0.3.1**) of [joern](https://github.com/octopus-platform/joern) in combination with [`joern-tools`](https://github.com/octopus-platform/joern-tools). 
Unfortunately, the `joern-tools` only work with the old version of joern, which still used a Neo4j graph database.
Does anyone have a piece of advice on how I can use the `joern-tools` along with the new version without importing the code property graphs into a Neo4j graph database? I am grateful for any hint. :)

**Comment by itsacoderepo** [comment]
Hi @marius-benthin,

your tasks sounds a bit to complicated to solve in a GH issue. I would recommend you to use the new joern only.

We could offer you to join our discord server, you should be able to write me there.
