### ISSUE TITLE
(C/C++) Is there any switch to set whether to analyse the exteral headers or not?

### ISSUE THREAD

**Issue by NemoTR** [joernio/joern#1327]
Since we may not care about standard libraries, we start to need a switch to stop analysing these headers.
With this feature, we can reduce the amount of the nodes and edges, which can make our parsing work faster.
Now I cannot find this switch, so I have to uninstall the gcc. This does not feel good.

**Comment by max-leuthaeuser** [comment]
`--no-include-auto-discovery` exists which ca also be seen when running `./c2cpg.sh --help`

**Comment by NemoTR** [comment]
> `--no-include-auto-discovery` exists which can also be seen when running `./c2cpg.sh --help`

@max-leuthaeuser I really appreciate your reply. This totally solved my problem. 

While I was using c2cpg, I found that c2cpg also does **not** generate the dataflowOss overlay automatically. Hope you can notice that.

Additionally, is there any similar argument like `--no-include-auto-discovery` for joern-parse?

**Comment by max-leuthaeuser** [comment]
> While I was using c2cpg, I found that c2cpg also does **not** generate the dataflowOss overlay automatically. Hope you can notice that.

Yes, thats intended. None of the frontends does it on its own.
However, it should be applied within Joern (once https://github.com/joernio/joern/issues/1327#issuecomment-1114672039 is resolved).

> Additionally, is there any similar argument like `--no-include-auto-discovery` for joern-parse?

Yes. You should be able to pass frontends args there (`--frontend-args`).
See: https://github.com/joernio/joern/blob/master/joern-cli/src/main/scala/io/joern/joerncli/JoernParse.scala#L53

**Comment by NemoTR** [comment]
I got it. Much appreciated！
