### ISSUE TITLE
(C/C++) Still need to run 'run.ossdataflow' to get the ossdataflow layer after 'importCode' while simply using joern-parse does not.

### ISSUE THREAD

**Issue by NemoTR** [joernio/joern#1328]

**Comment by NemoTR** [comment]
This doesn't match the official documentation:
![image](https://user-images.githubusercontent.com/50135026/166193355-08d66d99-e9b8-482d-9ab5-6890e8b784e4.png)

**Comment by pr0me** [comment]
This is true for jssrc2cpg, too, you still need to manually run the command.

**Comment by Liyw979** [comment]
You should have document that. Really annoying.
