### ISSUE TITLE
Improved P-Code support

### ISSUE THREAD

**Issue by drone-rites** [joernio/joern#1362]
Hello! I'd like to help add support for generating Low and High P-Code CPGs. I've seen there has been some existing work on P-Code support but it appears to be a work in progress. I tried reaching out on Discord and haven't yet received a response; I'm hoping this feature request might help kickstart the conversation.

Myself and several of my colleagues are able to spend substantial time on this effort, but before getting started we'd like to first understand the current status of P-Code support, existing plans for improving that support, and any suggestions for how we can best help.

Thanks and take care!

**Comment by fabsx00** [comment]
@drone-rites Niko (@itsacoderepo) will contact you on discord about this.

**Comment by itsacoderepo** [comment]
I already did :), closing the issue for now..
