### ISSUE TITLE
(C/C++) Lost REACHING_DEF edge in statement 'a = a + 1' or 'a = a + i'

### ISSUE THREAD

**Issue by NemoTR** [joernio/joern#1365]
Here is the test code:
```C++
int f()
{
    int a = 10;
    a = a + 1;
    for (int i = 1; i <= 10; i++)
        a = a + i;
    return a;
}
```
There should be a REACHING_DEF edge from `a + 1` ('CALL' node) to `a = a + 1` ('CALL' node) and a REACHING_DEF edge from `a + i` ('CALL' node) to `a = a + i` ('CALL' node)
However, here is the ddg of `f`:
![image](https://user-images.githubusercontent.com/50135026/167148905-a988ab25-fa4c-45a8-8f88-f0b867449a9e.png)
The above-mentioned REACHING_DEF edges are **LOST**!
The `a + 1` ('CALL' node) and  `a + i` ('CALL' node) have no out edge at all!

**Comment by fabsx00** [comment]
The major rewrite is merged. Please test again.

**Comment by NemoTR** [comment]
Tried on version 1.1.891, still not fixed.
![image](https://user-images.githubusercontent.com/50135026/173979116-90ece7c4-90a2-4f17-990f-c23f9532d424.png)

**Comment by itsacoderepo** [comment]
@NemoTR can you test again?

**Comment by itsacoderepo** [comment]
Closing because it seems outdated
