### ISSUE TITLE
Control Flow documentation not significantly descriptive

### ISSUE THREAD

**Issue by jahatfi** [joernio/joern#1369]
A number of terms ("controls", "controlledBy", "dominates", etc) are used in this page: https://docs.joern.io/cpgql/control-flow-steps, but not defined.  In fact, each word is used in its own definition, which provides no additional information, e.g.:

**dominates**

dominates is a Control-Flow Step which determines all nodes that are dominated by this node.

  Examples are provided, but it'd be great to have meaningful definitions as well, as I'm still trying to understand the difference based on the examples provided.  This link may be helpful: https://developers.google.com/tech-writing/one/words

Thanks!

**Comment by jahatfi** [comment]
I found more details here https://docs.joern.io/cpgql/reference-card, but it's be great reference them on the page above.

**Comment by ursachec** [comment]
we might improve the docs soon, in the meantime, we accept prs
