### ISSUE TITLE
"outE" and "outV" traversals don't work in "map" traversal

### ISSUE THREAD

**Issue by NemoTR** [joernio/joern#1372]
Edge travesal in map seems doesn't work:
![image](https://user-images.githubusercontent.com/50135026/167398180-11875a07-0ccb-4b3c-b7b4-5bfbebf6ab89.png)

Is this normal?

_Originally posted by @NemoTR in https://github.com/joernio/joern/issues/1367#issuecomment-1120950693_

**Comment by itsacoderepo** [comment]
@NemoTR Do you still need an answer for this?

**Comment by NemoTR** [comment]
> @NemoTR Do you still need an answer for this?

No, thanks.
