### ISSUE TITLE
Unable to Tag Nodes

### ISSUE THREAD

**Issue by ojaswa1942** [joernio/joern#1379]
Yoern version: `latest` (10/05/2022)

Receiving the following error on tagging:
```
joern> cpg.identifier.where(_.name(".*firstName.*")).newTagNode("DE").store 

cmd45.sc:1: could not find implicit value for parameter diffGraph: io.shiftleft.passes.DiffGraph.Builder
val res45 = cpg.identifier.where(_.name(".*firstName.*")).newTagNode("DE").store
                                                                           ^
Compilation Failed
```

This is replicable with all kinds of queries for both `newTagNode` and `newTagNodePair` - tested on multiple systems.

**Comment by tuxology** [comment]
Some more context, test was done with Java Src parser and with `shiftleft-java-example` repo

**Comment by maltek** [comment]
with the current API you have to do this:

```
 cpg.identifier.where(_.name(".*firstName.*")).foreach(ident => diffGraph.addEdge(ident, NewTag().name("DE").value(""), EdgeTypes.TAGGED_BY))
```

**Comment by mpollmeier** [comment]
The API should still be the same as per documentation, i.e. `.store` is correct, but as you reported it doesn't work at the moment. The underlying implementation was changed though, and not all places got adapted unfortunately. I'm completing the migration at the moment, will let you know once it's done. 

Links
https://github.com/ShiftLeftSecurity/overflowdb/pull/224
https://github.com/joernio/joern/pull/1002/

**Comment by mpollmeier** [comment]
Will be fixed once https://github.com/joernio/joern/pull/1382 is merged.

**Comment by ojaswa1942** [comment]
Awesome
