### ISSUE TITLE
joern parse error

### ISSUE THREAD

**Issue by Joel-MalwareBenchmark** [joernio/joern#1420]
Parsing with joern returns only an error result.
The source program is in the attachment.

joern> cpg.method.name.l 
res2: List[String] = List("<global>")

[case.zip](https://github.com/joernio/joern/files/8749035/case.zip)

**Comment by max-leuthaeuser** [comment]
I guess `HAVE_OPENCL` has to be set.

**Comment by Joel-MalwareBenchmark** [comment]
How to automatically set the macro definition？This is just one of many programs.

**Comment by max-leuthaeuser** [comment]
Unfortunately, this can't be done automatically here. We are re-using the Eclipse CDT parser which tries to stay as close as possible to the official GCC behavior.

You could run c2cpg with `--print-ifdef-only` first, which prints a comma-separated list of all preprocessor ifdef and if statements but does not create a CPG. With this list you may be able to set a lot of the defines for the actual c2cpg run afterwards. But keep in mind that real-world C/C++ programs tend to have contradicting defines. Setting them all at once may lead to code that does not make any sense at all.

**Comment by max-leuthaeuser** [comment]
Also you can have a look into the programs MAKEFILE you are testing. It most likely contains a set of defines already.
