### ISSUE TITLE
`kotlin2cpg` unit test suite needs performance improvements

### ISSUE THREAD

**Issue by claudiuvursache** [joernio/joern#1440]
takes up to 2min on a mid-range consumer laptop

**Comment by ursachec** [comment]
down to _30s - 1min_ thanks to https://github.com/joernio/joern/pull/1451

**Comment by mpollmeier** [comment]
![grafik](https://user-images.githubusercontent.com/506752/171137981-640bdf2c-bc73-4985-8ac5-be7b0a3cbe34.png)
😛

**Comment by ursachec** [comment]
on a more powerful machine it's ~10s atm

![time2](https://user-images.githubusercontent.com/497951/171143993-e33c451b-2e37-43a8-a5ea-dfbeebb81ced.png)


```
echo "number of cores: " $(grep 'cpu cores' /proc/cpuinfo | uniq | awk '{print $4}') && echo $(awk '/model name/{$1="";$2="";$3=""; print $0;}' /proc/cpuinfo | uniq)
number of cores:  8
Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
```

**Comment by claudiuvursache** [comment]
current state isn't too bad as to have this be a top priority, closing
