### ISSUE TITLE
Default frontend for Javascript

### ISSUE THREAD

**Issue by pr0me** [joernio/joern#1468]
Currently, joern-cli still builds with the original `js2cpg` frontend for javascript.

As that frontend is not part of the joern repository anymore, should it be replaced with the new
`jssrc2cpg` as the default or is that still too much WIP?

Will create a corresponding PR.

**Comment by max-leuthaeuser** [comment]
> As that frontend is not part of the joern repository anymore

Well, it never has been.

> or is that still too much WIP?

It kinda is, yes. It creates the same CPGs for plain JS code and understands some TS constructs but
as it does not transpile anything like js2cpg does, things build on-top of JS (frontend stuff e.g., JSX/TSX) are missing. 
Also, there is currently no support for [TS type annotations](https://www.tutorialsteacher.com/typescript/type-annotation) at all.

**Comment by pr0me** [comment]
completed by #1563
