### ISSUE TITLE
Scaladoc generation failed

### ISSUE THREAD

**Issue by Kanbe-Kotori** [joernio/joern#1525]
https://pastebin.com/yyHhCJXf

**Comment by mpollmeier** [comment]
joern requires java 11, but your sbt output shows that you're using java 8:
```
PS E:\Dev\Java\Joern\joern> sbt stage
[info] welcome to sbt 1.6.2 (Oracle Corporation Java 1.8.0_301)
```
https://github.com/joernio/joern#requirements


Please either set your JAVA_HOME to java 11, or pass a java 11 home to sbt, e.g. `sbt -java-home /path/to/jdk11`

**Comment by Kanbe-Kotori** [comment]
Solved
