### ISSUE TITLE
Is there a way to go back to java2cpg parser?

### ISSUE THREAD

**Issue by thapr0digy** [joernio/joern#1529]
Is there a way to go back to the java2cpg parser from months back? I just updated joern  which uses javasrc2cpg and it's broken my CPG for a whole bunch of types where the old parser seemed to have no issues.

**Comment by fabsx00** [comment]
Actually, javasrc is just the new default for java, but the old bytecode-based frontend is still available. You can use the `--language` flag to choose it.
