### ISSUE TITLE
Joern install with specific version should not download latest querydb version

### ISSUE THREAD

**Issue by dbMundada** [joernio/joern#1570]
If I try to install specific version
`./joern-install.sh --version=v1.1.826`

further the script downloads the latest version of querydb
`https://github.com/joernio/joern/releases/latest/download/querydb.zip`
but should download
`https://github.com/joernio/joern/releases/download/v1.1.826/querydb.zip`

cc: @tuxology

**Comment by dbMundada** [comment]
Sorry, Issue is related to `./joern-install.sh --version=v1.1.826` script.

joern-scan actually solved the issue for me.
`joern-scan --updatedb --dbversion 1.1.826`

**Comment by ursachec** [comment]
alright great. just for future reference, `joern-install.sh` does not offer a `--version` setting
