### ISSUE TITLE
`cpg.method.typeDecl` missing (?)

### ISSUE THREAD

**Issue by fabsx00** [joernio/joern#1597]
It seems like - at least on the joern shell - there is no easy may to jump from a method to the type declaration it is defined in. While `cpg.typeDecl.method` works just fine, `cpg.method.typeDecl` seems to be missing.

**Comment by mpollmeier** [comment]
It's called `cpg.method.definingTypeDecl`. 
Should we add a step alias `typeDecl` for `definingTypeDecl`?

This is also a reminder implement a `schema -> dot` converter, so that we get a nice overview of nodes, relationships, cardinalities, properties, named steps, ...

**Comment by max-leuthaeuser** [comment]
@mpollmeier 
I have written https://github.com/max-leuthaeuser/CpgSchema2Dot a while ago. It used the old json based shema definition as input. Maybe you want to use that as a starting point.

**Comment by mpollmeier** [comment]
that looks useful, thanks for sharing!

**Comment by fabsx00** [comment]
Ah, interesting, ok. I think an alias would be great. When traversing from a call to the enclosing method, the step is just called `method` and not `definingMethod`, so, this seems like an inconsistency.
