### ISSUE TITLE
scala.MatchError while importCode

### ISSUE THREAD

**Issue by vishesh27k** [joernio/joern#1606]
importCode throwing error for repository - https://github.com/keycloak/keycloak
Cpg got generated but couldn't find some methods.

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/45128646/179346284-9c9173a9-3874-4615-86c4-7703c7447197.png">
<img width="666" alt="image" src="https://user-images.githubusercontent.com/45128646/179346298-9b672312-a739-466f-965c-9220e9cdeb36.png">

**Comment by mpollmeier** [comment]
I tested with keycloak, this is fixed
@vishesh27k thanks for repoorting
@johannescoetzee thanks for fixing
