### ISSUE TITLE
jssrc: wrong arguments for calls with field access receivers

### ISSUE THREAD

**Issue by maltek** [joernio/joern#1685]
e.g. the call at 
https://github.com/OWASP/NodeGoat/blob/7c293e721bd1e95be6f82475d295b9b10e3b584e/app/assets/js/chart/chart-data-morris.js#L10 has no arg 0, some weird identifier as arg 1 and the actual first argument as arg 2. It has a field access as receiver, but without argument edge.

```
ocular> cpg.call.code("Morris.Area\\(.*").argument.l 
res15: List[Expression] = List(             
  Identifier(                 
    id -> 1847L,
    argumentIndex -> 1,                      
    argumentName -> None,            
    code -> "Morris",     
    columnNumber -> Some(value = 8),      
    depthFirstOrder -> 68,
    dynamicTypeHintFullName -> ArraySeq(),
    internalFlags -> 4,
    lineNumber -> Some(value = 10),
    name -> "Morris",
    order -> 1,
    typeFullName -> "ANY"
  ),     
  Block(
    id -> 1162L,
    argumentIndex -> 2,
    argumentName -> None,
    code -> """{
            // ID of the element in which to draw the chart.
            element: "morris-chart-area",
            // Chart data records -- each entry in this array corresponds to a point on the chart.
            data: [{
....
ocular> cpg.call.code("Morris.Area\\(.*").receiver.l 
res16: List[Expression] = List(
  Call(
    id -> 1160L,
    argumentIndex -> 0,
    argumentName -> None,
    code -> "Morris.Area",
    columnNumber -> Some(value = 8),
    depthFirstOrder -> 67,
    dispatchType -> "STATIC_DISPATCH",
    dynamicTypeHintFullName -> ArraySeq(),
    internalFlags -> 4,
    lineNumber -> Some(value = 10),
    methodFullName -> "<operator>.fieldAccess",
    methodInstFullName -> None,
    name -> "<operator>.fieldAccess",
    order -> 0,
    resolved -> None,
    signature -> "",
    typeFullName -> "ANY"
  )
)
```

**Comment by max-leuthaeuser** [comment]
It looks weird. But the behavior should be identical to js2cpg. Could that be verified with a simpler minimal reproducing example in both frontends?

**Comment by maltek** [comment]
In joern, just a file with `a.b(x);` shows the same behavior for both frontends. (But there's no `importCode.jssrc.fromString` or `importCode.javascript.fromString` so this is way harder to test than it should be :smile: )

But in ocular(!) for that smaller example argument indices are correct / decreased by one for both frontends. In the original call that's only true for js2cpg.

(Apparently I never really looked at the 0th argument in js2cpg - I always thought it was exactly the same as the receiver.)
