### ISSUE TITLE
jssrc2cpg: empty `name` fields in `app.get(...)` `CALL` nodes

### ISSUE THREAD

**Issue by fabsx00** [joernio/joern#1728]
I've just been playing around with the new `jssrc2cpg` frontend and noticed that for calls of the form `app.get(...)`, the `name` field is empty. I would have expected it to either contain `get` or `<operator>.fieldAccess`, preferably the former.

**Comment by max-leuthaeuser** [comment]
That has been the state of the art since I started working on js2cpg. We never set names for calls. I do not remember the reason for that, but maybe Markus could help. Also, in the CS passes everything is done via the CODE field.

**Comment by fabsx00** [comment]
Ok. But can we set the field? It would make a lot of sense to have that field set so that one can easily lookup all calls to `get` without using a regular expression. I also noticed that there is not `METHOD` node for `get`, so, something like `cpg.method("get").callIn` also can't be used as a workaround at the moment.

**Comment by max-leuthaeuser** [comment]
As another workaround at the moment you could look at the receiver and its args:
https://github.com/joernio/joern/blob/master/joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/SimpleAstCreationPassTest.scala#L536

**Comment by max-leuthaeuser** [comment]
(and there is no METHOD for `get` as we do not know what `app` is nor do we know what `get` is typewise.)

**Comment by fabsx00** [comment]
Ok, sure. Is there any reason though why we can't set the name field here or are you just saying, let's to that when you're back? It just seems very convenient to have on the long run.

**Comment by max-leuthaeuser** [comment]
Done in: https://github.com/joernio/joern/pull/1746

We want to revisit this in the future for sure (improve call linking) - this should be in a separate issue then.
