### ISSUE TITLE
Using Joern in Multi-Threading

### ISSUE THREAD

**Issue by windhl** [joernio/joern#1736]
Hi, all,
I want to use multi-threading to process large number of files in the same time, howver, I got thus message, how can I solve this problem, thanks for all.

java.lang.IllegalStateException: The file is locked: nio:/data1/linux-ast/6/cpg.bin [1.4.200/7]java.lang.IllegalStateException: The file is locked: nio:/data1/linux-ast/6/cpg.bin [1.4.200/7]
    at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
    at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
    at org.h2.mvstore.FileStore.open(FileStore.java:172)
    at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
    at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)

**Comment by mpollmeier** [comment]
This is the third place you're posting this exact question, please don't do that in the future. 

For reference, here's a copy of my answer on [discord](https://discord.com/channels/832209896089976854/832214243230744626/1017732275007406110):
Looks like you're trying to open the same cpg in two processes at the same time. The underlying storage (mvstore) prevents that with a lockfile, to avoid simultaneous writes from multiple processes. 
If you are performing read-only operations, you can copy the cpg.bin beforehand and open those independently.
