### ISSUE TITLE
CPG scanning output feature request

### ISSUE THREAD

**Issue by jasperosy** [joernio/joern#1743]
I am currently using ghidra2cpg and joern's run.scan to look at potential vulnerabilities in binaries. When running run.scan on a CPG created via ghidra2cpg, the output is rather useful with the Result line. 
![image](https://user-images.githubusercontent.com/36022363/189789157-d896571a-5ece-4f10-bcd8-7062fb394513.png)

However, when using the python cpgqls_client to query my joern server, only the last line with res is written to the stdout at the client side. It would make the run.scan feature more useful to include the result line with the potential vulnerability discovered.

**Comment by mpollmeier** [comment]
I can confirm your results - the output is printed to the stdout / stderr on the server, rather than being included in the results. Will discuss internally. 
Thanks for submitting!

**Comment by jasperosy** [comment]
> I can confirm your results - the output is printed to the stdout / stderr on the server, rather than being included in the results. Will discuss internally. Thanks for submitting!

Thanks for your prompt reply, looking forward to the inclusion of the results in run.scan

**Comment by mpollmeier** [comment]
done via https://github.com/joernio/joern/pull/1752
