### ISSUE TITLE
javasrc2cpg: member variable initialization missing

### ISSUE THREAD

**Issue by fabsx00** [joernio/joern#1757]
For the following code
```
class Foo {
    int x = 10;
    String a = "foo";
}
```
two `MEMBER` nodes are created, but the literals and initializations are nowhere to be found in the graph. I take it they should be present in the artificial constructor function?

**Comment by fabsx00** [comment]
Looking at the code in the OSS data flow tracker, the expected behavior is that there is a method called `<clinit>`, which contains the assignments `x = 10;` and `a = "foo"`.

**Comment by johannescoetzee** [comment]
The `<clinit>` method exists for java2cpg (and presumably for plume as well), so that may explain the data flow tracker code. javasrc2cpg also has a unit test for this that's been hiding in a `pendingUntilFixed` block, so this has probably been broken for quite a while now.
