### ISSUE TITLE
jssrc2cpg: member initialization missing

### ISSUE THREAD

**Issue by fabsx00** [joernio/joern#1758]
Similar to https://github.com/joernio/joern/issues/1757 (javasrc), jssrc2cpg also does not represent member initializations in the following code:

```
class Foo {
   x = "foo"
}
```

My suggestion would be to model it in the exact same way as it is done by the Java frontend. That way, the ossdataflowengine will pick this up correctly.

**Comment by max-leuthaeuser** [comment]
Oh it's in there: https://github.com/joernio/joern/blob/413bc9964913653bde7473037c071897b352ff19/joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/TsAstCreationPassTest.scala#L82 (example as enum, but for classes it's the same)
We put the assignment calls inside of a fake <sinit> method. Same for c2cpg.

**Comment by fabsx00** [comment]
Oh, weird: I used `joern-parse` on a directory containing only a single `foo.js` file and it ended up using `JAVASRC` as opposed to `JSSRC`. I now used `joern-parse --language jssrc`, and that leaves me with a CPG that's pretty much empty.

**Comment by max-leuthaeuser** [comment]
> Oh, weird: I used `joern-parse` on a directory containing only a single `foo.js` file and it ended up using `JAVASRC` as opposed to `JSSRC`. I now used `joern-parse --language jssrc`, and that leaves me with a CPG that's pretty much empty.

That's a different problem I guess. 
The initialization fix is here: https://github.com/joernio/joern/pull/1759
