### ISSUE TITLE
how to directly get cpg files in .json format instead of .svg ?

### ISSUE THREAD

**Issue by anushka192001** [joernio/joern#1793]
how to directly get cpg files in .json format instead of .svg ?

as we want cpg in .json format to train a graph neural network for our project.

**Comment by mpollmeier** [comment]
AFAIK so far we only offer dot, graphml and neo4jcsv: https://github.com/ShiftLeftSecurity/overflowdb/tree/master/formats/src/main/scala/overflowdb/formats
We're happy to include contributions for more formats. 

A workaround might be to convert the graphml (xml) to json...

Not sure why you mention svg, do we support that in some form?

**Comment by anushka192001** [comment]
@mpollmeier can i also not import the CPGs of my code files  into neo4j instance running on neo4j desktop and from there i can download the .json format files?

if yes then how can i do it using your joern library?

![image](https://user-images.githubusercontent.com/63954873/193593263-e315dc15-e703-4348-ad03-86ef695e99f5.png)




also ,
if not .json format then in what format i can get from your library which can be feed into a deep learning model to predict flaws in a code.

**Comment by mpollmeier** [comment]
have you tried https://docs.joern.io/exporting?

**Comment by anushka192001** [comment]
@mpollmeier ,yes i tried , here its giving me in these three formats
![image](https://user-images.githubusercontent.com/63954873/193815099-5644b474-78df-47b6-aab1-229f7979cce7.png)

 but i am not figuring out how to export cpgs to neo4j instance and then download .json from there.

**Comment by anushka192001** [comment]
@mpollmeier would you please elaborate what you said?

**Comment by fabsx00** [comment]
`joern-export` now supports exporting to json: https://github.com/joernio/joern/pull/1845
