### ISSUE TITLE
script in JOERN is not working properly .

### ISSUE THREAD

**Issue by anushka192001** [joernio/joern#1842]
when i am writing script in JOERN  library to parse the files and saving its CPG's in graphml format in the folder named as that of thiers  but getting error.?

what i must change here?
![image](https://user-images.githubusercontent.com/63954873/195593056-fdf1de3b-3799-42cc-9cf8-1097b4e5553d.png)

![image](https://user-images.githubusercontent.com/63954873/195694301-ba330d62-3a0c-46c8-af6f-93ed00e26f84.png)

**Comment by fabsx00** [comment]
You put a shell script inside a scala function, so, that can't work. You would have to execute that script directly on the shell, that is, put it in a file called `script.sh` and run that with `sh script.sc`. The `@main def exec() = {` and the last `}` would need to be removed.

**Comment by anushka192001** [comment]
@fabsx00  can you suggest me , which format is best for generating embeddings like graphson(json) or graphml(xml) ?

**Comment by tuxology** [comment]
@anushka192001 Please be mindful of Joern contributors' time. You have cross-posted this exact question on 15 other repositories

![image](https://user-images.githubusercontent.com/3373857/197390383-230e2569-4fbf-40bf-8510-35d61aa98879.png)

While this might be urgent to you in your own mind, actual OSS contributors here don't share the same urgency - they don't function like this or owe you anything - and are volunteering their time. There are humans on the other side of what you write. I cannot speak for individual projects you X-posted on, but I request you to read documentation and code of Joern - see how its developed and structured. If there is something missing, ask amicably on discord on public channels only to see if there is a feature which is not documented.  If you feel the feature is not existing, be willing to work through code and suggest early work, patches etc.
