### ISSUE TITLE
jssrc2cpg: dealing with `const foo = (x,y) => { ... }`

### ISSUE THREAD

**Issue by fabsx00** [joernio/joern#1870]
The following failing test case illustrates a problem with currently have when analyzing type script code:
https://github.com/joernio/joern/compare/master...fabs/flowconst#diff-afb5c19d03ad15d4ad7e4d95280e9b70f5e434466d8eb2f414ae4444fd35741bR600

For a function defined anonymously and assigned to a constant, we swallow the assignment to the constant and the name of the function remains unknown in the CPG, for example, for

```
const foo = (x,y) => { ... }
```

we end up with a `METHOD` node where the `NAME` and `FULL_NAME` fields simply tell us that this is an anonymous method. The assignment to `foo` is not visible in the CPG. I would propose that we either make the assignment visible, or we simply handle this as an alternative way of defining a named method. The latter is probably easier and would mean that this works without additional changes in the data flow engine.

**Comment by max-leuthaeuser** [comment]
There should be an assignment to a METHOD_REF linked to the corresponding METHOD node. Otherwise this is a serious bug. I'll have a look tomorrow.

**Comment by fabsx00** [comment]
Alright, let me take another look. I got back an empty `cpg.assignment.l` yesterday, but maybe I did something wrong.

**Comment by fabsx00** [comment]
You're right, there was a typo in the code I used to test this on the joern shell. So, that means, we do actually have the assignment, but the data flow engine isn't picking this up. I'm still wondering whether we shouldn't just interpret `const foo = $lambda` in a pass. I'll continue to investigate.
