### ISSUE TITLE
joern-export: allow exporting separate methods

### ISSUE THREAD

**Issue by fabsx00** [joernio/joern#1893]
Specifically (or at least for) the graphson output, it would be great if we could export graphs per method as we do with the dot exporter. It's clear that we end up discarding parts of the CPG that aren't inside methods, but that's fine. It would also be important here that we can match method names and graphson file in the output.

**Comment by mpollmeier** [comment]
initial version done via https://github.com/joernio/joern/pull/1902

**Comment by mpollmeier** [comment]
"initial" because we may modify it based on customer feedback. anyway, closing for now
