### ISSUE TITLE
joern-export does not generate pdg as expected

### ISSUE THREAD

**Issue by Runingtime** [joernio/joern#1913]
When parsing the following code(temp.c):
```
static int sclp_ctl_ioctl_sccb(void __user *user_area)
{
	struct sclp_ctl_sccb ctl_sccb;
	struct sccb_header *sccb;
	int rc;

	if (copy_from_user(&ctl_sccb, user_area, sizeof(ctl_sccb)))
		return -EFAULT;
	if (!sclp_ctl_cmdw_supported(ctl_sccb.cmdw))
		return -EOPNOTSUPP;
	sccb = (void *) get_zeroed_page(GFP_KERNEL | GFP_DMA);
	if (!sccb)
		return -ENOMEM;
	if (copy_from_user(sccb, u64_to_uptr(ctl_sccb.sccb), sizeof(*sccb))) {
		rc = -EFAULT;
		goto out_free;
	}
	if (sccb->length > PAGE_SIZE || sccb->length < 8)
		return -EINVAL;
	if (copy_from_user(sccb, u64_to_uptr(ctl_sccb.sccb), sccb->length)) {
		rc = -EFAULT;
		goto out_free;
	}
	rc = sclp_sync_request(ctl_sccb.cmdw, sccb);
	if (rc)
		goto out_free;
	if (copy_to_user(u64_to_uptr(ctl_sccb.sccb), sccb, sccb->length))
		rc = -EFAULT;
out_free:
	free_page((unsigned long) sccb);
	return rc;
}

```
using commands:
```
joern-parse temp.c
joern-export --repr pdg --out temp
```
there is no correct dot file in the folder, and only exists an empty one.
Is this a bug?

**Comment by mpollmeier** [comment]
I'm not a C expert, but what's that `__user` in the parameter list of your method declaration? It trips up our c frontend. If you remove it, it works. 

cc @max-leuthaeuser

**Comment by fabsx00** [comment]
It's a macro used in the linux kernel to denote data that is coming from userspace. If it trips up our frontend, then we need to find a way of fixing that as it is very common.

**Comment by max-leuthaeuser** [comment]
The macro needs to be available to Eclipse CDT (our underlying parser).
Two options:
1) Include it: `#include <linux/compiler_types.h>` (needs to be available on your system and run c2cpg with `--with-include-auto-discovery`)
2) Define it: `# define __user		__attribute__((noderef, address_space(__user)))`
(see: https://github.com/torvalds/linux/blob/master/include/linux/compiler_types.h)

As the parser actually works with these macros they need to be around.

**Comment by Runingtime** [comment]
I see, thank you.
