### ISSUE TITLE
jssrc2cpg: ANY Type Returned for Primitive Literal Parameter on a Field-Based Call

### ISSUE THREAD

**Issue by DavidBakerEffendi** [joernio/joern#1915]
In the following code:

```javascript
const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => {
  res.send('Hello World!')
})

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})
```

I've observed that:
* The `/` parameter on `.get` is being interpreted as an `ANY` literal when it's seemingly obvious what type it is. When asking for the label, code, and type full name, I get `(LITERAL,"/",ANY)`.
* The point above also happens when replacing the string literal with a number value.

A suggested fix is to parse the argument token to identify if it is either a boolean, number, or string literal.

**Comment by DavidBakerEffendi** [comment]
If this is seemingly easy to fix, point me to where this construct is created, and I'll happily implement this functionality + tests.

**Comment by DavidBakerEffendi** [comment]
Current workaround:
```scala
          case x: Literal if x.code.matches("[\"|'].+[\"|']") => Option("string")
          case x: Literal if x.code.matches("(\\d+(?:\\.\\d+)?)") => Option("number")
          case x: Literal if x.code.matches("false|true") => Option("boolean")
 ```

**Comment by max-leuthaeuser** [comment]
They were already available as `dynamicTypeHintFullName`.
This PR adds the types also as typeFullName for primitive types: https://github.com/joernio/joern/pull/1916

**Comment by DavidBakerEffendi** [comment]
Ah I see, got it, I should check there more often thanks!
