### ISSUE TITLE
Is it possible to release test artifacts for python, php, java and jimple?

### ISSUE THREAD

**Issue by Liyw979** [joernio/joern#1926]
I want to reuse the test fixtures in my project.
Can this be done be a PR? like adding this line in ```build.sbt```
`Test / packageBin / publishArtifact := true`

**Comment by ml86** [comment]
Which classes specifically are you interested in? I was already pondering the release of test artefacts, but maybe it is better to do some restructuring first.

**Comment by Liyw979** [comment]
classes like ```PySrc2CpgFixture```
<img width="701" alt="image" src="https://user-images.githubusercontent.com/16919236/199275994-23039f07-55ed-4721-8500-1cc559ba8601.png">
no test jar for ```python```
<img width="627" alt="image" src="https://user-images.githubusercontent.com/16919236/199276362-56cf4667-0295-4af0-8ca7-b3bac9a49e21.png">
test jar for ```c```

```
libraryDependencies ++= Seq(
  "io.joern" %% "pysrc2cpg" % joernVersion,
  "io.joern" %% "pysrc2cpg" % joernVersion % Test classifier "tests"
)
```

**Comment by Liyw979** [comment]
#1930

**Comment by ml86** [comment]
All test code is now released as separate test artifacts. For reference: https://github.com/joernio/joern/pull/1930
