### ISSUE TITLE
these cpg generated in graphml or graphson format do not have pdg relations(only AST and CFG ) . how to get PDG relations also in the cpg files generated?

### ISSUE THREAD

**Issue by anushka192001** [joernio/joern#1945]
https://drive.google.com/file/d/1ScclXzLMNFs5G3aDiA3R4l6inxWA9O3O/view?usp=share_link
(link to the graphml file generated)

https://drive.google.com/file/d/19kFG_7xbEkhEiyUvM56edqdMmn_wrcWO/view?usp=sharing
(link to the code file whose cpg this is)

**Comment by max-leuthaeuser** [comment]
Have you read that: https://docs.joern.io/exporting?
Especially: https://docs.joern.io/exporting#the-command-line-tool-joern-export

**Comment by anushka192001** [comment]
@max-leuthaeuser  i don't want pdg seperately , i want pdg also in cpg file.

**Comment by anushka192001** [comment]
@max-leuthaeuser follow please resolve this issue.

**Comment by itsacoderepo** [comment]
Closing because it seems outdated
