### ISSUE TITLE
querydb: Webpage Not Updated With Latest Queries

### ISSUE THREAD

**Issue by DavidBakerEffendi** [joernio/joern#1977]
I've noticed that [https://queries.joern.io](https://queries.joern.io) does not reflect the latest queries - is this perhaps reflecting the queries on the archived repository?

**Comment by claudiuvursache** [comment]
@DavidBakerEffendi it's not the archived queries that are being shown, it's just that the process of updating queries on the website is currently manual, see https://github.com/joernio/query-database-website/commit/30dec24829b5f7a7d5a0d7d2a7cf88778c2cd199

**Comment by DavidBakerEffendi** [comment]
@claudiuvursache Ah I see! Noted, thanks.
