### ISSUE TITLE
Need Help: some reaching def edge is missing since 1.1.1251

### ISSUE THREAD

**Issue by Liyw979** [joernio/joern#1982]
before
![image](https://user-images.githubusercontent.com/16919236/201859388-45fc3ce4-790a-49d1-9e11-3c6c2b2bc3ae.png)
after, 3 reachingdef egdes are now missing.
![image](https://user-images.githubusercontent.com/16919236/201859476-de658ba6-eca0-4adb-904d-2ffec1d9cd68.png)
Can't share the code sample.

**Comment by Liyw979** [comment]
In 1.1.1251, 2 semantics are added to ```split```.
https://github.com/joernio/joern/blob/e8d17cba2d8e4b9825e512572b08fa8aba038450/dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/DefaultSemantics.scala#L117-L118
In my source code, ```commands``` is excatly the arugment of ```split```. 
After deleting these 2 line, reaching def edges are back.

**Comment by Liyw979** [comment]
I try ```List((1, -1))``` and still can't get the flow.
This is weird. I think ```List((1, -1))``` should be good too.

**Comment by DavidBakerEffendi** [comment]
Hmm, since `split` is an instance method, maybe one should try also self taint the receiver. Try adding `(0,0)`

**Comment by Liyw979** [comment]
Both ```List((0,0), (0, -1))``` ,```List((0, -1))```  works for me, thanks for the help @DavidBakerEffendi

**Comment by DavidBakerEffendi** [comment]
Thanks for letting me know, @Liyw979! I'll make a PR to fix those
