### ISSUE TITLE
Why doest jssrc2cpg create TYPE_DECL nodes for every function decoration?

### ISSUE THREAD

**Issue by Liyw979** [joernio/joern#2003]
```
    val cpg: Cpg = code("""
        | var s = { 'field' : 0 }
        |
        | function foo(arg) {
        |   arg.field = source();
        |   sink(arg.field);
        | }
        |""".stripMargin)
```
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/16919236/202906825-ce8f6310-468c-4bd1-8cc2-f64284deeaea.png">

**Comment by ml86** [comment]
@Liyw979 This TYPE_DECL is required for the METHOD_REF to `foo`. The METHOD_REF not just requires a method full name but also a type full name which at the moment is a detail just required for the closed source data flow tracker.

**Comment by Liyw979** [comment]
The ```type full name``` of ```foo``` looks confusing.
<img width="331" alt="image" src="https://user-images.githubusercontent.com/16919236/203073010-c63c1602-3789-45e3-8eb8-d25cf9e13318.png">
<img width="927" alt="image" src="https://user-images.githubusercontent.com/16919236/203072735-4470c8ee-c3d2-4ef9-9d41-8d84838b093c.png">
Since this is required by the closed tracker, I will skip this. Thanks for you reply!

**Comment by Liyw979** [comment]
You can see from the screen shot that type of ```foo`` is ```funciton```.
