### ISSUE TITLE
Add support for C#

### ISSUE THREAD

**Issue by port513** [joernio/joern#2004]
Used to use CodeQL but I do like Joern better but I do miss support for C#
Would make my day easier if I could use only one platform...

**Comment by DavidBakerEffendi** [comment]
We currently have `jimple2cpg` and it appears there exists some kind of [.NET extension for Soot using JNI](https://github.com/schtho/soot-dotnet).  A good starting point for anyone who would like to tackle this.

**Comment by prabhu** [comment]
@port513, we have support for C# in the commercial offering. Are you interested in a demo? You can email me at prabhu @ qwiet.ai
