### ISSUE TITLE
The link between two JAR packages is disconnected. The source code is not broken. Same source and sink points

### ISSUE THREAD

**Issue by 75ACOL** [joernio/joern#2016]

**Comment by ml86** [comment]
Unclear what this ticked is supposed to mean. Please reopen if you have a proper issue/problem description.

**Comment by 75ACOL** [comment]
Thanks for answer. I mean, the data flow link between the two jars is broken. If I can find the source code, it broke when I compiled the project into two packages. Is it because SOOT does not support link search between two JAR packages
