### ISSUE TITLE
Duplicate Method Stubs: <operator.alloc> 

### ISSUE THREAD

**Issue by DavidBakerEffendi** [joernio/joern#2017]
When referring to the [`opencrx`](https://github.com/opencrx/opencrx) repository, there is some odd behaviour when considering the `<operator>.alloc` method/calls.

```scala
joern> cpg.method("<operator>.*").groupBy(_.name).map { case (k, v) => k -> v.size}.foreach(println) 
(<operator>.shiftLeft,1)
(<operator>.greaterEqualsThan,1)
(<operator>.fieldAccess,1)
(<operator>.xor,1)
(<operator>.cast,1)
(<operator>.division,1)
(<operator>.lessEqualsThan,1)
(<operator>.logicalOr,1)
(<operator>.logicalShiftRight,1)
(<operator>.subtraction,1)
(<operator>.conditional,1)
(<operator>.plus,1)
(<operator>.equals,1)
(<operator>.postDecrement,1)
(<operator>.assignmentPlus,1)
(<operator>.logicalAnd,1)
(<operator>.or,1)
(<operator>.preIncrement,1)
(<operator>.lessThan,1)
(<operator>.throw,1)
(<operator>.minus,1)
(<operator>.greaterThan,1)
(<operator>.assignmentMultiplication,1)
(<operator>.notEquals,1)
(<operator>.multiplication,1)
(<operator>.assignment,1)
(<operator>.arithmeticShiftRight,1)
(<operator>.alloc,663)
(<operator>.modulo,1)
(<operator>.instanceOf,1)
(<operator>.postIncrement,1)
(<operator>.not,1)
(<operator>.arrayInitializer,1)
(<operator>.logicalNot,1)
(<operator>.and,1)
(<operator>.addition,1)
(<operator>.assignmentMinus,1)
(<operator>.indexAccess,1)
```

In short, there are `663` method nodes for `<operator>.alloc`. When looking at each time `<operator>.alloc` is called, it links to all 663 methods, e.g.,

```scala
joern> cpg.call("<operator>.alloc").head.callee(NoResolve).size 
res3: Int = 663
```

This means bad things for the data-flow tracker, although minor returns from the call stack, it is 663 calls/tasks to generate each time. While this issue was found on `javasrc2cpg`, it may be linked to the `MethodStubPass`.

This appears mainly since these `Call(<operator.alloc>)` call signatures are unique, and the `MethodStubPass` groups calls by name, method full name, and signature. Other `<operator>.*` calls have empty signatures.

Removing [the line that sets alloc signatures](https://github.com/joernio/joern/blob/7f59bfa290f2a15256f14f6c5bb89a51e248b80e/joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala#L2408) fixes this anomaly. I would first like to confirm if this is unintended or what we can do to reduce all of these excess stubs/call edges.

**Comment by ml86** [comment]
Having different signatures for the `<operator>.alloc` calls does not make sense. An empty signature is fine.

**Comment by DavidBakerEffendi** [comment]
Seems that simply removing this line causes issues elsewhere, I assume it's used for type inference information. @johannescoetzee do you have time to investigate, otherwise I can dive into this and see if I can maintain all passing tests while removing signature info from this. Perhaps linking a type ref from the `alloc` site or something.

**Comment by johannescoetzee** [comment]
@DavidBakerEffendi I'll have a look.
