### ISSUE TITLE
joern Python

### ISSUE THREAD

**Issue by billquan** [joernio/joern#2025]
Somehow it seems I can't get joern work for python source code. It only generates empty graphs even if I use the test case from https://github.com/joernio/joern/blob/master/tests/code/pythonsrc/simple.py

I'm using the joern interactive mode. What is wrong?
![image](https://user-images.githubusercontent.com/65994455/204072255-beeb14c6-eed4-4641-8cc1-2eee122cbea7.png)

Thank you!

**Comment by Liyw979** [comment]
Did you put you code in a folder and import that folder?

**Comment by itsacoderepo** [comment]
Hello @billquan,

it works doing it this way: 
![image](https://user-images.githubusercontent.com/5180740/204152802-3061d28b-7226-4e50-95ef-af644372bc1e.png)
