### ISSUE TITLE
jssrc: wrong argument indizes in push calls within desugared array literals

### ISSUE THREAD

**Issue by maltek** [joernio/joern#2049]
```
joern> workspace.reset ; importCode.jssrc.fromString("""[0]""")
...
joern> cpg.literal.size
val res1: Int = 1
joern> cpg.literal.head.argumentIndex
val res4: Int = 2
joern> cpg.literal.expressionUp.code.head
val res5: String = "_tmp_0.push(0)"
joern> cpg.literal.inCall.argument.isIdentifier.argumentIndex.head
val res15: Int = 1
```

**Comment by max-leuthaeuser** [comment]
It's 2 because its the second argument to the `_tmp_0.push(0)` call (_tmp_0.push as receiver being the first)?

**Comment by maltek** [comment]
Compare against `importCode.jssrc.fromString("""_tmp_0.push(0)""")` - there the argument indices are 0/1 for `_tmp_0/0`. There, the receiver has -1 - but its `argumentIndex` doesn't really matter because it doesn't have an argument edge and so nothing is trying to match it to a parameter with the same index.

**Comment by max-leuthaeuser** [comment]
I see. Let me fix this.
