### ISSUE TITLE
jssrc: weird TypeRefs generated for classes cause problems due to position in AST

### ISSUE THREAD

**Issue by maltek** [joernio/joern#2055]
```
importCode.jssrc.fromString("""class A {}""")
joern> cpg.typeRef.l 
res10: List[TypeRef] = List(
  TypeRef(
...
    typeFullName -> "tmp.js::program:A"
...
  )
)
joern> cpg.typeRef.astParent.l 
res15: List[AstNode] = List(
  Method(
...
    fullName -> "tmp.js::program",
...
  )
)
joern> cpg.typeRef.expressionUp.l 
res9: List[Expression] = List()
```

For classes, we generate this `TypeRef` as an AST child of the containing method. I don't really understand the point of that - my feeling is that it doesn't do anything and we could just remove it?

If I'm wrong about that, we should put it somewhere below a `CfgNode` in the AST, so that we don't crash in this line:

https://github.com/ShiftLeftSecurity/codescience/blob/a0491a461316f78f8f129d22f15fbd9e8044dfb2/semanticcpg-ext/src/main/scala/io/shiftleft/semanticcpgext/language/nodemethods/TrackingPointMethodsImpl.scala#L150

**Comment by max-leuthaeuser** [comment]
No, it's nonsense I guess and we should remove it.
