### ISSUE TITLE
[doc] ControlStructure does not take parameters

### ISSUE THREAD

**Issue by extf33** [joernio/joern#2072]
In the [doc](https://docs.joern.io/c-syntaxtree#control-structures), it says,
![image](https://user-images.githubusercontent.com/119841155/206344118-d9e5a2fd-75b3-4a64-a67c-5b0635a63104.png)

```
joern> cpg.method.filter(_.controlStructure(".*MAX.*").isEmpty).l 
cmd10.sc:1: overflowdb.traversal.Traversal[io.shiftleft.codepropertygraph.generated.nodes.ControlStructure] does not take parameters
val res10 = cpg.method.filter(_.controlStructure(".*MAX.*").isEmpty).l
                                                ^
Compilation Failed
```

**Comment by mpollmeier** [comment]
Thanks for reporting! The documentation should rather be `.controlStructure.code(".*MAX.*")`
Pro tip: instead of `.filter(_.xyz.isEmpty)` you can use `.whereNot(_.xyz)`:

```scala
cpg.method.whereNot(_.controlStructure(".*MAX.*"))
          .where(_.callee.name(".*source.*")).l
```

I'll update the docs.
