### ISSUE TITLE
Joern doesn't recognize `__int64`?

### ISSUE THREAD

**Issue by extf33** [joernio/joern#2077]
Joern doesn't recognize `__int64`?

```scala
joern> importCode.cpp.fromString( """
       __int64 foo(unsigned __int64 *a1, __int64 a2) {
         return 1;
       }
       
       __int64 bar(__int64 *a1, __int64 a2) {
         return 2;
       }
       
       __int64 baz(unsigned int *a1, int a2) {
         return 3;
       }
       
       void main() {
         foo(0, 0);
         bar(0, 0);
         baz(0, 0);
       }
       """) 
[...]
res26: Cpg = Cpg (Graph [61 nodes])

joern> cpg.method("foo").code.l
res27: List[String] = List("<empty>")  ------------------------------>  ?

joern> cpg.method("bar").code.l 
res28: List[String] = List("__int64 bar (__int64 *a1,__int64 a2)")

joern> cpg.method("baz").code.l  
res29: List[String] = List("__int64 baz (unsigned int *a1,int a2)")
```

If I add `#define __int64 long long`,

```scala
joern> importCode.cpp.fromString( """
       #define __int64 long long
       
       __int64 foo(unsigned __int64 *a1, __int64 a2) {
         return 1;
       }
       
       __int64 bar(__int64 *a1, __int64 a2) {
         return 2;
       }
       
       __int64 baz(unsigned int *a1, int a2) {
         return 3;
       }
       
       void main() {
         foo(0, 0);
         bar(0, 0);
         baz(0, 0);
       }
       """) 
[...]
res36: Cpg = Cpg (Graph [67 nodes])

joern> cpg.method.code.l  
res37: List[String] = List(
  "<global>",
  "long long foo (unsigned __int64 *a1,__int64 a2)",
  "long long bar (__int64 *a1,__int64 a2)",
  "long long baz (unsigned int *a1,int a2)",
  "void main ()"
)

joern> cpg.method.name.l  
res38: List[String] = List("<global>", "foo", "bar", "baz", "main")
```

**Comment by max-leuthaeuser** [comment]
c2cpg re-uses Eclipse CDT as parser and macro preprocessor.
For performance reasons we disabled system header file scanning (and thus, macro expansion).
You may want to enable it with running c2cpg standalone with the `--with-include-auto-discovery` flag
and #include the corresponding header file.

**Comment by Runingtime** [comment]
> c2cpg re-uses Eclipse CDT as parser and macro preprocessor. For performance reasons we disabled system header file scanning (and thus, macro expansion). You may want to enable it with running c2cpg with the `--with-include-auto-discovery` flag and #include the corresponding header file.

Could you please explain more about how to use the  `--with-include-auto-discovery` flag? I didn't find the related documentation. I've tried `joern-parse code.c --with-include-auto-discovery` but failed.

**Comment by max-leuthaeuser** [comment]
That flag is for c2cpg only. You may invoke c2cpg directly or pass down the arg to joern-parse like this: `joern-parse code.c --frontend-args --with-include-auto-discovery`.
