### ISSUE TITLE
jssrc: invalid desugaring for spread syntax in object literals

### ISSUE THREAD

**Issue by maltek** [joernio/joern#2086]
example of actual behavior from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#spread_in_object_literals

```javascript
const array = [1, 2, 3];
const obj = { ...array }; // { 0: 1, 1: 2, 2: 3 }
```

i.e. it does a shallow copy of `array` into the resulting object. The only real way to model that in the CPG is as a call to an operator (or possibly `Object.assign` which has the same semantics, but I'd prefer something like `<operator>.shallowCopy` or `<operator>.spreadObject`).

------

Currently, we try to do weird things based on the name of the variable that's being spread:

```
joern> importCode.jssrc.fromString("""({...bar})""") 
res80: Cpg = Cpg (Graph [55 nodes])

joern> cpg.call.code.p 
res81: List[String] = List("_tmp_0.bar = bar", "_tmp_0.bar")
```

and even more wrong:

```
joern> importCode.jssrc.fromString("""({...foo.bar})""") 
res78: Cpg = Cpg (Graph [58 nodes])

joern> cpg.call.code.p 
res79: List[String] = List("_tmp_0._tmp_1 = foo.bar", "_tmp_0._tmp_1", "foo.bar")
```

**Comment by max-leuthaeuser** [comment]
This is not an easy one. 
Currently, we desugar ObjectExpressions like this in a general case:
```javascript
const x = {
  a,
  b,
  ...rest
}
// => desugaring:
const x = {
  var tmp;
  tmp.a = a;
  tmp.b = b;
  tmp.rest = rest;
  tmp;
}
```
which is wrong for `...rest` as you described. We simply handle it here as it would be a normal identifier. You suggest to add a specific call `<operator>.spreadObject`?
```javascript
const x = {
  var tmp;
  tmp.a = a;
  tmp.b = b;
  tmp.rest = CALL(name=<operator>.spreadObject) with arg 1: IDENTIFIER(name=rest);
  tmp;
}
```
?

**Comment by maltek** [comment]
Ah, yes I didn't think about how these expressions can be combined this with a regular object literal. This complicates things... Apparently you can have an arbitrary number of spreads and explicit properties and in case of conflicts the last value wins, i.e.

```javascript

const rest1 = {
  "a": "rest1",
  "b": "rest1",
  "c": "rest1",
};

const rest2 = {
  method() {
    return { "b": "rest2" }
  }
}

const x = {
  "a": "x",
  "b": "x",
  ...rest1, // overwrite a, b, sets new c
  c: "x", // overwrite c from rest1
  ...rest2.method() // overwrite b
}
// x -> { a: 'rest1', b: 'rest2', c: 'x' }
```

For that, I think something like this should work:
```
const x = {
  var tmp;
  tmp.a = a;
  tmp.b = b;
  CALL(name=<operator>.spreadObject)
    arg 1: tmp
    arg 2: EXPRESSION(rest.first())
  tmp.c = c;
  CALL(name=<operator>.spreadObject)
    arg 1: tmp
    arg 2: EXPRESSION(rest.second())
  tmp;
}
```

Difference to your example is

  1. it's not `tmp.rest = ...` because the spreading affects all of `tmp` and not just its `rest` property 
  2. the thing that's being spread can be an arbitrary expression and not just an identifier

**Comment by ml86** [comment]
Using an extra operator is also what the python frontend does for the `*`. Compare: https://github.com/joernio/joern/blob/5e41a1487af8cf6ea816f2d358523166d6792e8a/joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitorHelpers.scala#L432
