### ISSUE TITLE
jssrc: code fields are wrong after a multi-byte character was encountered in the source code

### ISSUE THREAD

**Issue by maltek** [joernio/joern#2087]
```
joern> importCode.jssrc.fromString("""// 😼
       logger.error()
       """) 
res91: Cpg = Cpg (Graph [46 nodes])

joern> cpg.fieldAccess.argument(2).code.l 
res92: List[String] = List(".erro")
```

**Comment by max-leuthaeuser** [comment]
This might be a problem with joern writing a temporary file.
jssrc2cpg is reusing https://github.com/ShiftLeftSecurity/codepropertygraph/blob/master/codepropertygraph/src/main/scala/io/shiftleft/utils/IOUtils.scala which handles utf8 just fine.
