### ISSUE TITLE
[ERROR] Caused by java.lang.ClassNotFoundException: com.sun.activation.registries.MimeTypeFile

### ISSUE THREAD

**Issue by Liyw979** [joernio/joern#2115]
- frontend: ```Javasrc2cpg```
- project: ``` ff4j```

reference：https://security.snyk.io/vuln/SNYK-JAVA-ORGFF4J-3152484

**Comment by Liyw979** [comment]
https://github.com/joernio/joern/issues/2115

**Comment by johannescoetzee** [comment]
I wasn't able to reproduce the error. Could you please check whether this is still an issue and provide some steps to reproduce if so?

**Comment by Liyw979** [comment]
@johannescoetzee Thanks for your reply, this is nolonger a issue!
