### ISSUE TITLE
Circular hierarchies for java.lang.Object

### ISSUE THREAD

**Issue by Liyw979** [joernio/joern#2126]
I am using ```javasrc2cpg``` to scan ```jdk8```, and get ```StackOverflowError``` in 
https://github.com/joernio/joern/blob/f258451c080c674da0a146d0b8fa171e0dd280b7/joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/callgraph/DynamicCallLinker.scala#L84-L96

Then I find out that the ```inheritsFromTypeNames``` of ```java.lang.Object``` contains itself

![image](https://user-images.githubusercontent.com/16919236/209047457-8995e389-c8b3-4a9c-aa8b-e31c41d0c33c.png)

**Comment by DavidBakerEffendi** [comment]
#3197 Will fix the circular hierarchy issue

**Comment by Liyw979** [comment]
I have test this. ```StackOverflowError ``` is gone. Thanks @DavidBakerEffendi
