### ISSUE TITLE
Is this a bug or improper usage?

### ISSUE THREAD

**Issue by ycclnn** [joernio/joern#2158]
What I am doing here is to find calls that can reach the sink. According to my understanding, I believe the two query in the screenshot below are the same. But the result differs. 
Is this a bug? 
Thanks.
![image](https://user-images.githubusercontent.com/56081290/210750857-c4b69110-f2e4-4705-84ba-42b46417712d.png)

**Comment by 75ACOL** [comment]
I can tell you that this result is normal, because joern uses preemptive multithreading to query the results and optimizes them, so the results may not be the same every time

**Comment by itsacoderepo** [comment]
The queries are not the same. 

In the first query you are starting from `sink1`, searching flows to all calls and filtering the `results` (=return value of "reachableBy"), while the second query is starting from the same source but the sink are calls with the name "source1".
