### ISSUE TITLE
Wrong with signature of method

### ISSUE THREAD

**Issue by INT2ECALL** [joernio/joern#2165]
When I analyzed the [webgoat ](https://github.com/WebGoat/WebGoat/archive/refs/tags/v2023.3.zip)project, I found that there was a problem with the method signature.

Some method signatures do not have package and class names：
![image](https://user-images.githubusercontent.com/91420400/210918575-49420e97-c968-4865-9832-e16ae3e934a5.png)

**Comment by Liyw979** [comment]
```org.owasp...ResultBuilder``` is the ```returnType``` of method ```fail``` like ```void``` above

**Comment by johannescoetzee** [comment]
The signatures should only contain `<returnType>(<parameterTypes>)`, so the ones given here are correct. `methodFullName` is the field which includes the package and class names as well, specifically `<packageName>.<className>.<methodName>:<signature>`.
