### ISSUE TITLE
jssrc2cpg: Invalid IMPORTS Edge on IMPORT Node

### ISSUE THREAD

**Issue by DavidBakerEffendi** [joernio/joern#2168]
Given the test code:

```scala
  "foo" in {
    val cpg: Cpg = code(
      """
        |const mongoose = require('mongoose');
        |mongoose.model('abc', { title: { type: String }});
        |""".stripMargin)
  }
  ```
  I get the exception `Edge with type='IMPORTS' with direction='OUT' not supported by nodeType='IMPORT'`. Changing the `require('mongoose')` to `null` results in a passing CPG creation.
  
  Joern version: 1.1.1378

**Comment by max-leuthaeuser** [comment]
Looks like this came in with https://github.com/joernio/joern/pull/1861

**Comment by fabsx00** [comment]
I can't reproduce this on joern master, looks like a setup issue.

**Comment by fabsx00** [comment]
Closing for now.

**Comment by DavidBakerEffendi** [comment]
Confirmed this is a setup issue, with older versions of CPG/OverflowDB running behind a newer Joern
