### ISSUE TITLE
PassesNot doesn't work as expected

### ISSUE THREAD

**Issue by ycclnn** [joernio/joern#2175]
Hi, I was trying to analyze the following one line python code.
`cur111.execute(BeautifulSoup(cp.request.params["keyname"]))`

I define the source as the call with code that contains "cp.request.params"; sink as "execute" and sanitizer as "BeautifulSoup"
After I run the joern sql to check the results for them all.  The result for all three is:

List(
    148L,
    "cur3.execute(BeautifulSoup(input()))",
    List("./snippets/py-test/c1.py"),
    Some(value = 33)
  ),

When I run: sink.reachableBy(source), the result includes the 148L as expected. So far so good. 

But when I run: sink.reachableBy(source).passesNot(sanitizer), the result has the 148L as well. I think this is quite confusing. Since source, sink, and sanitizer all contain 148L. Why does the result tell the opposite that it does not flow through 148L. 

Is this a bug?

**Comment by prabhu** [comment]
@yzn12345 Could you share the def statements for source, sink, and sanitizer?
