### ISSUE TITLE
Improve astgen dependency management

### ISSUE THREAD

**Issue by iandinwoodie** [joernio/joern#2205]
**Is your feature request related to a problem? Please describe.**

In my attempts to create a Homebrew formula to address https://github.com/joernio/joern/issues/1107 I've encountered the following behaviors:

1. The build system does not search the path for an `astgen` executable. Instead, it checks for the binaries only in the `jeorn-cli/frontends/jssrc2cpg/bin/astgen` directory.
    * This requires me to create a symlink from the `astgen` dependency found in the path to the `jeorn-cli/frontends/jssrc2cpg/bin/astgen` directory.
2. The build system downloads `astgen` binaries for all platforms, regardless of the user's platform, except for when a satisfactory file is found in the `jeorn-cli/frontends/jssrc2cpg/bin/astgen` directory.
    * This requires me to create placeholder files in `jeorn-cli/frontends/jssrc2cpg/bin/astgen` to prevent unnecessary downloads.
    * E.g., on macOS ARM I need to create `astgen-linux`, `astgen-macos`, and `astgen-win.exe` placeholder files.
3. The build system makes copies of all the files in the `jeorn-cli/frontends/jssrc2cpg/bin/astgen` directory.
    * This copies the symlinked `astgen` binary into the build directory (Note: it copies the actual binary, not the symlink).
        * For Homebrew purposes, this secret decouples `jeorn` from its `astgen` dependency formula.
        * Therefore, commands like `brew info jeorn` won't accurately represent the underlying state.
            * E.g., `brew uninstall --force astgen` would seemingly break `jeorn` according to Homebrew, but `jeorn` would continue operating fine because it is relying on it's own local copy of `astgen`.

**Describe the solution you'd like**

* To address point 1, the build system could be updated to first consider an `astgen` binary found in the path.
    * If there are concerns about the build system proceeding with an outdated version of `astgen`, then the build system could be updated to error if the output of `astgen --version` indicates a version older than the build system requires.
* To address point 2, the build system could be updated to only require `astgen` binaries relevant to the user's machine.
   * It's possible the current behavior exists so a single build results in a distributable that is platform-agnostic.
       * If this is the case, then perhaps the build system could be updated to accept an argument or environment variable to specify a platform-specific build when necessary.
* To address point 3, the build system could be updated to not copy `astgen` binaries to the build directory when the build is using an `astgen` binary found in the path.

**Describe alternatives you've considered**

I can attempt to circumvent these behaviors with additional logic in the Homebrew formula (e.g., managing placeholder files, creating symlinks, deleting copies of copied binaries and replacing them with symlinks). However, it is very possible that Homebrew maintainers will refuse to approve a formula with so many additional steps.

**Additional context**

Not applicable.

**Comment by mpollmeier** [comment]
@max-leuthaeuser and I will discuss this - once my body get's rid of this covid thing

**Comment by max-leuthaeuser** [comment]
@iandinwoodimi please check if https://github.com/joernio/joern/pull/2216 is sufficient for your needs.

**Comment by iandinwoodie** [comment]
@mpollmeier wishing you a peaceful recovery!

**Comment by iandinwoodie** [comment]
@max-leuthaeuser that proposed solution looks great! I just added a comment about a possible change to the version matching logic in the PR.

**Comment by iandinwoodie** [comment]
Fixed in #2216
