### ISSUE TITLE
[Bug] Joern silently crasing with no crash logs

### ISSUE THREAD

**Issue by tuxology** [joernio/joern#2206]
**Describe the bug**
Latest version of `joern` when installed from the install script is not booting up. There are multiple SLF4J logs on console but no detailed log of crash. Using Joern as a library post v1.1.359 also shows the same behavior when silent crashes and no logs are observed. Rebuilding from scratch using `sbt` and then testing does not show the same error however. Tested on `v1.1.403`

**To Reproduce**
Install and start joern using `sudo ./joern-install.sh --reinstall --interactive` and then start joern

```
$ joern
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/opt/joern/joern-cli/lib/org.apache.logging.log4j.log4j-slf4j-impl-2.19.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
Compiling /home/suchakra/(console)
```
End of log :point_up_2: 

**Expected behavior**
Joern starts normally and when integrated as a library, is able to print all logs. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Elementary OS v5.1
 - Joern Version : v1.1.403
 - Java version: 

```
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu218.04, mixed mode, sharing)
```

**Comment by mpollmeier** [comment]
@tuxology does this also happen if you install without `sudo`?
I currently have covid, so I'm a bit limited atm, in many ways.

**Comment by max-leuthaeuser** [comment]
Just tested it on my machine.
It worked without any problems (with and without `sudo`).

```
openjdk 11.0.18 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10)
OpenJDK 64-Bit Server VM (build 11.0.18+10, mixed mode)
```

**Comment by fabsx00** [comment]
Worked with @tuxology to resolve this - turns out he was using joern as a lib and log4j-simple wasn't on the classpath.
