### ISSUE TITLE
How to associate method in call statement with a method node in neo4j?

### ISSUE THREAD

**Issue by wcy1997** [joernio/joern#2230]
I have exported cpg.bin as csv and import it into neo4j.
Now, I want to know which functions have been called, so I traverse all the method nodes, hoping that a call node points to it, but I can't find it (I'm sure the function "str_to_token" has been called)
![image](https://user-images.githubusercontent.com/22297131/216019124-a82e794b-c824-4806-8f97-af5e72063495.png)

This means that there is no correlation between the calling function in the call statement and the actual function definition.
However, Joern's query syntax provides the caller function, which seems to be able to query the function signature from the call statement.

So, I wonder if this is because joern-export lost this part of the association information during the process of exporting to csv, and what I should do to associate the call statement with the actual function signature

**Comment by wcy1997** [comment]
In short, I want to know how to associate a METHOD node called "str_to_token" and a CALL node called "str_to_token".
Thanks~~~

**Comment by wcy1997** [comment]
I take the liberty to ask whether the source code is available for analyzing the call statement, and if so, which source code file this part is in.

**Comment by mpollmeier** [comment]
Actually it's simpler than I initially thought. Take e.g. https://github.com/joernio/joern/blob/master/joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/CallTests.scala

If you add a simple test like this:
```scala
    "foo" in {
      cpg.method("add").caller.name.foreach(println)
    }
```

and step through with the debugger, you'll see that it goes through https://github.com/joernio/joern/blob/master/semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/ICallResolver.scala#L36, and I thought there's quite some magic in there. However, that's only true for our closed source engine. The open source joern engine simply follows the incoming `CALL` edges. Those should be there, also in the neo4j export. I.e. for a given `METHOD` node, follow the _incoming_ `CALL` edge, and you should be on a `CALL` node.

**Comment by wcy1997** [comment]
Take e.g.
`
int getClientIDByToken(std:: string& stoken)
{
  SecurityToken token;
  str_to_token(stoken, token);
  return getClientIDByToken(token);
`
In theory, I should be able to start with a METHOD node called str_to_token, find a CALL node, which is in the getClientIDByToken function definition. However, I did not find such a call node in neo4j.
![image](https://user-images.githubusercontent.com/22297131/216265743-1eaa9bd1-8984-4cfa-aa49-b665dc90b58b.png)
In this screenshot, the METHOD node called str_to_token does not have a CALL node pointing to it.(Note that the color of the call node on the left is pink.)
So, I guess Joern does not export the relationship between the function and the call statement, or Joern did not generate this information when parsing my code.....

**Comment by mpollmeier** [comment]
not sure what's different in your snippet, but here's an example that's simple enough and that works. maybe you can go from there:

```scala
val code = """
  int add(int x, int y) {
    return x + y;
  }
  int main(int argc, char **argv) {
    printf("%d\n", add((1+2), 3));
  }
"""
importCode.c.fromString(code)
cpg.method.name.l
cpg.method("add").caller.name.l
// main

val addMethod = cpg.method("add").next
val call = addMethod.in("CALL").next
val mainMethod = call.in("CONTAINS").next
```

![grafik](https://user-images.githubusercontent.com/506752/216300117-7e220f48-8217-4de2-a30e-fc4fbb266f14.png)

**Comment by wcy1997** [comment]
Thanks~

**Comment by itsacoderepo** [comment]
Closing because it seems to be solved
