### ISSUE TITLE
[Bug] Error running 'AmmoniteBridge': Illegal char <:> at index 4

### ISSUE THREAD

**Issue by yzn12345** [joernio/joern#2267]
**Describe the bug**
Couldn't run ammonite repl as well as provided tests.

**To Reproduce**
1. Import joern as bsp in IDEA
2. Build the project
3. Go to 'joern-cli/src/main/scala/io/joern/joerncli/console/AmmoniteBridge.scala'
4. See the run button, click it
5. Receive error

**Expected behavior**
should start the ammonite repl

**Screenshots**
![image](https://user-images.githubusercontent.com/56081290/218630414-9cdd18c8-d696-47fb-9ada-237ed2575396.png)

**Desktop (please complete the following information):**
 - win11
 - Joern Version: v1.1.1447
 - jdk17

**Comment by max-leuthaeuser** [comment]
Just tested that on my machine and it worked without issues.
- Windows 11
- Joern Version: v1.1.1447
- but different JDK: 11.0.12

Could you try this too? I doubt its related to the JDK version, but I want to be sure.

**Comment by yzn12345** [comment]
Still the same error. I believe its an IDE issue so I'll close this. Thanks anyway
