### ISSUE TITLE
How to write joern script in Intellij IDEA with code completion?

### ISSUE THREAD

**Issue by Icyrockton** [joernio/joern#2281]
I want to write my own joern script with complex logic.
I notice Intellij IDEA can not resolve symbol , code completion can't work.
Is there anything i need to configure?
![image](https://user-images.githubusercontent.com/42564541/219940182-d8ff603b-eff3-4104-a0f5-3d67f3ff92ee.png)

**Comment by mpollmeier** [comment]
That would indeed be nice, albeit I'm not sure about the best way to make that work at the moment. The trick is probably to configure the classpath correctly. I'll give this a try in the next days as well, let me know if you find something in the meantime.

fwiw a workaround is to write the code in the regular joern subprojects in a .scala file and then copy it over. Not ideal, but better than red squiggles all over the place...
