### ISSUE TITLE
Supports for Android application?

### ISSUE THREAD

**Issue by evilpan** [joernio/joern#2285]
It seems that Joern supports Dalvik bytecode via Soot Jimple IR, But how can I import Android `.apk` with joern? Or is there any scripts that can be used to conver apk to `cpg` database?

**Comment by itsacoderepo** [comment]
Hello @evilpan , 

for now i would recommend you to use dex2jar (`https://github.com/pxb1988/dex2jar`) and convert the apk to a jar. 

The screenshot below shows how i used dex2jar on an apk and successfully imported it into joern.

Converting:
```
./d2j-dex2jar.sh Google_Authenticator.apk 
```
Importing:
```
importCode("Google_Authenticator-dex2jar.jar")
```

![image](https://user-images.githubusercontent.com/5180740/220291302-1170ac92-1a92-42ae-a65e-bb71cb32fef5.png)


Wrapping everything into a script should be as easy as (assuming that you have joern and dex2jar installed):
```
#!/bin/bash

d2j-dex2jar $1 -o $1.jar
joern-parse $1.jar -o $1.bin.zip
```

![image](https://user-images.githubusercontent.com/5180740/220296268-7e25d19e-a7ec-4e9a-8b81-c1d689805471.png)

**Comment by evilpan** [comment]
Thanks Niko, I'll check about that!
