### ISSUE TITLE
Timeout exit mechanism for query

### ISSUE THREAD

**Issue by wcy1997** [joernio/joern#2294]
I found that when executing some queries (including repeat or reachableByFlaws), joern would not send a response for a long time and the computer would be down. I think the possible reason is that there is recursion in the source code, which causes Joern to fall into a dead loop when searching.

I hope to provide a timeout exit mechanism to ensure that my computer will not be down.
Thanks~~

**Comment by yzn12345** [comment]
I've read the source code of reachableBy and the program will exit the loop without stucking. The reason might be your query not the joern.
