### ISSUE TITLE
[ERROR COMPILING] Unknown error checking OSGI environment.

### ISSUE THREAD

**Issue by rouamar** [joernio/joern#2311]
When installing and testing joern on a cpp source file, fail to create cpg.bin.
![error](https://user-images.githubusercontent.com/32984553/221412456-4aae2847-bbc1-4440-be11-3b9e2e5090bd.png)

**Comment by mpollmeier** [comment]
does this also happen if you change the `output` to a local directory, i.e. not in `/mnt`?

**Comment by rouamar** [comment]
I changed my environment (move from Windows to Ubuntu), and change output directory, it works ! Thanks you for your concern!

**Comment by prabhu** [comment]
log4j needs to be at 2.19.0 to avoid this error
