### ISSUE TITLE
Limiting depth of query

### ISSUE THREAD

**Issue by avalanche-pwn** [joernio/joern#2313]
Hi,
I couldn't find it in docs, is there any way to limit depth of search in `.repeat(x)(_.until)` queries?

**Comment by mpollmeier** [comment]
Sounds like `maxDepth` is what you're looking for. 
For a full overview: https://github.com/ShiftLeftSecurity/overflowdb/blob/master/traversal-tests/src/test/scala/overflowdb/traversal/RepeatTraversalTests.scala

**Comment by itsacoderepo** [comment]
Closing, because the issue seems to be resolved.
