### ISSUE TITLE
[Bug] Error: -cp requires class path specification

### ISSUE THREAD

**Issue by riusksk** [joernio/joern#2316]
**Describe the bug**
Whenever I try to use Joern to parse C code on Windows, I encounter errors: `-cp requires class path specification`
Is this a bug?

**To Reproduce**
 
```
joern-parse.bat ./x42/c                                                                                                                                                                                    
Parsing code at: ./x42/c - language: `NEWC`
[+] Running language frontend
=======================================================================================================
Invoking CPG generator in a separate process. Note that the new process will consume additional memory.
If you are importing a large codebase (and/or running into memory issues), please try the following:
1) exit joern
2) invoke the frontend: D:\document\test\joern\joern-cli\c2cpg.bat -J-Xmx8152m ./x42/c --output cpg.bin
3) start joern, import the cpg: `importCpg("path/to/cpg")`
=======================================================================================================

Error: -cp requires class path specification
Failure: Could not generate CPG with language = NEWC and input = ./x42/c
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Joern Version : [v1.1.1482](https://github.com/joernio/joern/releases/tag/v1.1.1482)
 - Java version: java version "16.0.1" 2021-04-20

**Additional context**

**Comment by max-leuthaeuser** [comment]
Just tested that with the latest joern and it worked without any errors here on my Windows machine.
Can you try a clean joern install?

**Comment by riusksk** [comment]
I'm downloading the latest version of joern-cli from https://github.com/joernio/joern/releases/download/v1.1.1482/joern-cli.zip, decompressing it and running joern-parse.bat. 
Does it require additional installation?

**Comment by max-leuthaeuser** [comment]
Did you execute `joern-parse.bat` in the PowerShell?

**Comment by riusksk** [comment]
yes, Is it only run on cygwin or mingw?

**Comment by max-leuthaeuser** [comment]
For me it works in the PowerShell.

**Comment by riusksk** [comment]
it's ok on java 11.

**Comment by max-leuthaeuser** [comment]
@mpollmeier is this something for you?

**Comment by mpollmeier** [comment]
Hmm, not sure I can really help here, I don't have a working windows setup to reproduce this. 
Searching for your error there's a few pages that hint that you may need to fix your env variables, e.g.
https://9to5answer.com/error-classpath-requires-class-path-specification

Did you try that yet?
