### ISSUE TITLE
[Bug] jssrc no dataflow in object/array access

### ISSUE THREAD

**Issue by Tobiasfro** [joernio/joern#2317]
I'm trying to track dataflow from a method parameter to an index access call without success.
There seems like there is no dataflow between the parameter arg and the identifier arg on line 3. 

The following queries give no result

```cpg.identifier.reachableByFlows(cpg.method.parameter).p```
```cpg.call.argument.reachableByFlows(cpg.method.parameter).p```

```
importCode.javascript.fromString("""function myFunction(arg) {
                var o = {}
                var o1 = o[arg]
            }""")
```
The output that should be given is 

```
_____________________________________________________________________________
| nodeType          | tracked              | lineNumber| method     | file   |
|============================================================================|
| MethodParameterIn | myFunction(this, ... | 1         | myFunction | tmp.js |
| Identifier        | var o1 = o[arg]      | 3         | myFunction | tmp.js |
```

**Comment by max-leuthaeuser** [comment]
This is very strange indeed.
It fails for any index access already - so the object/array construction has nothing to do with it.

```
function myFunction(arg) {
  var o1 = o[arg]
}```

@maltek Any idea?

**Comment by maltek** [comment]
This is just a matter of how much over-tainting you want to accept. For an index access like `o[arg]` we only [transmit taint for the left-hand side](https://github.com/joernio/joern/blob/08b9ab629a0eb20882e169562ac9a03893fd3635/dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/DefaultSemantics.scala#L46). While `arg` certainly affects the result, `o[arg]` only has actual contents of `o` and not of `arg`.

You'd have to provide your own call semantics to change this.

**Comment by Tobiasfro** [comment]
I tried a similar case in c and then I got results for the same queries as above

```
importCode.c.fromString("""#include <stdio.h>

              int test(int arg){
                  int balance[4] = {8,8,8,860};
                  int arrres = balance[arg];
                  return arrres;
              }

              int main()
              {
                  printf("Hello World%d\n", test(2));


                  return 0;
              }""")
```

**Comment by maltek** [comment]
C semantics are different - you can write either `balance[arg]` or obfuscate that into `arg[balance]` and get the same results. Hence, the frontend C turns this into a `<operator>.indirectFieldAccess` which has different default semantics than the `<operator>.fieldAccess` which is generated by the JS frontend.

**Comment by Tobiasfro** [comment]
Okey, got it. How would I then provide my own call semantics? 

Is it as easy as:

1. Cloning the repo
2. Change F(Operators.indexAccess, List((1, -1))) to F(Operators.indexAccess, List((1, -1), (2,1)))
3. Run sbt stage in the repo

Or is there something else that needs to be done?

Sry if this is a newbie question but I do not know scala that well yet :)

**Comment by Tobiasfro** [comment]
Seems like that fixed it for me, thanks!!!

Do you have any documentation that explains what the number in List((1, -1), (2,1) means? For example, what does a negative number mean and what's the difference between 1 and 2?

**Comment by maltek** [comment]
I don't quickly see any docs for this. Afaik, `-1` is a special value for the return value of a function, and anything else is the index of a parameter. First value in the tuple is the source of taint and the second value the destination.

**Comment by Liyw979** [comment]
```
# "<operator>.sizeOf" reduces the FPs
# 1->-1 first parameter mapped to return value (-1)
```
The only doc I can find is this. 
You can find this when you checkout old versions, such as v1.1.1262
