### ISSUE TITLE
[Bug] jssrc missing dataflow to identifier in forEach loop

### ISSUE THREAD

**Issue by Tobiasfro** [joernio/joern#2333]
I was analyzing the code below where I used the query of ```cpg.identifier("value").reachableByFlows(cpg.method.parameter).p``` to track flow from a method parameter to the identifier "value". However, this gave no results

```
importCode.javascript.fromString("""module.exports.set = function (obj, path, value) {
	if (!isObject(obj) || typeof path !== 'string') {
		return;
	}

	var pathArr = path.split('.');
	pathArr.forEach(function (path, index) {
		if (!isObject(obj[path])) {
			obj[path] = {};
		}

		if (index === pathArr.length - 1) {
			obj[path] = value;
		}

		obj = obj[path];
	});
};""")
```

It seems like there is some problem with the data flow to an identifier from a method parameter when using a forEach loop.

I managed to reproduce the same missing dataflow with a much more basic example where the query of ```cpg.identifier("value").reachableByFlows(cpg.method.parameter.order(2)).p``` or ```cpg.call(Operators.assignment).reachableByFlows(cpg.method.parameter.order(2)).p``` gives no results

```
importCode.javascript.fromString("""function test(obj, value) {
                       Object.keys(obj).forEach(key => obj[key] = value)
                   }""")
```

Interestingly, when using a for-in loop as in the code below the queries of ```cpg.identifier("value").reachableByFlows(cpg.method.parameter.order(2)).p``` or ```cpg.call(Operators.assignment).reachableByFlows(cpg.method.parameter.order(2)).p``` gives the expected results. 

```
importCode.javascript.fromString("""function test(obj, value) {
                       for(var key in obj){
                           obj[key] = value
                       }
                   }""")
```

Output of ```cpg.identifier("value").reachableByFlows(cpg.method.parameter.order(2)).p`` when using for-in loop`:

```
________________________________________________________________________
| nodeType          | tracked              | lineNumber| method| file   |
|=======================================================================|
| MethodParameterIn | test(this, obj, v... | 1         | test  | tmp.js |
| Identifier        | obj[key] = value     | 3         | test  | tmp.js |
```

Output of ```cpg.call(Operators.assignment).reachableByFlows(cpg.method.parameter.order(2)).p``` when using for-in loop:

```
________________________________________________________________________
| nodeType          | tracked              | lineNumber| method| file   |
|=======================================================================|
| MethodParameterIn | test(this, obj, v... | 1         | test  | tmp.js |
| Identifier        | obj[key] = value     | 3         | test  | tmp.js |
| Call              | obj[key] = value     | 3         | test  | tmp.js |
| Call              | obj[key] = value     | 3         | test  | tmp.js |
```

**Comment by max-leuthaeuser** [comment]
Thanks for the report. It looks like the DF tracker is unable to track across the boundaries of the lambda function passed into `.forEach` which is strange because it works here: https://github.com/joernio/joern/blob/master/joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/dataflow/DataflowTest.scala#L608

Even in
```
function test(obj, value) {
  Object.keys(obj).forEach(key => value)
}
```
it does not work.


@maltek Any idea?

**Comment by maltek** [comment]
No clue. Apparently the oss dataflow engine doesn't make use of closure bindings, so no idea how (or if) it tracks closed-over variables.

**Comment by fabsx00** [comment]
I'll look into this one.

**Comment by fabsx00** [comment]
Briefly discussed this with @DavidBakerEffendi who has agreed to look into it, given that he has recently contributed very similar fixes.

**Comment by fabsx00** [comment]
Ok, great, so fixed by https://github.com/joernio/joern/pull/2343

**Comment by DavidBakerEffendi** [comment]
@Tobiasfro If you run into any strange flows or flows that don't track across closures, feel free to re-open the issue and I'll take a deeper look into it.

**Comment by Tobiasfro** [comment]
@DavidBakerEffendi Will do, thanks for your fix! Very helpful 😄
