### ISSUE TITLE
Inconsistency while parsing C macros

### ISSUE THREAD

**Issue by jaiverma** [joernio/joern#2335]
While parsing a C file, joern is doing macro expansion in a condition if the macro is the first argument, but not when it is the second,
```c
#define FLAG_A 1

int func(int x) {
    if (x & FLAG_A) {
        return 0;
    }
    else if (FLAG_A & x) {
        return 1;
    }
}
```
```
joern> cpg.call.name(Operators.and).code.p
res1: List[String] = List("x & FLAG_A", "1 & x")
```
imo, macro should not be expanded

**Comment by max-leuthaeuser** [comment]
@fabsx00 
This one is interesting. It looks like we do not expand the second macro to the artificial macro call because the locations somehow overlap and are filtered out here: https://github.com/joernio/joern/blob/master/joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/MacroHandler.scala#L54

I created a branch to test this: https://github.com/joernio/joern/tree/max/issue2335

**Comment by jaiverma** [comment]
I believe the difference in behaviour is because of the `expandedFromMacro` function in `MacroHandler.scala`.
The documentation for [getNodeLocations](https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.cdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fcdt%2Fcore%2Fdom%2Fast%2Fcpp%2FICPPASTTranslationUnit.html) mentions that it can return multiple locations which may or not be `IASTMacroExpansionLocation`,
```
Returns the location of this node. In cases not involving macro expansions, the IASTNodeLocation[] result will only have one element in it, and it will be an IASTFileLocation.

Where the node is completely generated within a macro expansion, IASTNodeLocation[] result will have one element in it, and it will be an IASTMacroExpansionLocation.

Nodes that span file context into a macro expansion (and potentially out of the macro expansion again) result in an IASTNodeLocation[] result that is of length > 1. 
```

![image](https://user-images.githubusercontent.com/8081757/223426677-ad5d11e8-166d-4369-8325-cb0dd277e653.png)

For the first binary expression (`x & FLAG_A`), the `node.getLocation` API returns two locations (`[ASTFileLocation, ASTMacroExpansionLocation]`).

![image](https://user-images.githubusercontent.com/8081757/223427035-f63dadcc-a5b9-4a73-9038-9d52f9d6a57f.png)

```scala
private def expandedFromMacro(node: IASTNode): Option[IASTMacroExpansionLocation] = {
  val locations = node.getNodeLocations
  if (locations.nonEmpty) {
    node.getNodeLocations.headOption.collect { case x: IASTMacroExpansionLocation => x }
  } else {
    None
  }
}

```

`expandedFromMacro` returns the first location which happens to be an `ASTFileLocation` for this expression.

![image](https://user-images.githubusercontent.com/8081757/223426807-871c16f9-adfa-451a-90c9-c2c85bc06981.png)

When we reach the second binary expression (`FLAG_A & x`), `node.getLocation` returns two locations in the reverse order as last time (`[ASTMacroExpansionLocation, ASTFileLocation]`).

![image](https://user-images.githubusercontent.com/8081757/223426966-0af4d206-e3ac-4b8c-b1a8-e9c314ab3b99.png)

This time, the function returns the `ASTMacroExpansionLocation` which leads to different behaviour.

This was my patch which fixes this issue, but this leads `MacroHandlingTests4` to fail. It messes up creating a call operator and arguments for `A_MACRO`.

```scala
private def expandedFromMacro(node: IASTNode): Array[IASTMacroExpansionLocation] = {
  val locations = node.getNodeLocations
  if (locations.length == 1) {
    node.getNodeLocations.head match {
      case x: IASTMacroExpansionLocation => Array(x)
      case _ => Array()
    }
  } else {
    Array()
  }
}
```
