### ISSUE TITLE
Import a package in joern

### ISSUE THREAD

**Issue by wcy1997** [joernio/joern#2354]
I notice that Joern's console supports scala. Now I want to import a new package to do more things. I wonder
 how to configure a pom.xml to introduce related dependencies?

**Comment by mpollmeier** [comment]
We (currently) use ammonite for the REPL, which has a very neat way to add dependencies:

http://ammonite.io/#import$ivy

example:
```
import $ivy.`com.michaelpollmeier::colordiff:0.35`
```

![grafik](https://user-images.githubusercontent.com/506752/223950358-015b0b67-bd71-484f-a9dd-4f6e23e2339f.png)

Note that we're in the process of upgrading to Scala3 though, and therefor removing ammonite. The new REPL will also have a way to add dependencies, but you'll need to do that when you start it.

**Comment by fabsx00** [comment]
Looks like this is taken care of. Feel free to reopen if you need more info.
