### ISSUE TITLE
[Bug]object dataflowengineoss is not a member of package io.shiftleft

### ISSUE THREAD

**Issue by Fr3ya** [joernio/joern#2379]
**Describe the bug**
I want to run `joern --script test.scala target_code_cpg.bin`
However, when I run this command, I met `object dataflowengineoss is not a member of package io.shiftleft`
**To Reproduce**
The code which produce the bug: 
```
import io.shiftleft.dataflowengineoss.language._
import io.shiftleft.dataflowengineoss.queryengine.EngineContext
```

**Desktop (please complete the following information):**
 - OS: MACOS
 - Joern 1.1.1461
 - JDK 17

**Additional context**
I guess it is because I don't have the plugin  io.shiftleft.dataflowengineoss. However, I have downloaded it, but I don't know where I should place it.
I also tried to run joern --add-plugin, but it does not work.
What should I do?

**Comment by mpollmeier** [comment]
replace `shiftleft` with `joern` and it should work:
```scala
import io.joern.dataflowengineoss.language._
import io.joern.dataflowengineoss.queryengine.EngineContext
```

**Comment by fabsx00** [comment]
yep, that should fix it. Closing. Feel free to reopen if there's still a problem.
