### ISSUE TITLE
[Bug] TypeScript Abstract Functions are Members not functions

### ISSUE THREAD

**Issue by DavidBakerEffendi** [joernio/joern#2380]
**Describe the bug**
Using a simple abstract TypeScript class, we can illustrate the issue. Below is a snippet of code:
```typescript
export abstract class Scene {
    game: Game;
    gl: WebGL2RenderingContext;
    public constructor(game: Game){
        this.game = game;
        this.gl = game.gl;
    }

    public abstract load(): void;
    public abstract timer(): void;
    public abstract start(): void; 
    public abstract draw(deltaTime: number): number;
    public abstract end(): void; 
}
```
The abstract methods above are members, with the only function being the constructor.

**To Reproduce**
1. Load the above code in the CPG
2. Run `cpg.typeDecl.name("Scene").method.name.l`, observe `List("<init>")`
3. Run `cpg.typeDecl.name("Scene").member.name.l`, observe `List("game", "gl", "public abstract load(): void;", ...)`

**Expected behavior**
Abstract functions should be methods not members

**Desktop (please complete the following information):**
 - OS MacOs Ventura
 - Joern Version 1.1.1519
 - Java version 18

**Comment by max-leuthaeuser** [comment]
Thanks for the report. I am looking into this.
