### ISSUE TITLE
[Bug] Astgen failed to parse vue in some cases

### ISSUE THREAD

**Issue by yzn12345** [joernio/joern#2393]
**Describe the bug**
![image](https://user-images.githubusercontent.com/56081290/225794787-eedd0f13-6cdf-4a7d-a386-d77302bcffc2.png)
![image](https://user-images.githubusercontent.com/56081290/225794835-6201340b-5795-4b76-b358-ee704d317e4a.png)

**Comment by fabsx00** [comment]
Thanks for the report. Fix is in.
