### ISSUE TITLE
Release pysrc2cpg for scala3

### ISSUE THREAD

**Issue by Liyw979** [joernio/joern#2401]

**Comment by mpollmeier** [comment]
We're currently working on the migration of the entire joern ecosystem to Scala 3, and I'm happy to say that we're not far away. Until then, you should be able to use the 2.13 artifacts, even if you're using Scala3 in your build, since Scala3 can interpret Scala2.

**Comment by Liyw979** [comment]
Thank you @mpollmeier 
I try `ThisBuild / scalaVersion := "3.2.2"` in my project and get

![image](https://user-images.githubusercontent.com/16919236/226292322-bb0038d2-bd06-4545-86ad-6c10b90763f9.png)

**Comment by Liyw979** [comment]
After using `"io.joern" %% "pysrc2cpg" % "1.1.1535" cross CrossVersion.for3Use2_13`
![image](https://user-images.githubusercontent.com/16919236/226843009-a4ffb99d-31d5-4078-acc5-a21a49562e8e.png)
Do I have to exclude these conflict versions manually?
