### ISSUE TITLE
[jssrc2cpg] [Bug] dataflow of multiple assignment is broken

### ISSUE THREAD

**Issue by Liyw979** [joernio/joern#2404]
```
    val cpg: Cpg = code("""
        |const tmp = source();
        |const number = 1, str = tmp.sink()
        |""".stripMargin)
    def src = cpg.call("source")
    def snk = cpg.call("sink")
    snk.reachableByFlows(src).p.foreach(println)
```

It seems that the order of assigments presenting in the AST is wrong.

![image](https://user-images.githubusercontent.com/16919236/226277174-c36ba15d-fcad-44e5-a2e4-30ebc36bb44a.png)

**Comment by fabsx00** [comment]
I think there's a semicolon missing in that test case (`tmp.sink();`), but that probably doesn't make a difference. This is the C frontend, right?

**Comment by Liyw979** [comment]
Ah...I forget to add the frontend for this, which is jssrc2cpg.
I am making a PR for this btw.

**Comment by fabsx00** [comment]
Ah, great. Thanks!
