### ISSUE TITLE
How to use joern as a lib

### ISSUE THREAD

**Issue by for-just-we** [joernio/joern#2405]
Hi, authors. I used to use joern as a tool, but I need to write additional scripts to parse the output results. So now I want to write my own tool based on joern-API. I just want to output the code property graph in my favored format. How to do that. Are there any documents or sample projects about using joern as a lib?

**Comment by Liyw979** [comment]
https://github.com/fabsx00/standalone

**Comment by for-just-we** [comment]
> https://github.com/fabsx00/standalone

Thank you

**Comment by itsacoderepo** [comment]
Closing, because it seems to be solved
