### ISSUE TITLE
[Bug] NullPointerException in JavaScriptTypeRecovery Pass

### ISSUE THREAD

**Issue by pr0me** [joernio/joern#2407]
The new JavaScriptTypeRecovery default overlay results in a non-recoverable crash and non-creation of a CPG on some samples.

**To Reproduce**
1. Import the attached Typescript project.
[ts_bug_sample.zip](https://github.com/joernio/joern/files/11029223/ts_bug_sample.zip)
2. Observe the following error:
```java
2023-03-21 13:53:35.489 ERROR CpgPassBase: Pass io.joern.jssrc2cpg.passes.JavaScriptTypeRecovery failed
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006) ~[?:?]
	at io.joern.x2cpg.passes.frontend.XTypeRecovery.$anonfun$run$3(XTypeRecovery.scala:63) ~[io.joern.x2cpg-1.1.1536.jar:1.1.1536]
[...]
```

**Expectation:**
The CPG creation should finish correctly.
If not possible, the new pass should fail gracefully and explain why TypeRecovery could not be performed on the sample. 

**Desktop:**
 - OS: Linux pop-os 6.0.12-76060006-generic
 - Joern: v1.1.1536 
 - Java: javac 11.0.18

**Comment by DavidBakerEffendi** [comment]
Recreate the bug with 
```scala
  "decorator should" should {
    val cpg = code(
      """import { Component } from '@angular/core';
        |
        |@Component({
        |  selector: 'tributech-root',
        |  templateUrl: './app.component.html',
        |  styleUrls: ['./app.component.scss'],
        |})
        |export class AppComponent implements OnInit {
        |
        |}
        |
        |""".stripMargin, "app.component.ts")

    "crash the CPG" in {
      cpg.identifier("_tmp_0").l
    }
  }
  ```
