### ISSUE TITLE
The neo4jcsv of ast cannot be exported separately ，How to solve this problem？ In addition, the value \ "in the cpp file cannot be imported after exporting neo4jcsv. The following error message is displayed.

### ISSUE THREAD

**Issue by PWJ1900** [joernio/joern#2427]
![image](https://user-images.githubusercontent.com/43459089/228182344-2c735712-960b-4b54-a4f7-54bd2a95933e.png)

![image](https://user-images.githubusercontent.com/43459089/228181995-d3d10749-16c9-47c1-8553-4848764fdf43.png)

**Comment by PWJ1900** [comment]
> Can you share some steps to reproduce, please?

the first picture in the issue (An error is reported after executing the following statement)：
                                       joern-parse /src/directory
                                      ./joern-export --repr=ast --format=neo4jcsv
![image](https://user-images.githubusercontent.com/43459089/229664892-7853c8dc-870e-4e68-bb84-ad4b2a40c41e.png)


the second pictuer in the issue (In the data import of neo4j) :
The corresponding data source cpp statement :  redis.command("xxx", "xxx", ".", "{\"xxxx\":\"xxx\",\"xxx\":xxxx,\"loggedOut\":xxx,\"xxxx\":{\"xxxx\":\"xxxx\",\"xxxx\":[\"xxxx\",\"xxxxx\"]}}");

![image](https://user-images.githubusercontent.com/43459089/229664930-c1b76ef1-a378-40d0-8638-3667b99da975.png)

**Comment by mpollmeier** [comment]
joern-export doesn't currently support this combination of `--repr=ast --format=neo4jcsv` unfortunately. 
https://github.com/joernio/joern/blob/master/joern-cli/src/main/scala/io/joern/joerncli/JoernExport.scala

For available combinations check out https://docs.joern.io/exporting
