### ISSUE TITLE
[Bug] joern-parse --language don't work

### ISSUE THREAD

**Issue by gystar** [joernio/joern#2436]
**Describe the bug**
The joern version is v1.1.1542.
I use Joern-parse to parse c files.
But I found that Joern-parse can't work right when the file extension is ".txt" and I set the option "--language c".
The generated cpg file is very small (only 16k) and Joern-export will cast an error.
Then I renamed all the files to ".cpp" files, and it worked.

**Comment by max-leuthaeuser** [comment]
This is not a bug.
It works as intended. The individual language frontends will only look for typical for extensions.

**Comment by max-leuthaeuser** [comment]
If you don't use the language flag joern-parse will choose a frontend appropriate for the majority of the files in your folder (e.g., 10 *.cpp files and 5 *.js -> C frontend is selected).
To override this behavior you can use the language flag.

**Comment by fabsx00** [comment]
Closing as it seems resolved. Feel free to reopen if you'd like to discuss further.
