### ISSUE TITLE
Bring passes and passesNot to joern

### ISSUE THREAD

**Issue by prabhu** [joernio/joern#2438]
**Is your feature request related to a problem? Please describe.**
passes and passesNot feature

**Describe the solution you'd like**
Easy way to filter flows.

**Describe alternatives you've considered**

**Additional context**

**Comment by DavidBakerEffendi** [comment]
I did make an attempt at writing these at `io.shiftleft.semanticcpg.language.nodemethods.CfgNodeMethods.[passesNot|passes]` using the dominator tree. Perhaps if this doesn't work according to how it should then tests should be added to verify the behaviour
