### ISSUE TITLE
Runnin Gremlin Queries in joern CLi

### ISSUE THREAD

**Issue by AtaKaboudi** [joernio/joern#2449]
Hey , i am working on a project where i have a bunch of gremlin queries to run on a code property graph. i am currently working on joern and  i am not sure if the joern cli language covers everything gremlin does.
**here is a sample of the queries  i am working on :** [Sample Queries ](https://github.com/aalhuz/python-joern/blob/navex/Analysis.py)
 Is there a way to run gremlin queries in joern CLI ?
And Please i am having problems understanding the key/value pairs in the parameters of each node. Is there a clear documentation about the content of every node,
Thank you

**Comment by itsacoderepo** [comment]
Hello! 

please checkout https://docs.joern.io, it contains queries and documentation about the CPG (https://docs.joern.io/code-property-graph) as well as the language reference (https://docs.joern.io/cpgql/reference-card). 

There is no out of the box way to run those queries and we do not plan to support it. The underlying technology has changed.

**Comment by mpollmeier** [comment]
+1, you won't be able to run your queries "as-is". 

That being said: at first sight, you should be able to port all those queries. The underlying cpg query dsl is built on top of [overflowdb Traversal](https://github.com/ShiftLeftSecurity/overflowdb/tree/master/traversal/src/main/scala/overflowdb/traversal) which contains many gremlin-like steps, e.g. `outE` etc.

**Comment by itsacoderepo** [comment]
Closing, because the issue seems to be resolved.
