### ISSUE TITLE
[Bug] Joern-Scan misidentifies apk files as Java src

### ISSUE THREAD

**Issue by WilliamParks** [joernio/joern#2460]
**Describe the bug**
`joern-scan` calls `javasrc2cpg` on an Android apk file, rather than `jimple2cpg`

**To Reproduce**
`./joern-scan --names testQuery ./foo/app-debug.apk --overwrite` produces

```
=======================================================================================================
Invoking CPG generator in a separate process. Note that the new process will consume additional memory.
If you are importing a large codebase (and/or running into memory issues), please try the following:
1) exit joern
2) invoke the frontend: /home/b/projects/joern/joern-cli/target/universal/stage/javasrc2cpg -J-Xmx16064m /home/b/projects/joern/foo/app-debug.apk --output /home/b/projects/joern/workspace/app-debug.apk/cpg.bin.zip
3) start joern, import the cpg: `importCpg("path/to/cpg")`
=======================================================================================================
```

**Expected behavior**
The importer calls `jimple2cpg`

**Comment by mpollmeier** [comment]
Thanks for reporting!
For reference, `importCode` in joern console correctly chooses `jimple2cpg`.
joern-scan seems to have different heuristics to guess the language - I'll take a look.

**Comment by mpollmeier** [comment]
https://github.com/joernio/joern/blob/e2a92bb/console/src/main/scala/io/joern/console/BridgeBase.scala#L320 language != frontend...
