### ISSUE TITLE
Support to exlude the files/directories in given repository from CPG creation

### ISSUE THREAD

**Issue by dbMundada** [joernio/joern#2466]
**Is your feature request related to a problem? Please describe.**
Sometimes repositories contains the ***.test.ts** files or **tests/** folder or external libraries folders like **node_modules/** in Javascript case. Joern tries to build the cpg for all & run the queries all over directory which may take lots of time which is unnecessary.

**Describe the solution you'd like**
Joern should accept some arguments/config in array form which contains the regex patterns. If any file path matches against that regex pattern it should be excluded from CPG.

**Additional context**
Example like in this repo: https://github.com/satwantsingh007/college, I want to skip the **venv** folder but its not supported currently in joern

**Comment by max-leuthaeuser** [comment]
Folders ignored by default are: https://github.com/joernio/astgen/blob/8553cd4e29cd5ed2a5657471d687472fddfbc6b1/index.js#L8

Currently there is no way to include them other than renaming the affected folders. That's something we may want to change in the future.

But adding stuff via regex is already supported. Simply use the following command line args for jssrc2cpg:

```
  --exclude <file1>,<file2>,...
                           files to exclude during CPG generation (paths relative to <srcdir> or absolute paths)
  --exclude-regex <value>  a regex specifying files to exclude during CPG generation (the absolute file path is matched)
```

**Comment by dbMundada** [comment]
@max-leuthaeuser Is this specific to jssrc2cpg or applicable to all the Frontends available ?

**Comment by max-leuthaeuser** [comment]
Sorry, this is specific to jssrc2cpg.

**Comment by Liyw979** [comment]
The python frontend do exclude the `.venv` folder.
https://github.com/joernio/joern/blob/58dbc4f6a76dcf37f44f9f4eb5b717caf49a7f7f/joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/Py2CpgOnFileSystem.scala#L12-L18
