### ISSUE TITLE
JSSRC - Type recovery / Type hint call linker performance problems

### ISSUE THREAD

**Issue by max-leuthaeuser** [joernio/joern#2530]
**Describe the bug**
When importing juice-shop (TS/JS) into Joern the type recovery / type hint call linking takes ages.

**To Reproduce**
1) git clone https://github.com/juice-shop/juice-shop
2) import into Joern
3) see how long these two passes run while the raw CPG coming from jssrc2cpg and also all other passes are finished quickly.

**Additional context**
Maybe its a heap memory problem but as the project isn't that large I suspect a general performance problem with the two passes.

**Comment by DavidBakerEffendi** [comment]
Will profile it 👍

**Comment by DavidBakerEffendi** [comment]
Update: I've narrowed it down to `RecoverForJavaScriptFile::isField`. Will look at optimizing this query or finding a better way to handle this functionality.

**Comment by DavidBakerEffendi** [comment]
@max-leuthaeuser Found that `isField` was doing linear time searches. This [PR](https://github.com/joernio/joern/pull/2536) reduces the time to finish within 2-3 minutes whereas without the fix it wasn't terminating on my machine.
