### ISSUE TITLE
[Question] Why do we need to choose BSP? What will go wrong if sbt is choosen?

### ISSUE THREAD

**Issue by Liyw979** [joernio/joern#2665]
the document
>  Back to Intellij: open project: select your local joern clone: select to open as BSP project (i.e. not sbt project!)

**Comment by mpollmeier** [comment]
the whole ecosystem (scala, sbt, intellij etc.) evolve over time, so this instruction may be outdated - ideally both options should work

back when we added those notes intellij type resolution would work much better in BSP mode. I.e. if you used sbt mode you'd get many red squiggles for 'unknown type|function|...'.

**Comment by Liyw979** [comment]
Actually I just find out that I have been using the sbt option for several months and didn't notice any weird warnings :)
