### ISSUE TITLE
[Q]  How to set not to skip java test code when importing a project?

### ISSUE THREAD

**Issue by bczhaoa** [joernio/joern#2776]
I used importCode to import a project.
cpg.importCode(inputPath="D:\\doxygen\\srcCode\\xxxt", projectName="xxxt")

Run the cpg.file.l command to find that the files in the src/test directory are not scanned.
According to the documentation, joern disables the scanning of test code by default.
I looked for joern's installation directory and found no configuration file.
So I don't know how to turn this switch on and let the test code be scanned.
I don't understand the scala language, so I can't look up the information from the source code.

------------------
我使用了 importCode 导入了一个工程
cpg.importCode(inputPath="D:\\doxygen\\srcCode\\xxxt", projectName="xxxt")

然后通过 cpg.file.l 发现我的 src/test 路径下的文件没有被扫描
查阅资料发现 joern 默认关闭了 测试代码的扫描。
我寻找了下 joern的安装目录，没有发现配置文件。
因此我也不知道如何打开这个开关，让测试代码被扫描。
我不懂scala语言，因此也无法从源码中查询相关信息。

**Comment by Liyw979** [comment]
https://github.com/joernio/joern/blob/e4d4e7c8ea462af303f48097bc76254249ddcc28/joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/SourceRootFinder.scala#L16

It is hard coded for the moment.

**Comment by Liyw979** [comment]
Consider renaming the `src/test` folder to something else as a temporary solution.

**Comment by bczhaoa** [comment]
Thank you , Does joern have plans to make the scan path configurable?
