### ISSUE TITLE
how to parse c/cpp declaration modifier

### ISSUE THREAD

**Issue by Icyrockton** [joernio/joern#2806]
```c
static int __init nonx32_setup(char *str)
{
	if (!strcmp(str, "on"))
		force_personality32 &= ~READ_IMPLIES_EXEC;
	else if (!strcmp(str, "off"))
		force_personality32 |= READ_IMPLIES_EXEC;
	return 1;
}
```

e.g. `__init ` modifier

**Comment by max-leuthaeuser** [comment]
Looks like the `__init` macro is from `include/linux/init.h`.
So please include that in your code and make sure its actually available in your system.
You can then run c2cpg with `--with-include-auto-discovery` to discover this header file and expand the macro correctly.
