### ISSUE TITLE
rubysrc2cpg: Complete List of Built-in Functions

### ISSUE THREAD

**Issue by DavidBakerEffendi** [joernio/joern#2972]
**Is your feature request related to a problem? Please describe.**
In a recent PR, I have included the detection for built-in calls which are then later given a method full name prefixed with `__builtin`. This list is small for now, but is incomplete.

**Describe the solution you'd like**
Under `io.joern.rubysrc2cpg.astcreation.AstCreatorHelper` there is an object `GlobalTypes` with a note on what needs to be filled out and a link to all the built-in calls. Some of these calls are object constructors and I think they should also be included as the basic types are also considered "built in" in other frontends such as Python and JS.

**Comment by xavierpinho** [comment]
Fixed in #3088
