### ISSUE TITLE
[Bug] Ruby parsing issue

### ISSUE THREAD

**Issue by rahul-privado** [joernio/joern#3022]
**Describe the bug**
Ruby parser fails for the below code
Please keep the conversation English! Make it easy for us and share your input code or a minified example. 

**To Reproduce**
Load [this](https://github.com/redis/redis-rb/blob/master/lib/redis/distributed.rb) code in the Ruby parser and see it failing.
Once this has been fixed please import the entire repository to verify that it does not produce any more parser issues

**Expected behavior**
Parsing should pass

**Screenshots**
NA
**Desktop (please complete the following information):**
 NA

**Additional context**

**Comment by ankit-privado** [comment]
@xavierpinho still facing parser issue in [this](https://github.com/redis/redis-rb/blob/master/lib/redis/distributed.rb) file (using intellij ANTLR plugin).

**Comment by xavierpinho** [comment]
For future reference, bear in mind that the ANTLR plugin is not to be 100% trusted, as it doesn't take into account custom predicates/semantic actions.

Nevertheless, just double-checked and you're right: the following is not properly handled:

```ruby
"#{@command.to_s.upcase} cannot be used in Redis::Distributed because the keys involved need " \
          "to be on the same server or because we cannot guarantee that the operation will be atomic."
``` 

Missing is the support for recognising strings separated by `\`.

Let's continue work in #3081
