### ISSUE TITLE
[Bug] jssrc: missing REF edges for locals for destructured parameters

### ISSUE THREAD

**Issue by maltek** [joernio/joern#3024]
from https://github.com/puppeteer/puppeteer/blob/14b236965000c2821aece8deae72fb927ab33930/experimental/puppeteer-firefox/lib/Page.js#L737-L740

```javascript
function _onConsole({type, args, executionContextId, location}) {
  const context = this._frameManager.executionContextById(executionContextId);
  this.emit(Events.Page.Console, new ConsoleMessage(type, args.map(arg => createHandle(context, arg)), location));
}
```

```
joern> cpg.identifier.name("location").not(_.refsTo).size 
val res1: Int = 1
joern> cpg.identifier.name("location").not(_.refsTo).astParent.code.l
val res4: List[String] = List("location = param1_0.location")
```

cc @DavidBakerEffendi since you recently changed some code around that area (though I'm not sure that broke it) and @max-leuthaeuser as regular jssrc maintainer

**Comment by DavidBakerEffendi** [comment]
Yeah, this looks related to the work I've been doing around de-structured parameters. I assumed that the `Ast` class would do a bit more, but I see now that the `REF` edges aren't added when handling these.
