### ISSUE TITLE
[Bug] Ruby parsing issue

### ISSUE THREAD

**Issue by ankit-privado** [joernio/joern#3037]
Describe the bug

Ruby parser fails for the below code
Please keep the conversation English! Make it easy for us and share your input code or a minified example.

To Reproduce
Load [this](https://github.com/cagandhi/Library-Management-System-Rails/blob/3024f31310accf4d4287dd31ced64b9b6bf37e1d/app/controllers/book_requests_controller.rb#L29) code in the Ruby parser and see it failing.

Expected behavior
Parsing should pass

Screenshots
NA

Desktop (please complete the following information):
NA

Additional context
NA

**Comment by xavierpinho** [comment]
A minified sample is `x = a+@b`. This should be parsed as a binary expression `+` between `a` and `@b`. The issue is that `+@` is a token by itself.

**Comment by xavierpinho** [comment]
Another minified sample is with `foo(x:y)`. This is meant to be a `foo` call with an association `x:y` for argument, but `:y` is being first recognized as a symbol.

**Comment by xavierpinho** [comment]
@ankit-privado Looks like #3147 added this is now parsed in full. Let me know if you still find issues in it.
