### ISSUE TITLE
[Bug][rubysrc2cpg] - 1:4 no viable alternative at input ' %w'  

### ISSUE THREAD

**Issue by pandurangpatil** [joernio/joern#3167]
**Describe the bug**
Getting parser error "1:4 no viable alternative at input ' %w'"

**To Reproduce**
code to reproduce the error

```
    %w[stripe braintree paddle fake_processor].each do |processor_name|
      puts processor_name
    end
```

**Comment by pandurangpatil** [comment]
@xavierpinho tagging you for parser errors

**Comment by xavierpinho** [comment]
Thanks for the sample, but closing this as a duplicate of #3040
