### ISSUE TITLE
[Bug][rubysrc2cpg] -  %r is not supported

### ISSUE THREAD

**Issue by pandurangpatil** [joernio/joern#3171]
**Describe the bug**
getting parser error -` no viable alternative at input 'def to_regexp(name)\n %'`
**To Reproduce**
Sample code to reproduce the error

```
      def to_regexp(name)
        %r{^#{Regexp.escape name_with_namespace(name)}}
      end
```

You can also refer to the entire code snippet - https://github.com/pay-rails/pay/blob/master/lib/pay/webhooks/delegator.rb#L56C1-L58

**Comment by pandurangpatil** [comment]
@xavierpinho tagging for parser error

**Comment by xavierpinho** [comment]
Thanks for the sample, but closing this as a duplicate of #3040
