### ISSUE TITLE
[Bug] `browse` missing after upgrade to scala3

### ISSUE THREAD

**Issue by fabsx00** [joernio/joern#3174]
**Describe the bug**

The `browse` feature described here https://docs.joern.io/shell/ is missing  now. Also, the documentation still states that the shell is based on ammonite, which it no longer is.

**To Reproduce**

Type `browse` on the joern shell.

**Expected behavior**

`browse` takes the output of the query and makes it available in a pager, e.g., `less`.

**Comment by fabsx00** [comment]
This may actually be a good opportunity to get rid of `browse` altogether and instead automatically pipe into a pager when the result that comes back is too long to fit onto the screen.

**Comment by fabsx00** [comment]
Another possibility would be to introduce the ability to pipe to arbitrary shell commands, e.g.,

```
cpg.method.fullName.l | less
```

That would be even cooler, especially, if we could chain:

```
cpg.method.fullName.l | awk ... | less
```

**Comment by prabhu** [comment]
@fabsx00 I think the powershell approach of passing objects via piped commands is better. Shell supports only passing text across commands thereby requiring jq and other commands to make it useful.

**Comment by mpollmeier** [comment]
got a rough first sketch - need to simplify it though

**Comment by mpollmeier** [comment]
part 1: https://github.com/mpollmeier/scala-repl-pp/pull/84

**Comment by mpollmeier** [comment]
The new `.browse` step opens the results in `less` - screenshot of `cpg.method.browse`:
![image](https://github.com/joernio/joern/assets/506752/f6900001-d80e-41b8-ac41-7c934aea47e4)

And the output redirection now has a different name `#>` (the old one is deprecated and redirects to the new one):
![image](https://github.com/joernio/joern/assets/506752/bb1ca6e5-f08c-4486-bdb2-5bb5d4af786c)

We now have pipe operators - the latter one makes the subprocess inherit stdin and stdout:
```
cpg.method #| "cat"
cpg.method #|^ "less"
```

The website has been updated:
https://docs.joern.io/shell/#exporting-results-with-pipe-operators-and-tojson

**Comment by mpollmeier** [comment]
actually: the above will only become true once https://github.com/joernio/joern/pull/3504 is merged
