### ISSUE TITLE
[Bug][rubysrc2cpg] do keyword issue

### ISSUE THREAD

**Issue by ankit-privado** [joernio/joern#3175]
Describe the bug
getting parser error - ` mismatched input 'do' expecting <EOF> at line 1`
To Reproduce
```
RSpec.configure do |config|
  config.before(:suite) do
    DatabaseCleaner.clean_with :truncation, except: %w(ar_internal_metadata)
  end
end
```

**Comment by ankit-privado** [comment]
@xavierpinho i'm not confident about whether this issue is related to `do` keyword or not, but this fragment of code throwing error.

**Comment by xavierpinho** [comment]
> @xavierpinho i'm not confident about whether this issue is related to `do` keyword or not, but this fragment of code throwing error.

Indeed, the issue is still #3040, so I'll be closing this one. But thanks for the sample either way!
