### ISSUE TITLE
Understanding dummy assignments in Python

### ISSUE THREAD

**Issue by khemrajrathore** [joernio/joern#3178]
@fabsx00 @DavidBakerEffendi  @ml86
 
In python, I see we create dummy assignments for function

- For builtins if we encounter a builtin call we create a assignment
- For functions if we encounter a definition

Ex - if the source code is 
```
def foo():
   print("I am here")
return 4

foo(3)
```

we create 2 dummy assignment
```
print = __buitlins__.print
foo = def foo(...)
```
To me it looks like this is been done to facilitate types in typeRecovery. Other than that is there any other reason to do this?

**Comment by ml86** [comment]
Those assignments model language semantics. When defining a function foo with `def foo()...` your python program will end up with a local variable which holds a reference to the function implementation. Only when this is reflected in the CPG representation you can do call resolution and data flow tracking in cases like this:
```
def foo():
  ...
def bar():
  ...

foo = bar

foo() // call to bar via name of foo
```

**Comment by khemrajrathore** [comment]
Thanks @ml86, the same hold true for Ruby and it needs to be built in a similar fashion. Will make this change in ruby

**Comment by DavidBakerEffendi** [comment]
@khemrajrathore For more context, this wasn't necessarily done for the type recovery, but the type recovery does use this to match these calls with their methods - which it can get for free by parsing these `identifier-assigned-to-method-ref` structures.
