### ISSUE TITLE
[Bug][rubysec2cpg] - comma separated json object

### ISSUE THREAD

**Issue by ankit-privado** [joernio/joern#3182]
Describe the bug
getting parser error - ` mismatched input ',' expecting` 

To Reproduce
below code parsing as expected

```
api :POST, '/send', 'Resend code'
  errors_standard_login
  errors_validation
  example <<-JSON
    {
      "code": 0
    }
  JSON
```
facing parser issue in below code

```
api :POST, '/send', 'Resend code'
  errors_standard_login
  errors_validation
  example <<-JSON
    {
      "code": 0
    },
  JSON
```

Notice the second last line where `,` is there.

**Comment by xavierpinho** [comment]
It's the same issue as #3169, so I'll be closing this one.
