### ISSUE TITLE
[Bug][rubysrc2cpg] - defining method with = sign not supported

### ISSUE THREAD

**Issue by pandurangpatil** [joernio/joern#3187]
**Describe the bug**
Getting parser error for below sample code

**To Reproduce**

```
    class SampleCls 
      def someConstant = "some message"
    end
```

This is the syntax supported since Ruby 3 - https://acuments.com/how-to-write-single-line-functions-in-ruby.html#:~:text=This%20allows%20programmers%20to%20write,(2%2C%202)%20%23%204

Interestingly this following lambda function sample gets parsed.

```
# Define a lambda that takes two arguments and returns their sum
add_lambda = ->(a, b) { a + b }

# Call the lambda and print the result
result = add_lambda.call(10, 20)
puts result # Output: 30
```

**Comment by pandurangpatil** [comment]
@xavierpinho tagging you for parser errors.

**Comment by xavierpinho** [comment]
Wasn't aware of this feature, thanks. Though, this means a big change on the parser, so we'll handle other Ruby 2.x stuff first, then.
