### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by DongShuaike** [joernio/joern#3206]
**Describe the bug**
Fail to exit the joern interactive shell. 
```
joern> exit
-- [E006] Not Found Error: -----------------------------------------------------
1 |exit
  |^^^^
  |Not found: exit
  |-----------------------------------------------------------------------------
  | Explanation (enabled by -explain)
  |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  | The identifier for exit is not bound, that is,
  | no declaration for this identifier can be found.
  | That can happen, for example, if exit or its declaration has either been
  | misspelt or if an import is missing.
   -----------------------------------------------------------------------------
1 error found
```

I built joern from scratch using `sbt stage` and successfully compiled. 
However, I tried **`exit`, `quit` , `exit;`, `exit()` etc.**  and none of them can exit the program.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 
 - Joern Version: 2.0.22+8-3090d51f
 - Java version: java version "17.0.8" 2023-07-18 LTS

**Comment by max-leuthaeuser** [comment]
It's Ctrl-D now.
See: https://docs.joern.io/shell/

**Comment by itsacoderepo** [comment]
Or `System.exit(0)`

https://docs.oracle.com/javase/8/docs/api/java/lang/System.html#exit-int-
