### ISSUE TITLE
[Bug] Potential memory leak caused by PythonTypeRecovery

### ISSUE THREAD

**Issue by yzn12345** [joernio/joern#3211]
**Describe the bug**
Memory usage goes up sigificantly for the second type recovery pass. `cloc` shows the code base has ~80k loc.

**To Reproduce**
1. Source code:
[mmdetection.zip](https://github.com/joernio/joern/files/12142985/mmdetection.zip)
2. importCode.python("")
3. iteration num attribute is set to 2
4. Initial run of type recovery uses 2.6gb ram
5. Second run causes gc monitor clearing references
![image](https://github.com/joernio/joern/assets/56081290/b65ffca3-ff39-4267-855f-9c0c86d6c76b)

**Screenshots**

**Desktop (please complete the following information):**
 - Win
 - Joern 2.0.1

**Comment by yzn12345** [comment]
Memory Analyzer leak suspect:
![image](https://github.com/joernio/joern/assets/56081290/d89fbc6c-21fe-4b8c-8eaa-fbc2e020a8e3)
![image](https://github.com/joernio/joern/assets/56081290/4534cc2e-636c-47b5-b9ef-57214adbba3b)

**Comment by yzn12345** [comment]
Not digging too much into the code, but wondering whether the memory spike is due to: "ForkJoinParallelCpgPass will wait until all parts and mutations are done, merge into one big diffgraph and apply that in one go." 
If so, is it possible to use ConcurrentWriteCpgPass which writes intermediate results to flatten the curve?
@DavidBakerEffendi

**Comment by DavidBakerEffendi** [comment]
@yzn12345 Good observation, that has been at the back of my mind though when I initially tried it seemed to have failed a test here and there, but I think it is about time I address that. I'll get started on that next.

**Comment by DavidBakerEffendi** [comment]
@yzn12345 Hmm, one issue that writing intermediate results poses is that the interprocedural checks (e.g., checking methods, fields, etc.) may differ as results are written in whatever order and cause a read race-condition. While this is not super terrible, it may mean flaky tests.

A solution here is to simply cache the parts we need of the CPGs, e.g. mapping method names to their return types, type declarations and their field names and types, etc. This cache then won't change, and we can write our results immediately while referring to this.

One may need to weigh up which uses more memory, but I feel that all the accumulated `DiffGraph` objects in the queue may be more memory intensive than a couple of maps and their strings.

**Comment by yzn12345** [comment]
> @yzn12345 Hmm, one issue that writing intermediate results poses is that the interprocedural checks (e.g., checking methods, fields, etc.) may differ as results are written in whatever order and cause a read race-condition. While this is not super terrible, it may mean flaky tests.
> 
> A solution here is to simply cache the parts we need of the CPGs, e.g. mapping method names to their return types, type declarations and their field names and types, etc. This cache then won't change, and we can write our results immediately while referring to this.
> 
> One may need to weigh up which uses more memory, but I feel that all the accumulated `DiffGraph` objects in the queue may be more memory intensive than a couple of maps and their strings.

😃Agreed! Using cache maps is less memory-intensive than keeping a backlog of diffs in the diffGraph builder's `ArrayDeque<Change> _buffer`.

**Comment by DavidBakerEffendi** [comment]
Will be working with @badly-drawn-wizards to implement this

**Comment by yzn12345** [comment]
@DavidBakerEffendi Analyzed the heap dump using the memory analyzer again and found something interesting:
![image](https://github.com/joernio/joern/assets/56081290/b3961234-e18c-4464-ae98-e71b471ee1c2)
By listing the outgoing reference of one of the biggest `setNodeProperty` who have very large retained size redirected us to this page:
![image](https://github.com/joernio/joern/assets/56081290/a94f7436-82be-43c5-bbd7-1f2ce0b1874b)
That one call node is causing the `mmdetection` program's memory to grow exponentially, and it's because of the `dynamicTypeFullName` attribute, which is set to have approximately 2 million values.

However, changing from an accumulating updating style to an immediate updating style will not have any negative consequences and may still mitigate the memory issue somehow.

**Comment by DavidBakerEffendi** [comment]
@yzn12345 Ah, good find. Those seem to be many permutations of dummy types and their dummy access paths. The intention behind this is that the prefixes should describe where the type "comes from" but I'm sure we don't need 2 mill values lol. 

I think merging various dummy types based on common prefixes should hopefully bring this down too.
