### ISSUE TITLE
Some confusion in using Joern

### ISSUE THREAD

**Issue by clccc** [joernio/joern#325]
I want to get `REACHING_DEF` edge's information. I can get the edge's "`label`", but cannot get its "`VARIABLE`", the result showed below. What is the right query command?
![image](https://user-images.githubusercontent.com/12693134/91412147-ef33eb00-e87b-11ea-9b17-2160bbb0192b.png)

As in the above example, there is some buge confusion in using joern, specially in writing joern scripts. 
1. Suppose I've got a node ID and I want to get information about that node, I use the command `cpg.id(XXX).l`. And the command `cpg.id(xxx).id.l ` return right, but the commands ` cpg.id(xxx).name.l` and ` cpg.id(xxx).code.l`  are wrong.  Why？
![image](https://user-images.githubusercontent.com/12693134/91414631-6ae36700-e87f-11ea-8108-1521b74225be.png)

2. Then suppose I know the node is a "call", so I run some commands，the result showed below. 
![image](https://user-images.githubusercontent.com/12693134/91415617-e4c82000-e880-11ea-8e28-2102cc515366.png)
Why I get the `code`, `name `right, but the `argumentIndex ` returned wrong?
 Is it means the node tyes (`id, code ,name ,order, methodInstFullName, argumentIndex, dispatchType ...`) is not all of  keys of the "call“ code？ How can I get a right "nodeKeys" list of a node from the joern shell? When I want to get nodeKeys of a node, do I need to know the node type in advance? If it is yes, how can I get the “nodeTypes” of  a node with `id` as input ? 

The above problems are some of my confusion when using joern. This may be because the function of Joern is not perfect, but it is more likely that I do not fully understand the usage of Joern. However, I think there may be many other people who encounter similar problems, so I write it out deliberately. I am sorry for the trouble caused to you, and I sincerely hope to get your advice

**Comment by ursachec** [comment]
unclear what this issue is about, will have to close. maybe try asking on the discord channel with a more specific example
