### ISSUE TITLE
rubysrc2cpg: handle function def in attr_accessor params 

### ISSUE THREAD

**Issue by tuxology** [joernio/joern#3330]
## Describe the bug
While defining `attr_accessor` as follows, the method definition is populated as another argument instead of the accessor list terminating at `cd` due to presence of additional `,`: 

```
class Bar

  attr_accessor :ab,
    :cd,
  def self.foo
    current.foo
  end

end
``` 

This causes the following error while building the CPG:
```
Exception in thread "Writer" java.lang.RuntimeException: Edge with type='ARGUMENT' with direction='IN' not supported by nodeType='METHOD'
        at overflowdb.NodeDb.storeAdjacentNode(NodeDb.java:651)
        at overflowdb.NodeDb.storeAdjacentNode(NodeDb.java:630)
        at overflowdb.NodeDb.addEdgeSilentImpl(NodeDb.java:324)
        at overflowdb.Node.addEdgeSilentInternal(Node.java:37)
        at overflowdb.NodeRef.addEdgeSilentImpl(NodeRef.java:168)
        at overflowdb.Node.addEdgeSilentInternal(Node.java:37)
        at overflowdb.BatchedUpdate$DiffGraphApplier.applyChange(BatchedUpdate.java:304)
        at overflowdb.BatchedUpdate$DiffGraphApplier.run(BatchedUpdate.java:249)
        at overflowdb.BatchedUpdate.applyDiff(BatchedUpdate.java:17)
        at io.shiftleft.passes.ConcurrentWriterCpgPass$Writer.run(ParallelCpgPass.scala:151)
        at java.base/java.lang.Thread.run(Thread.java:1623)
java.lang.RuntimeException: Failure in diffgraph application
        at io.shiftleft.passes.ConcurrentWriterCpgPass.createApplySerializeAndStore(ParallelCpgPass.scala:114)
        at io.shiftleft.passes.NewStyleCpgPassBase.createAndApply(CpgPass.scala:124)
```

Tested the above piece of code in Ruby interpreter and it seems to be valid. 

## To Reproduce
Use the sample code above and generate CPG using `rubysrc2cpg`

Following error is observed:
`Exception in thread "Writer" java.lang.RuntimeException: Edge with type='ARGUMENT' with direction='IN' not supported by nodeType='METHOD'`

## Expected behavior
Separate method node gets produced not added to the accessor list

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Joern Version: `master` at [e12978b](https://github.com/joernio/joern/commit/e12978b64e8eb27314a24e09f314fcccfaeadb9e)

## Additional context
Parser output for method added to argument of accessor:

![image](https://github.com/joernio/joern/assets/3373857/33b8a3af-d214-4b3d-a35c-dced51ffd7f2)

PArser output when the extra `,` is removed from `cd,`

![image](https://github.com/joernio/joern/assets/3373857/09fdee04-a95e-4e2d-9a3d-bb9baaf0e90e)

**Comment by xavierpinho** [comment]
`self.foo`  is indeed being passed as the 3rd argument to `attr_accessor`, but that's the correct parse tree here. That "extra" comma after `:cd` makes all the difference. This is a matter of extending the AstCreator support to handle this.

**Comment by tuxology** [comment]
@xavierpinho But attr_accessor only takes instance variables isn't it? So clearly when we encounter this, the last `,` token could be discarded then? Or do you suggest we handle this in AST Creator by ensuring that if a method is encountered in accessor list, it should be considered not part of the list? I am confused - is this even valid to add method in an accessor list from Ruby's perspective 🤔

**Comment by xavierpinho** [comment]
> @xavierpinho But attr_accessor only takes instance variables isn't it? So clearly when we encounter this, the last `,` token could be discarded then? Or do you suggest we handle this in AST Creator by ensuring that if a method is encountered in accessor list, it should be considered not part of the list? I am confused - is this even valid to add method in an accessor list from Ruby's perspective 🤔

It can also take [strings](https://ruby-doc.org/core-2.3.0/Module.html#method-i-attr_accessor) and... apparently method definitions are ok too. For instance, running your sample

```ruby
irb(main):001:1* class Bar
irb(main):002:1* 
irb(main):003:1*   attr_accessor :ab,
irb(main):004:1*     :cd,
irb(main):005:2*   def self.foo
irb(main):006:2*     current.foo
irb(main):007:1*   end
irb(main):008:1* 
irb(main):009:0> end
=> [:ab, :ab=, :cd, :cd=, :foo, :foo=]
irb(main):010:0> 
```

we can see it extracted the method name and used it as a symbol. 

I have yet to find where and how this idiom is used, but from a syntactical point of view, there's nothing special about `attr_accessor`, it's an invocation like any other.

So, I think the parser doesn't need to be changed here, but rather the AstCreator for `attr_accessor` calls should be able extract a symbol name from the method definition too.

**Comment by tuxology** [comment]
@xavierpinho Yes, I just tested more on interpreter like you. You are right. We need to handle this in AstCreator. PR incoming from me 😎
