### ISSUE TITLE
[Bug][c2cpg] import node can be find, but can not find which file import it.

### ISSUE THREAD

**Issue by bczhaoa** [joernio/joern#3438]
joern> cpg.imports.id(455580L).l
val res10: List[io.shiftleft.codepropertygraph.generated.nodes.Import] = List(
  Import(
    id = 455580L,
    code = "#include \"asn-util.h\"",
    columnNumber = Some(value = 1),
    explicitAs = None,
    importedAs = Some(value = "asn-util.h"),
    importedEntity = Some(value = "asn-util.h"),
    isExplicit = None,
    isWildcard = None,
    lineNumber = Some(value = 19),
    order = -1
  )
)

joern> cpg.imports.id(455580L).file.l
val res11: List[io.shiftleft.codepropertygraph.generated.nodes.File] = List()

joern>

![image](https://github.com/joernio/joern/assets/96362132/cae0c51a-bc3f-4e03-8047-63fb60d1b46e)

joern verison is  2.0.39

**Comment by max-leuthaeuser** [comment]
Do you have the source code you scanned somewhere available?

**Comment by bczhaoa** [comment]
![image](https://github.com/joernio/joern/assets/96362132/82319984-7425-43b0-8870-326fb1a7f9a3)

this is the source code
