### ISSUE TITLE
[Bug] Recent Java Type Inference Speed-Up Leads to Missing Types

### ISSUE THREAD

**Issue by DavidBakerEffendi** [joernio/joern#3527]
**Describe the bug**
Recent changes from https://github.com/joernio/joern/commit/02a375ed132aac18e7430b55d8c70331b1639bad have lead to missing type information for certain calls. 

The example used is https://github.com/devdcores/BookStoreApp-Distributed-Application and the call in question can be queried with: `cpg.call.nameExact("getMyPaymentMethodById").lineNumber(331).l`

**To Reproduce**
1. Build Joern on commit `5d98ee8568f4f47e3f404133e0421343f6cfe8cf` (before the speedup commit) and generate CPG using the repo above
2. Run query `cpg.call.nameExact("getMyPaymentMethodById").lineNumber(331).l` and see
```
  Call(
    id = 15818L,
    argumentIndex = 2,
    argumentName = None,
    code = "getMyPaymentMethodById(o.getPaymentMethodId())",
    columnNumber = Some(value = 64),
    dispatchType = "DYNAMIC_DISPATCH",
    dynamicTypeHintFullName = ArraySeq(
      "com.devd.spring.bookstorecommons.feign.PaymentFeignClient.getMyPaymentMethodById:com.devd.spring.bookstorecommons.web.GetPaymentMethodResponse(java.lang.String)"
    ),
    lineNumber = Some(value = 331),
    methodFullName = "com.devd.spring.bookstorecommons.feign.PaymentFeignClient.getMyPaymentMethodById:com.devd.spring.bookstorecommons.web.GetPaymentMethodResponse(java.lang.String)",
    name = "getMyPaymentMethodById",
    order = 2,
    possibleTypes = ArraySeq(),
    signature = "com.devd.spring.bookstorecommons.web.GetPaymentMethodResponse(java.lang.String)",
    typeFullName = "com.devd.spring.bookstorecommons.web.GetPaymentMethodResponse"
  )
```
3. Build Joern on commit `02a375ed132aac18e7430b55d8c70331b1639bad ` (the speedup commit) and generate CPG using the repo above
4. Run query `cpg.call.nameExact("getMyPaymentMethodById").lineNumber(331).l` and see
```
  Call(
    id = 15818L,
    argumentIndex = 2,
    argumentName = None,
    code = "getMyPaymentMethodById(o.getPaymentMethodId())",
    columnNumber = Some(value = 64),
    dispatchType = "DYNAMIC_DISPATCH",
    dynamicTypeHintFullName = ArraySeq(
      "com.devd.spring.bookstorecommons.feign.PaymentFeignClient.getMyPaymentMethodById:<unresolvedSignature>(1)"
    ),
    lineNumber = Some(value = 331),
    methodFullName = "com.devd.spring.bookstorecommons.feign.PaymentFeignClient.getMyPaymentMethodById:<unresolvedSignature>(1)",
    name = "getMyPaymentMethodById",
    order = 2,
    possibleTypes = ArraySeq(),
    signature = "<unresolvedSignature>(1)",
    typeFullName = "com.devd.spring.bookstorecommons.web.GetPaymentMethodResponse"
  )
```
5. See difference in `signature` and `methodFullName`

**Expected behavior**
No change in types as a result of the speedup PR

**Comment by johannescoetzee** [comment]
The speedup pr did end up including a bug fix with how caching was done and argument type matching. It looks like the new version finds a signature where the previous did not. Is the result wrong? It's not obvious from the file linked.

**Comment by johannescoetzee** [comment]
If the mfn/signature is correct, then I don't see why this would have to be reverted. If they're wrong, then this would be something to look at.

**Comment by johannescoetzee** [comment]
@DavidBakerEffendi are you sure the query outputs are in the correct order in the issue? 

Assuming they are swapped, then I suspect the culprit is the argument type filtering. If that is the case, then some heuristics can be added to match calls in some cases where argument types could not be resolved or such.

**Comment by DavidBakerEffendi** [comment]
@johannescoetzee sorry my bad, the order was wrong. Will update the issue.

**Comment by DavidBakerEffendi** [comment]
@johannescoetzee So it appears that the interface of the call's receiver (`PaymentFeignClient`) is in the CPG and describes the signature of `getMyPaymentMethodById`, so it is strange that this is missing.

**Comment by johannescoetzee** [comment]
@DavidBakerEffendi The issue seems to be that the call argument type is `ANY`, so matching type full names failed since that's just a string comparison. The linked PR changes the logic so that `ANY` matches all types, so that fixes the issue in this instance.

**Comment by johannescoetzee** [comment]
There will still be newly unresolved types with the post-speedup version if the argument typeFullName is a subclass of the parameter type, but that's a TODO and is a decision that was made for the sake of more accurate results when results are found
