### ISSUE TITLE
[Bug] JavaSrc2Cpg : Missing Type Information in Java after revamping Type Inference Pass

### ISSUE THREAD

**Issue by khemrajrathore** [joernio/joern#3552]
**Describe the bug**
With the recent changes made to JavaSrc2Cpg's Type Inference Pass, we are observing some loss in the methodFullName and signature for some call nodes. 
Suspected PRs causing the delta 
- https://github.com/joernio/joern/pull/3500
- https://github.com/joernio/joern/pull/3532

One such example is being shared below

**To Reproduce**
Steps to reproduce the behaviour:
1. Using Joern version `2.0.61+`
2. Clone the repo - https://github.com/devdcores/BookStoreApp-Distributed-Application
3. Import this repo using ImportCode
4. Run the query - `cpg.call("findByUserName").lineNumber(127).l`
5. See the output with unresolved Signature
```
Call(
    id = 3544L,
    argumentIndex = 0,
    argumentName = None,
    code = "findByUserName(userName)",
    columnNumber = Some(value = 7),
    dispatchType = "DYNAMIC_DISPATCH",
    dynamicTypeHintFullName = ArraySeq(),
    lineNumber = Some(value = 127),
    methodFullName = "com.devd.spring.bookstoreaccountservice.repository.UserRepository.findByUserName:<unresolvedSignature(0)>",
    name = "findByUserName",
    order = 1,
    signature = "<unresolvedSignature(0)>",
    typeFullName = "java.util.Optional"
  ) 
```

**Expected behavior**
The Types should be resolved like it used to be till Joern version `2.0.52`
```
Call(
    id = 3544L,
    argumentIndex = 0,
    argumentName = None,
    code = "findByUserName(userName)",
    columnNumber = Some(value = 7),
    dispatchType = "DYNAMIC_DISPATCH",
    dynamicTypeHintFullName = ArraySeq(),
    lineNumber = Some(value = 127),
    methodFullName = "com.devd.spring.bookstoreaccountservice.repository.UserRepository.findByUserName:java.util.Optional(java.lang.String)",
    name = "findByUserName",
    order = 1,
    signature = "java.util.Optional(java.lang.String)",
    typeFullName = "java.util.Optional"
  )
  ```
  @johannescoetzee 
  
  cc- @DavidBakerEffendi

**Comment by johannescoetzee** [comment]
The issue here is with the `findByUserName` argument types. 

```
joern> cpg.call("findByUserName").argument.l
val res5: List[io.shiftleft.codepropertygraph.generated.nodes.Expression] = List(
  Call(
     ... // This one seems fine
  ),
  Identifier(
    code = "userName",
    lineNumber = Some(value = 127),
    name = "userName",
    typeFullName = "<unresolvedNamespace>", // Issue is here
    ... 
  )
)
```

The issue is the `<unresolvedNamespace>` type for the identifier, where it should be `ANY` if unresolved, which would then fix the argument <-> param type matching as well.

**Comment by DavidBakerEffendi** [comment]
Thanks for the quick find! @johannescoetzee. Do you have bandwidth to implement the related fix, or should we attempt a fix and take over?
