### ISSUE TITLE
[Q] what is the callee  default parmeter?

### ISSUE THREAD

**Issue by bczhaoa** [joernio/joern#3579]
I coded it like this in a separate project：
```scala
def methodCallParse(jFile: File): List[((Long, String), String, Int)] = {
    jFile.method.callee.typeDecl.file.filter(_.name.contains(Constant.huawei)).map(f => (f.id, f.name))
      .groupCount.l.map(tp => (tp._1, Constant.call, tp._2))
  }
```
Reported this error when I was packing ：
``` shell
JavaCpgUsedEdgeParser.scala:102:23: No given instance of type io.shiftleft.semanticcpg.language.
ICallResolver was found for parameter callResolver of method callee in class MethodTraversal
```
I want to know how I should call the callee method,
The callee method requires parameters in the source code. What is omitted in the callee method? Are there any differences between these two calls:

```scala
joern> cpg.method.callee.length
val res13: Int = 6484

joern> cpg.method.callee(NoResolve).length
val res14: Int = 6484

joern>
```

**Comment by maltek** [comment]
In open-source joern `NoResolve` is the only call resolver implementation. It's an extension point that allows for custom resolvers.

If you don't want to explicitly specify `NoResolve` everywhere in your own project you can define a variable like `implicit val resolver: ICallResolver = NoResolve`. You can find the same definition all over the place in the joern code-base.

**Comment by bczhaoa** [comment]
thank you !
