### ISSUE TITLE
[GO] - Handle FuncLit AST Node

### ISSUE THREAD

**Issue by pandurangpatil** [joernio/joern#3635]
Handle Below Code

```
package main

func main() {
	add := func(a, b int) int {
		return a + b
	}
	result := add(3, 5)
}

```

**Comment by pandurangpatil** [comment]
```
package main

import "fmt"

// Function that takes another function as an argument
func processInt(fn func(int) int, num int) int {
    return fn(num)
}

func main() {
    // Define a function to double an integer
    double := func(x int) int {
        return x * 2
    }

    // Use the processInt function to apply the double function
    result := processInt(double, 5)
    fmt.Println(result) // Output: 10
}

```

**Comment by pandurangpatil** [comment]
@DavidBakerEffendi Here are my thoughts on handling lambda expression in Go.

If you look at the above sample, while defining the function and calling the function, we can identify the signature of a function. e.g. 
The signature for the below example will be `func(int)int`
```
func(x int) int {
        return x * 2
    }
```

I think if we create a method full name for the lambda function same as the **signature** without any namespace or kind of global method. A similar method full name can be generated at the time of creation of the call node for the invocation statement of a lambda. This way, it will be able to connect the `CALL` node with `METHOD` node.

**Comment by DavidBakerEffendi** [comment]
@pandurangpatil What about 

```go
	add := func(a, b int) int {
		return a + b
	}
       subtract := func(a, b int) int {
		return a - b
	}
```
These both have the same signature, right?

In JavaScript, we make all of these methods with method ref assignments and then give temp names, e.g. `lambda_1` or something. Then there is a follow-up pass (ConstClosurePass or something) that checks if the method pointer, e.g. `add` is ever reassigned or not. If it's not, then we set the name and full name to the identifier it's assigned to, e.g. `add(int,int):int`.

**Comment by pandurangpatil** [comment]
```
package main

import "fmt"

func main() {
	// Define and immediately invoke an anonymous function
	result := func(x, y int) int {
		return x + y
	}(5, 7)

	fmt.Println(result) // Output: 12
}
```

**Comment by pandurangpatil** [comment]
This has been handled with the following PRS

#3870 
#3873 
#3885 
#3888 
#3899 
#3944
