### ISSUE TITLE
[GO] - Handle ChanType AST Node

### ISSUE THREAD

**Issue by pandurangpatil** [joernio/joern#3636]
Dependent on: https://github.com/orgs/joernio/projects/10/views/1?pane=issue&itemId=38445455
Handle below code: 

```
func foo(c chan int, someValue int) {
   c <- someValue * 5
}

func main() {
   fooVal := make(chan int)
   go foo(fooVal, 4)
}
```

**Comment by hiteshbedre** [comment]
Pull Request: https://github.com/joernio/joern/pull/3653
