### ISSUE TITLE
[GO] - Handle factory function return

### ISSUE THREAD

**Issue by pandurangpatil** [joernio/joern#3641]
Handle below code: 

```
func NewService(node *Node) *Service {
        return &Service{
                value: &Node{node},
        }
}
```

**Comment by hiteshbedre** [comment]
cpg.call("Service.<init>").l shouldBe 1
cpg.call("Node.<init>").l shouldBe 1

**Comment by hiteshbedre** [comment]
In sample add structure for Service and Node in same file.

**Comment by hiteshbedre** [comment]
Pull Request: https://github.com/joernio/joern/pull/3669
