### ISSUE TITLE
[c2cpg] Revisit the kernel benchmark

### ISSUE THREAD

**Issue by prabhu** [joernio/joern#3656]
**Is your feature request related to a problem? Please describe.**
I can't replicate the parser benchmark with recent Linux kernel versions with the command line arguments available.

https://github.com/joernio/joern/tree/master/joern-cli/frontends/c2cpg#parser-benchmarks

**Describe the solution you'd like**
We may need to follow the instructions below from CDT and pre-create an index for the tool to finish in a finite time.

https://github.com/eclipse-cdt/cdt/tree/main/FAQ#whats-the-best-way-to-set-up-the-cdt-to-navigate-linux-kernel-source

I suspect some AST creation logic is costly, causing the slowdown.

**Describe alternatives you've considered**
I tried creating a lighter frontend to parse only the header files and skip method bodies. Tried upgrading to CDT 11.2 and disabled macro expansion completely. These approaches didn't yield the kind of performance promised in the readme.

**Additional context**

**Comment by max-leuthaeuser** [comment]
Please note: the benchmark you linked is for parsing only. Ofc, the whole CPG generation takes much longer. 

@itsacoderepo has some recent numbers for running c2cpg on the kernel sources. But afair, he was running it on quite some beefy machine.

**Comment by max-leuthaeuser** [comment]
Also: Sadly, we can not use Eclipse Indexing at all as this is tightly coupled to Eclipse Workspaces and other internals that are not available as standalone libraries.

**Comment by prabhu** [comment]
@max-leuthaeuser below is the code I came up with to enable the index. Also tested with some projects. While it worked I didn't see a huge improvement probably some other setting is missing. 

https://github.com/AppThreat/chen/blob/main/platform/frontends/c2cpg/src/main/scala/io/appthreat/c2cpg/parser/CdtParser.scala#L53

**Comment by max-leuthaeuser** [comment]
I am pretty sure using the index would only be beneficial when doing some reparsing (file changes) which we won't have anyway.

**Comment by prabhu** [comment]
It must help avoid the need for lookups in the include directories as well as expand macros.

**Comment by max-leuthaeuser** [comment]
I guess one needs to prepopulate the index with the include directories. Last time I tried this it crashed due to missing runtime dependencies.
