### ISSUE TITLE
MethodFullName getting "ANY"

### ISSUE THREAD

**Issue by hiteshbedre** [joernio/joern#3692]
Code:

     package main

    import (
        "go.uber.org/zap"
    )

    func main() {
        logger := zap.Must(zap.NewProduction())

        defer logger.Sync()

        logger.Info("Hello from Zap logger!")
    }

Getting methodFullName for call `Info` as `ANY.Info`

**Comment by pandurangpatil** [comment]
This is done with download dependency ticket #3688
