### ISSUE TITLE
[GO] Handle global variable and constant

### ISSUE THREAD

**Issue by hiteshbedre** [joernio/joern#3695]
Global variable and constant is declared here: https://github.com/apm-dev/go-user-rest-api/blob/main/datasources/mysql/users_db/users_db.go

global variable is used here: https://github.com/apm-dev/go-user-rest-api/blob/main/domain/users/user_dao.go
(stmt, err := users_db.Client.Prepare(queryGetAll))

End outcome to verify: MethodFullName property for below call nodes would be get resolved:

cpg.call("Prepare").l

**Comment by pandurangpatil** [comment]
`<project_root>/lib/global.go `
```
package lib

var GlobalConstant string = "some constant"

```
`<project_root>/main.go`
```
package main

import "<project_root>/lib"
func main() {
   println(lib.GlobalConstant)
}

```

@fabsx00 @DavidBakerEffendi  I have the above scenario where the GlobalConstant variable is declared in the lib package. Then, its being accessed from another package function. It might get also be accessed from the same file i.e. `<project_root>/lib/global.go` or it also can be accessed from the same package in another file i.e. let's say from file `<project_root>/lib/somelib.go`. It can also be accessed outside of the package.

I have the following question.
Under which block node the respective `LOCAL` node should be created for this GlobalConstant declaration?
At the place where it is getting accessed, I am assuming we need to only create an `IDENTIFIER` node. Correct me if I am wrong here.
If my understanding is correct, how do I create a ref edge between the `LOCAL` node and `IDENTIFIER` node when the variable is accessed from another file (either from the same package or outside of the package)

cc: @hiteshbedre

**Comment by pandurangpatil** [comment]
Keeping it open, as this one is not handled completely.

**Comment by pandurangpatil** [comment]
Raised the PR https://github.com/ShiftLeftSecurity/codepropertygraph/pull/1736 to add ast parent properties to member node.
