### ISSUE TITLE
[Bug] Index out of bound for JavascriptTypeRecovery failed

### ISSUE THREAD

**Issue by dbMundada** [joernio/joern#3701]
**Describe the bug**
Index out of bound for JavascriptTypeRecovery failed.

![Image](https://github.com/joernio/joern/assets/5364736/d97ad8c3-3dae-411d-8bd2-5ba0e54cf1e5)

Repo: https://github.com/strapi/strapi

**To Reproduce**
1. Please try to load repo https://github.com/strapi/strapi with joern & you will get this error.

**Expected behavior**
Without any error above repo should work with Joern

**Screenshots**

**Comment by DavidBakerEffendi** [comment]
Seems this is a language agnostic bug, but for any languages that allows "," in the import path.
