### ISSUE TITLE
[Bug] Js frontend generates different number of nodes with same source files 

### ISSUE THREAD

**Issue by yzn12345** [joernio/joern#3746]
**Describe the bug**
Source code: [joi.zip](https://github.com/joernio/joern/files/13039136/joi.zip)
“importCode.javascript(xxx)” leads to diffent number of TYPE node. Want to know whether this affect dataflow engine checks like "reachableByXXX" or not.

**Screenshots**
![image](https://github.com/joernio/joern/assets/56081290/8d0952c4-f57f-4566-af67-83162e8695b8)
![image](https://github.com/joernio/joern/assets/56081290/e878a2bd-228c-48cc-8297-b4526a5aec46)

**Desktop (please complete the following information):**
 - Win11
 - Latest version

**Additional context**

**Comment by max-leuthaeuser** [comment]
This might indicate an issue with the type recovery mechanism by @johannescoetzee not being fully deterministic. 
@johannescoetzee Could you take a look if you have some time?

**Comment by yzn12345** [comment]
> This might indicate an issue with the type recovery mechanism by @johannescoetzee not being fully deterministic. @johannescoetzee Could you take a look if you have some time?
Still looking at this problem but have some progress.
![image](https://github.com/joernio/joern/assets/56081290/785cddd1-eb3e-4385-a45e-4b45ab2801db)
![image](https://github.com/joernio/joern/assets/56081290/2fca3fb4-19ac-4e0f-9a75-ecc231bca1dd)

**Comment by yzn12345** [comment]
> > This might indicate an issue with the type recovery mechanism by @johannescoetzee not being fully deterministic. @johannescoetzee Could you take a look if you have some time?
> > Still looking at this problem but have some progress.
> > ![image](https://private-user-images.githubusercontent.com/56081290/286082016-785cddd1-eb3e-4385-a45e-4b45ab2801db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNDExNDQsIm5iZiI6MTcwMTE0MDg0NCwicGF0aCI6Ii81NjA4MTI5MC8yODYwODIwMTYtNzg1Y2RkZDEtZWIzZS00Mzg1LWE0NWUtNGI0NWFiMjgwMWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDAzMDcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlYWY3YzNlNzI2Yjk2MjQ2Yzc3MWIxZTA2NGU5M2RlZGEyY2NiZWQzNDhiMTg0MTFmYzEzNzg2NjU5NDcxOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hvs0INmFlGb1_Qa2H42vKavMPQHKdF5wd0X2QPbHpeY)
> > ![image](https://private-user-images.githubusercontent.com/56081290/286082397-2fca3fb4-19ac-4e0f-9a75-ecc231bca1dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNDExNDQsIm5iZiI6MTcwMTE0MDg0NCwicGF0aCI6Ii81NjA4MTI5MC8yODYwODIzOTctMmZjYTNmYjQtMTlhYy00ZTBmLTlhNzUtZWNjMjMxYmNhMWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDAzMDcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZjY1NjBiNDY1NzNlNWI4ZmI3NzY4YTdiNWI5NjJlNTQ0YjM3ZDQ2ZTE4NDJhOTk4YmI1MmU2ZmM0NmFkMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RbZo4A8UDuzjWfUFghWkepQ-M-Dv_rOB_tlNx4KLX0E)

Finally found a minimum example that reproduced this.
File A:
![image](https://github.com/joernio/joern/assets/56081290/7c507821-a261-4e2f-bab5-2099f2e584ca)
File B:
![image](https://github.com/joernio/joern/assets/56081290/0a4a25f5-e1ef-4441-bb7d-e514d2a710cb)
And the `usedType` key value output comparison by diffchecker:
![image](https://github.com/joernio/joern/assets/56081290/2bb52540-0a9e-46af-a86d-80fe04a3b98a)
