### ISSUE TITLE
[Bug][JavaScript] ReachingDefPass hang

### ISSUE THREAD

**Issue by yzn12345** [joernio/joern#3778]
**Describe the bug**

**To Reproduce**
1. [grapesjs.zip](https://github.com/joernio/joern/files/13214091/grapesjs.zip)
2. importCode.javascript()

**Screenshots**
![image](https://github.com/joernio/joern/assets/56081290/5f4c2ec9-59a1-4552-b265-36bd442acee2)
![image](https://github.com/joernio/joern/assets/56081290/931fc6fb-6d74-4d40-868c-8d26ddfd14e9)

**Desktop (please complete the following information):**
 - OS: Win11
 - Joern Version: V2.0.138 
 - Java version

**Comment by max-leuthaeuser** [comment]
I was able to reproduce this on my machine.
@johannescoetzee You touched that piece of code recently. Maybe there is something wrong with the regex handling there? See: https://github.com/joernio/joern/commit/b916a61db9c8ea25939683fa99b46fca4423426c#diff-cc8c78a80b5c108ead37e1579243df1afa12b013570d60b23d140254d2fa3b06

**Comment by DavidBakerEffendi** [comment]
@max-leuthaeuser I see, let me have a look

**Comment by DavidBakerEffendi** [comment]
So there are no default semantics that make use of regex, but I'm seeing this hang on `io.joern.dataflowengineoss.passes.reachingdef.ReachingDefTransferFunction.initKill`.

The method calls `method.ast` only to collect identifiers and parameters. I'm sure this would be much faster using `.contains` edges.

**Comment by DavidBakerEffendi** [comment]
Seems that occasional really large methods are encountered, causing 1 thread to sit on this task alone - will also explore recursive thread forking.

**Comment by DavidBakerEffendi** [comment]
Update: Solved it, the bottlenecks were `.ast` calls on nodes really high up on the AST. Replaced these to make use of `CONTAINS` edges on more select nodes instead. PR will come soon. However, I am seeing slowdowns on subsequent passes as this is a large codebase - will investigate other instances of where things are hanging.

**Comment by DavidBakerEffendi** [comment]
Fix: https://github.com/joernio/joern/pull/3781
