### ISSUE TITLE
How to implement secondary development using Joern？

### ISSUE THREAD

**Issue by tyousyuka** [joernio/joern#3786]
My IntelliJ IDEA：![image](https://github.com/joernio/joern/assets/5753432/e85915a9-d17a-4155-b083-bbb923e1a316)
My sbt version：![image](https://github.com/joernio/joern/assets/5753432/c7800e40-cb87-493a-b639-840193c211b4)
My scala plugin：![image](https://github.com/joernio/joern/assets/5753432/6bf8a46e-6c66-4d88-9326-5789f82ad0bb)
My scala SDK：
![image](https://github.com/joernio/joern/assets/5753432/51eec2d2-ed2a-428f-bb67-619a9f836a76)

1, I git clone the joern project> https://github.com/joernio/joern.git
2, cd to local joern folder
![image](https://github.com/joernio/joern/assets/5753432/40974d4a-077d-471c-8109-f09953ffd2c9)
3, use cmd command to start sbt in this folder
![image](https://github.com/joernio/joern/assets/5753432/be91512f-d053-44fa-b83c-5a70386fb0c7)
4, open in idea
![image](https://github.com/joernio/joern/assets/5753432/0f8070b1-beb5-44ab-b8f9-f0aef3a45766)

bsp list
![image](https://github.com/joernio/joern/assets/5753432/fc489822-20bb-4a34-8a28-d50e7b9428c1)

could not run it
![image](https://github.com/joernio/joern/assets/5753432/c7082c9e-06df-470c-ab57-abb076689695)

******
And then, how can I run it or debug it in the idea? What is the detailed operation? 
![image](https://github.com/joernio/joern/assets/5753432/d949c89e-be47-4e7a-aa4b-4a89f117994f)

Thank You!!!
@fabsx00 @ursachec @mpollmeier @max-leuthaeuser @DavidBakerEffendi @johannescoetzee @scala-steward @xavierpinho @itsacoderepo @prabhu

**Comment by mpollmeier** [comment]
joern is a console application, you can develop it in intellij, but to run it you need to go back to the terminal and run `sbt stage` and then `./joern` (or in your case `./joern.bat` I guess, since you're on windows)

Please don't ping such a long list of contributors in the future. We would have seen your question anyway and this is just generating noise. Thanks.

**Comment by DavidBakerEffendi** [comment]
I believe @badly-drawn-wizards had some nice debugger attached to the REPL with IntelliJ? If I'm wrong, let me know, though it may be handy to have documented for future.

If I need the debugger, I usually approach this with either making some test case or configuring an IntelliJ application run to the `Main` class of the frontend I'm working on, however this without modifications does not include all overlays.

**Comment by prabhu** [comment]
@tyousyuka, Scala 3 with IntelliJ is definitely a PITA. I had to fiddle with sbt vs. bsp, use the scala 3 beta extension, and then play with the SDK settings to get it to recognize. Even then, the experience has been subpar, and I usually use the cli to build and test. An alternative is vs code with metals, which works but doesn't have all the refactoring capabilities of IntelliJ.

**Comment by tyousyuka** [comment]
@mpollmeier @DavidBakerEffendi 
Usually, after importing a project, this running icon will appear on the main function, like this
![image](https://github.com/joernio/joern/assets/5753432/95f034a1-bf8c-44a0-8952-6333813c6bd8)


But IDEA didn't recognize it after importing the Joern project, what is the reason?
![image](https://github.com/joernio/joern/assets/5753432/e6454ada-9018-469b-b249-d90f3c535c3b)

**Comment by mpollmeier** [comment]
Can you paste the version info from Menu -> Help -> About -> "Copy and close" here please? This is what I get:

IntelliJ IDEA 2023.2.4 (Community Edition)
Build #IC-232.10203.10, built on October 24, 2023
Runtime version: 17.0.8.1+7-b1000.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.1.49-1-manjaro
GC: G1 Young Generation, G1 Old Generation
Memory: 4048M
Cores: 16
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    scala.erase.compiler.process.jdk.once=false

Non-Bundled Plugins:
    IdeaVIM (2.5.1)
    net.seesharpsoft.intellij.plugins.csv (3.2.2-232)
    com.jetbrains.packagesearch.intellij-plugin (232.9921.28)
    org.intellij.scala (2023.2.853)
    com.github.tomasmilata.intelliroutes (2023.2.0)

Kotlin: 232-1.9.0-IJ10203.10
Current Desktop: XFCE

![grafik](https://github.com/joernio/joern/assets/506752/d56c5626-54c5-4e47-a2ec-f34ca7340b37)

**Comment by tyousyuka** [comment]
@mpollmeier Thank You
IntelliJ IDEA 2023.2.4 (Ultimate Edition)
Build #IU-232.10203.10, built on October 25, 2023
Licensed to U
Subscription is active until June 21, 2024.
For educational use only.
Runtime version: 17.0.8.1+7-b1000.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
    debugger.new.tool.window.layout=true
    terminal.use.conpty.on.windows=false
    ide.experimental.ui=true
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    org.antlr.intellij.plugin (1.22)
    Batch Scripts Support (1.0.13)
    one.util.ideaplugin.screenshoter (1.8.1)
    name.kropp.intellij.makefile (232.8660.88)
    org.plugin.dot.id (1.5.3)
    org.jetbrains.plugins.rest (232.8660.88)
    com.jetbrains.packagesearch.intellij-plugin (232.9921.28)
    org.jetbrains.kotlin (232-1.9.20-release-507-IJ10072.27)
    com.alibaba.p3c.xenoamess (2.1.1.6x-SNAPSHOT)
    org.intellij.scala (2023.2.27)
    Pythonid (232.10203.10)
    ai.codegeex.plugin (2.2.0)

Kotlin: 232-1.9.20-release-507-IJ10072.27

**Comment by mpollmeier** [comment]
Your scala plugin is `2023.2.27` and I'm on `2023.2.853`, that could well be the reason here. Our team always uses the latest nightlies, and if it turns out that's the issue we should add that to the readme for joern as well. 
Can you please try the following: File -> Settings -> Languages & Frameworks -> Scala -> Updates -> Update channel -> select 'nightly builds' and press 'check now'

Then, double check the version info from above and see if it works. You may need to reimport the project, not sure though.

**Comment by max-leuthaeuser** [comment]
I think you did the right things but at step 3:

> 3, use cmd command to start sbt in this folder

please also do a `compile` in the sbt console.
Best thing would be to start fresh with a clean checkout.

If that does not help you may also want to try to import the project as sbt project (not bsp) as a last resort.

**Comment by tyousyuka** [comment]
![微信截图_20231106091326](https://github.com/joernio/joern/assets/5753432/8c99dc47-9b20-43de-8492-4514db6f5803)
I run compile in the sbt console
@max-leuthaeuser @mpollmeier

**Comment by tyousyuka** [comment]
> I think you did the right things but at step 3:
> 
> > 3, use cmd command to start sbt in this folder
> 
> please also do a `compile` in the sbt console. Best thing would be to start fresh with a clean checkout.
> 
> If that does not help you may also want to try to import the project as sbt project (not bsp) as a last resort.

@max-leuthaeuser 
follow your method, it is OK now, thank you very much!!!
![compile](https://github.com/joernio/joern/assets/5753432/338d7fa0-4516-49fd-872f-b7dcb182d995)
![debug](https://github.com/joernio/joern/assets/5753432/97908cf2-fa8e-4da0-813b-99c6dd01514c)


@mpollmeier @max-leuthaeuser @DavidBakerEffendi 
And Then I want to package the program
does it use a command-line or in the idea? 
could you tell me how to do it?

I used the method in the below image,but it does not generate something in the joern folder
![image](https://github.com/joernio/joern/assets/5753432/102865bf-d657-4d9d-8160-61ab24179f7d)

I hope it can be generated like this
![image](https://github.com/joernio/joern/assets/5753432/93ff2b7d-a825-4b00-ae67-6ee92dcbc1a0)

**Comment by max-leuthaeuser** [comment]
To generate that zip file simply run `createDistribution` within the sbt console.

**Comment by tyousyuka** [comment]
> To generate that zip file simply run `createDistribution` within the sbt console.
@max-leuthaeuser 
it is ok! Thank you very much!!

**Comment by DavidBakerEffendi** [comment]
To avoid this issue cropping up again, could we add this to the [Joern docs](https://docs.joern.io)? Or a GitHub Wiki?

**Comment by mpollmeier** [comment]
Yes we should. There's already have a section for that in the readme https://github.com/joernio/joern#intellij-idea
I'll update it to reflect the latest and the relevant details.

**Comment by mpollmeier** [comment]
https://github.com/joernio/joern/pull/3794
