### ISSUE TITLE
[Perfomance][JS][ReachingDef] Long execution time

### ISSUE THREAD

**Issue by yzn12345** [joernio/joern#3819]
**Describe the bug**
[tfjs-models.zip](https://github.com/joernio/joern/files/13330464/tfjs-models.zip)

![image](https://github.com/joernio/joern/assets/56081290/15805d54-87f0-4a03-9b20-5fb10dce0537)

**Desktop (please complete the following information):**
 - WIN 11
 - Version: 2.0.151

**Comment by yzn12345** [comment]
Calculating the num of definition in reaching def pass for the following cost a lot of time before skipping.
![image](https://github.com/joernio/joern/assets/56081290/24094c37-1129-48c0-92b0-c30a2ea24940)
And these are actually calls with `methodFullName:` __ecma.array.* in cpg.
![image](https://github.com/joernio/joern/assets/56081290/1be8d5d9-9a3c-40ba-9999-2cc31bbbc220)
![image](https://github.com/joernio/joern/assets/56081290/3436468b-9fc8-4adc-bb5b-efdc4f40610e)
I am thinking if they are really indispensable in data flow. Could you please give me some advice? @max-leuthaeuser 
My first thought is to skip the reaching def calculation once it reaches the threshold without knowing the exact number, this could save some time. And another is to filter these out similiar to `fieldAccess` if they are not very important:
![image](https://github.com/joernio/joern/assets/56081290/1eb0c488-6f2f-42b0-a715-ac9614e16743)

**Comment by max-leuthaeuser** [comment]
We had a similar issue with c2pg and simply truncated the array. I'll try to get the same fix into jssrc2cpg.
