### ISSUE TITLE
[Bug] Failure to analyze c++ functions

### ISSUE THREAD

**Issue by riusksk** [joernio/joern#3825]
**Describe the bug**
Failure to analyze c++ functions

**To Reproduce**
source file is here: https://github.com/electron/electron/blob/e7074c5cdb1973ede8da4713ad079d2afa850cc8/atom/app/atom_main.cc

Execute the following command
```
joern-parse -o after_atom-app-atom_main.cc.bin after_atom-app-atom_main.cc --frontend-args --define """"OS_WIN=1""""
joern-export --repr pdg -o pdg-after_atom-app-atom_main after_atom-app-atom_main.cc.bin
```

After setting up the OS_WIN macro, no dot files are generated for the `wWinMain` and `main` functions. 
However, the IsEnvSet function successfully analyzes the relevant code after setting OS_WIN, indicating that OS_WIN was set successfully:
```
digraph "IsEnvSet" {  
"58" [label = <(METHOD,IsEnvSet)<SUB>42</SUB>> ]
"72" [label = <(METHOD_RETURN,bool)<SUB>42</SUB>> ]
"59" [label = <(PARAM,const char* name)<SUB>42</SUB>> ]
"62" [label = <(getenv_s,getenv_s(&amp;required_size, nullptr, 0, name))<SUB>45</SUB>> ]
"68" [label = <(RETURN,return required_size != 0;,return required_size != 0;)<SUB>46</SUB>> ]
"69" [label = <(&lt;operator&gt;.notEquals,required_size != 0)<SUB>46</SUB>> ]
...
```

**Expected behavior**
Generate dot files related to the winMain and main functions 

**Desktop (please complete the following information):**
 - OS: windows 10
 - Joern Version: 2.0.71
 - Java version: openjdk 17.0.1 2021-10-19

**Comment by max-leuthaeuser** [comment]
The main function `wWinMain` is not found because it can not be parsed correctly.
This can be seen with:
```
> .\c2cpg.bat --log-problems \path\to\source\ --define """"OS_WIN=1""""
[INFO ] Parse problem 'CPPASTProblem' occurred!
  Code: 'int APIENTRY wWinMain(HINSTANCE instance, HINSTANCE, wchar_t* cmd, int) {
  struct Arguments {
    int argc = 0;
    wchar_t** argv = ::CommandLineToArgvW(::GetCommandLineW(), &argc);
[...]
```

I suspect all the macros and special variables used there (`APIENTRY`, `HINSTANCE`, ...) are missing when scanning the file in isolation. Thus, that code block can not be parsed.

Notice, that the other main functions are hidden behinde flags as well (`OS_LINUX`, `OS_MACOSX`).

**Comment by riusksk** [comment]
you're right, it's ok after delete `APIENTRY `
