### ISSUE TITLE
[javascript] how to parse js to a cpg?

### ISSUE THREAD

**Issue by tyousyuka** [joernio/joern#3827]
I used joern-parse to parse a js file ,but it failed 
the command :  joern-parse xx.js --output=a.bin
<img width="984" alt="7607ec4356a3c2ee1ab6f822e39c906" src="https://github.com/joernio/joern/assets/5753432/69590bc1-1e60-4e25-a887-b00f15948a5f">

how can I use it to parse js file? thank you!! did it need another things?
@max-leuthaeuser @mpollmeier @DavidBakerEffendi

**Comment by DavidBakerEffendi** [comment]
You may need to place it in a directory, I believe I've encountered this before

**Comment by tyousyuka** [comment]
> You may need to place it in a directory, I believe I've encountered this before
@DavidBakerEffendi 
it is ok now,thanks
------
and then I has another question, it could not create edge:
![微信截图_20231116120252](https://github.com/joernio/joern/assets/5753432/7d0cd4f5-91cc-4790-aeb5-c947cdd75cee)

used command: \joern-cli\joern-parse.bat D:\360MoveData\ets\pages\test --output cpg.bin
and the log file>a.log [a.log](https://github.com/joernio/joern/files/13372171/a.log)
the typescript source file>ets.zip [ets.zip](https://github.com/joernio/joern/files/13372182/ets.zip)

**Comment by max-leuthaeuser** [comment]
Yes, Typescript is supported and you did everything just fine.
The messages you encountered can be ignored for now. Currently, or mapping / handling for Typescript types and their CPG representation is incomplete but should be sufficient for most queries.
