### ISSUE TITLE
[Help] how to set '--define' arg?

### ISSUE THREAD

**Issue by riusksk** [joernio/joern#3830]
joern-parse cmd params are as follows:
`['joern-parse', '--language', 'c', '-o', 'test.c.bin', 'test.c', '--frontend-args', '--define', '"SIGEV_THREAD_ID!=(SIGEV_THREAD_ID&~(SIGEV_SIGNAL|SIGEV_NONE|SIGEV_THREAD))"']`

but run fail:
```
Exception: '~' is not recognized as an internal or external command,
operable program or batch file.
```

how to set '--define' arg: `SIGEV_THREAD_ID!=(SIGEV_THREAD_ID&~(SIGEV_SIGNAL|SIGEV_NONE|SIGEV_THREAD))` ?

**Comment by max-leuthaeuser** [comment]
You can only set flags individually. The expression is not evaluated.
`--define SIGEV_THREAD_ID=1 --define SIGEV_SIGNAL=1` etc.
