### ISSUE TITLE
[Javascript]Failure to parse javascript with joern-parse

### ISSUE THREAD

**Issue by LLZPP** [joernio/joern#3866]
I used joern-parse to parse the javascript code and successfully generated cpg.bin, but when converting the cpg.bin to a dot file, I found that the result is the same, 33 nodes and 44 edges, it seems that it did not parse the javascript code successfully.

![image](https://github.com/joernio/joern/assets/75934327/55152373-f2b3-401c-9df1-6879953e3dfb)
![image](https://github.com/joernio/joern/assets/75934327/bf2ce149-45e9-4254-a3c5-981a51a3e638)
![image](https://github.com/joernio/joern/assets/75934327/bf4d98d3-c43f-4028-a088-4b842ac0a90c)

**Desktop (please complete the following information):**
 - OS：Linux
 - Joern Version :2.0.170
 - Java version: 19

**Comment by max-leuthaeuser** [comment]
Can you provide the JS code you scanned? Or a full log when running jssrc2cpg directly?

**Comment by LLZPP** [comment]
The javascript code I scanned was the code provided in the repository at joern/tests/code/jssrc/simple.js.

I ran jssrc2cpg.sh directly without reporting an error, and the results are not quite the same, but it doesn't seem to be parsing the code correctly either.




Strangely, I parsed an empty js file directly and got the same result, so I'm not sure what the problem is.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "joernio/joern"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月29日(星期三) 凌晨0:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [joernio/joern] [Javascript]Failure to parse javascript with joern-parse (Issue #3866)





 
Can you provide the JS code you scanned? Or a full log when running jssrc2cpg directly?

**Comment by max-leuthaeuser** [comment]
Just out of curiosity:
Could you please download the latest release (currently: https://github.com/joernio/joern/releases/download/v2.0.171/joern-cli.zip), unzip it, and start the Joern shell.
Then run:
```
joern> importCode.jssrc.fromString("""console.log("hello");""")
[...]
joern> cpg.method.plotDotPdg
```
The result should look like this:
![13410989028356337188](https://github.com/joernio/joern/assets/1417198/248a4741-397c-483a-bc8e-2842841caea7)

**Comment by LLZPP** [comment]
> Just out of curiosity: Could you please download the latest release (currently: https://github.com/joernio/joern/releases/download/v2.0.171/joern-cli.zip), unzip it, and start the Joern shell. Then run:
> 
> ```
> joern> importCode.jssrc.fromString("""console.log("hello");""")
> [...]
> joern> cpg.method.plotDotPdg
> ```
> 
> The result should look like this: ![13410989028356337188](https://private-user-images.githubusercontent.com/1417198/286682813-248a4741-397c-483a-bc8e-2842841caea7.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NzYxMzYsIm5iZiI6MTcwMTc3NTgzNiwicGF0aCI6Ii8xNDE3MTk4LzI4NjY4MjgxMy0yNDhhNDc0MS0zOTdjLTQ4M2EtYmM4ZS0yODQyODQxY2FlYTcuc3ZnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDVUMTEzMDM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWQ4MWQ3YjAzMjM0YTNmMmYwOTI1MWU5YzlhMzAwMTk2NGU5ZTJjMWI1ZTY2Y2Q4MDJhZjgxYjhjYTZlYzFkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Pb3THeV6X0BtzzrODERDsQenYyV8ne9mLus6khjc2d0)

I ran it according to your tips, the result is the same.
But I encountered a problem is why using the command 

> importCode.jssrc.fromString("""console.log("hello");""")

The final parsed CPG, which has 66 nodes, is shown below:
![image](https://github.com/joernio/joern/assets/75934327/ef677512-0773-47f3-890a-a0e513448745)


but I put `console.log(" hello");` this line of code saved in a test.js file, this file is located in the test folder, and then use the command 

> importCode.jssrc(". /test")

The final parsed CPG, however, only has 33 nodes, as shown in the following figure:
![image](https://github.com/joernio/joern/assets/75934327/4f6d42e7-9a27-4c4e-9e4a-2dda8bacac6e)

And using the command "cpg.method.plotDotPdg" at this time will not give any result.

what is the reason for this?

**Comment by max-leuthaeuser** [comment]
Oh, now its clear to me. 
Everything under test/ is ignored by default. See: https://github.com/joernio/astgen/blob/main/index.js#L8

**Comment by LLZPP** [comment]
It did, I changed the filename and it parsed successfully, thank you for your help!
