### ISSUE TITLE
[Bug] Error when generating slices

### ISSUE THREAD

**Issue by anonymitycoder2** [joernio/joern#3924]
**Describe the bug**
joern-slice cannot generate slices
![image](https://github.com/joernio/joern/assets/106904264/42388313-3ce5-4846-926c-8b297a916ac7)

joern seems to be able to parse the code, generating parsed files and cpg files. But cannot generate slices

**Desktop (please complete the following information):**
 - OS  Ubuntu 20.04
 - Joern Version 2.0.187
 - Java version JDK 19

Looking forward to your reply

**Comment by max-leuthaeuser** [comment]
I was able to reproduce this issue with the latest joern.
I searched the git log but did not find anything `circe` related.
@mpollmeier Any idea?

**Comment by anonymitycoder2** [comment]
> I was able to reproduce this issue with the latest joern. I searched the git log but did not find anything `circe` related other than #2980 in the last weeks. @mpollmeier Any idea?

Thank you for your reply. I also tried other versions of joern and JDK and the same problem occurred. can you tell me the version of os joern jdk you used when running successfully

**Comment by DavidBakerEffendi** [comment]
I'm still running into this issue on JDK 18. Looking at the build to see if there is something obvious, but this used to work, as I used this via CLI quite a bit when I created it.

**Comment by DavidBakerEffendi** [comment]
Ok it seems to work when I run Joern with Java 17 - could be limits around reflection or something

**Comment by max-leuthaeuser** [comment]
How tight are we coupled with circe there? Maybe we could replace it?

**Comment by DavidBakerEffendi** [comment]
I've identified the following modules using it:
* `io.joern.joerncli.JoernVectors`
* `io.joern.dataflowengineoss.slicing`
* `io.joern.gosrc2cpg.model.GoMod`
* `io.joern.gosrc2cpg.parser.GoAstJsonParser`

So I'd say we could probably replace it with `ujson` fairly easily - would also reduce the footprint of our classpath.

**Comment by mpollmeier** [comment]
Sorry for the silence, I was out sick (still not quite fit, slowly getting there though)
Yes that makes sense. I can do that tomorrow, unless @DavidBakerEffendi are you already on this?

**Comment by DavidBakerEffendi** [comment]
@mpollmeier Haven't started anything on my side, so feel free to go ahead. Welcome back, and hoping for a speedy recovery!

**Comment by mpollmeier** [comment]
I'm not against removing circe, but the quick fix is https://github.com/joernio/joern/pull/3978

**Comment by mpollmeier** [comment]
fixed in next release (2.0.197)

**Comment by mpollmeier** [comment]
and yes, there's now a test in the PR pipeline, so hopefully this won't crop up again
