### ISSUE TITLE
[javasrc2cpg]Does the ConfigFile node not support yaml or yml detection?

### ISSUE THREAD

**Issue by Coker-Cooler** [joernio/joern#3943]

**Comment by DavidBakerEffendi** [comment]
Configs are fairly language agnostic, we should perhaps consider an `x2cpg` pass with all general configs instead of re-inventing these passes in each frontend.

**Comment by tajobe** [comment]
> if there are some common Java frameworks where analysis could benefit from yaml files

FWIW, Spring Boot is one such framework where `application.properties` and `application.yaml` are roughly equal ([docs]), and having one but not the other in the cpg configFiles is unfortunate.

I also think that the current treatment of configs is a bit weird and should be made agnostic. There are many other missing formats/files that can make it difficult to rely on. `.conf`/`HOCON` files ([config],[ktor]), various xml configs ([JPA] `persistence.xml`/[hibernate]) are other such examples.

[docs]: https://docs.spring.io/spring-boot/docs/3.2.0/reference/html/features.html#features.external-config.files
[config]: https://github.com/lightbend/config
[ktor]: https://ktor.io/docs/configuration-file.html
[JPA]: https://docs.oracle.com/cd/E16439_01/doc.1013/e13981/cfgdepds005.htm
[hibernate]: https://docs.jboss.org/hibernate/orm/3.3/reference/en-US/html/session-configuration.html#configuration-xmlconfig
