### ISSUE TITLE
[Bug] [javasrc2cpg] Memory leak

### ISSUE THREAD

**Issue by xavierpinho** [joernio/joern#3953]
## Description

javasrc2cpg seems to have issues reclaiming memory back between scans. 

For instance, here's what it's memory usage looks like when running its unit-tests back-to-back 3 times:

<img width="1394" alt="before" src="https://github.com/joernio/joern/assets/3519109/cfe0e2f2-7469-4848-bcb0-3ac680eba84b">

This is problematic when using Joern as a library to run multiple scans, as memory usage will keep growing over time.

## Discussion

With a profiler, I traced this issue at least back to `JdkJarTypeSolver.addArchives` (and `registerPackagesForJar`). It seems that every time we repeat this process (of creating a new `JdkJarTypeSolver` with JDK jars) we are unable to reclaim a considerable chunk of memory back.

However, I couldn't figure out much past this point. I have my suspicions on `classPool`.

## A temporary workaround

I implemented a `JdkJarTypeSolver.fromJdkPath` cache, so that for each JDK path we build at most one `JdkJarTypeSolver`. It's discussable whether this is appropriate or not. For some use-cases, it certainly is safe to assume the JDK path contents won't change in between scans.

Repeating the same unit-tests back-to-back 3 times now yields the following graph:

<img width="1394" alt="after2" src="https://github.com/joernio/joern/assets/3519109/9a0207a8-1ad7-4afa-91b4-e5d8c157ff7f">

No changes in the tests' outcome. Even though this isn't a real fix, it's now much more manageable. 

Is this something worth of a PR? 

cc @johannescoetzee

**Comment by max-leuthaeuser** [comment]
@johannescoetzee is on vacation until 01/19/24.
So I think it's a good idea to simply go ahead and take your PR.
