### ISSUE TITLE
[Bug] - Can't find method node for method defined inside Anonymous object 

### ISSUE THREAD

**Issue by pandurangpatil** [joernio/joern#3967]
I am trying to query the CPG generated with the following sample.

```
var myObject = {
  property1: "Hello",
  property2: "World",

  // Function 1
  sayHello: function () {
    console.log(this.property1);
  },

  // Function 2
  sayWorld: function () {
    console.log(this.property2);
  },

  // Function 3
  sayHelloWorld: function () {
    console.log(this.property1 + " " + this.property2);
  }
};
```

`cpg.method("sayHello").l ` returns empty results.

**Comment by DavidBakerEffendi** [comment]
The entrypoint for these kinds of objects appears to be in `AstForExpressionsCreator.astForObjectExpression`, but anonymous classes generally appear under `AstForTypesCreator.astForTypeAlias`. 

I would presume that having this object be associated with an anonymous class be consistent with other cases where this happens. Any thoughts? @max-leuthaeuser

**Comment by max-leuthaeuser** [comment]
These functions are part of the CPG, just labeled as anonymous function. We could set their names based on the ObjectExpression property names afterwards.

**Comment by DavidBakerEffendi** [comment]
Then perhaps we go with the name setting thing for now, as a direct child to the parent context. May not be 100% correct naming strategy, but it should give the gist/be resolvable by the naive call graph linker.
