### ISSUE TITLE
[Bug] c2cpg "class" structure can not be correctly recognized as “type_decl” node

### ISSUE THREAD

**Issue by PoyoyoJia** [joernio/joern#4012]
**Describe the bug**
When I use Joern parse or c2cpg to parse C++source code, the "class" structure can not be correctly recognized as “type_decl” node, instead recognized as' unknown'.

**To Reproduce**
joern-parse {source code dir}
joern-export cpg.bin --repr=all --format=graphml --out=./.graphml

**Screenshots**
source code picture
<img width="326" alt="src" src="https://github.com/joernio/joern/assets/83326611/05681f87-d79f-4782-8882-0c54a2cbec52">
<img width="466" alt="export xml" src="https://github.com/joernio/joern/assets/83326611/62d2b8bb-e89e-476a-b501-88e20a37265d">

**Desktop (please complete the following information):**
 - OS windows 11
 - Joern Version 20.191
 - Java version jdk 19.02

**Comment by max-leuthaeuser** [comment]
May adding the correct includes helps?

Something like 
```
#include <chrono>
#include <iostream>

using namespace std;
```

**Comment by PoyoyoJia** [comment]
Here are some works I did, both the code and files are located had been uploaded "https://github.com/PoyoyoJia/SimpleParseDemo.git". 

## use class

the "class" structure can not be correctly recognized as “type_decl” node, instead recognized as' unknown'.

> file "use_class\\.graphml\\export.xml"
>
> - line 2642, node id 222, class Logger, incorrectly
> - line 4614, node id 392, class util_timer, incorrectly

## use struct

changing the keyword "class" to "struct", joern-parse can run correctly, but the "enum" inside the "struct" cannot be correctly parsed, but the declaration of the function in the ".h" file was incorrectly parsed

> file "use_struct\\.graphml\\export.xml"
>
> - line 1893, node id 153, struct Logger, correct
> - line 1934, node id 154, enum LogLevel, incorrectly
> - line 1954, node id 155, public: static Logger* getInstancePtr(), incorrectly
> - … the declaration of the function
> - line 5636, node id 486, struct util_timer, correct

## no header file

cancel the h file and use the cpp file instead, joern-parse can run all correctly, the "class" "enum" or the function\member in the class.

> file "no_header\\.graphml\\export.xml"
>
> - line 2642, node id 222, class Logger, correct
> - line 2710, node id 223, enum LogLevel, correct
> - line 4614, node id 392, class util_timer, correct

**Comment by max-leuthaeuser** [comment]
c2cpg guesses the language from the file extention, e.g. *.c -> C language, *.cpp -> C++.
For *.h we default to C, that's why you example fails.

**Comment by PoyoyoJia** [comment]
OK, thank you, bu is there any way to let *.h to be processed by C++?
