### ISSUE TITLE
Running joern-scan on Windows [Bug]

### ISSUE THREAD

**Issue by cssaheel** [joernio/joern#4015]
**Describe the bug**
Seems there is a problem when it comes to running joern-scan on Windows. I guess Windows use of '\\' instead of '/' messes up the path for joern-scan. Thanks in advance.

**To Reproduce**
C:\Users\user>joern-scan C:\Users\user\Joern\joern-cli\samples
executing C:\Users\user\AppData\Local\Temp\joern-bundle11256851351473129493\script.sc
-- Error: C:\Users\user\AppData\Local\Temp\scala-repl-pp-script-with-predef12807637217054419288.sc:239:44
239 | if (false || !workspace.projectExists("C:\Users\user\Joern\joern-cli\samples")) {
    |                                            ^
    |                          invalid character in unicode escape sequence
-- Error: C:\Users\user\AppData\Local\Temp\scala-repl-pp-script-with-predef12807637217054419288.sc:239:57
239 | if (false || !workspace.projectExists("C:\Users\user\Joern\joern-cli\samples")) {
    |                                                         ^
    |                                              invalid escape character
-- Error: C:\Users\user\AppData\Local\Temp\scala-repl-pp-script-with-predef12807637217054419288.sc:239:65
239 | if (false || !workspace.projectExists("C:\Users\user\Joern\joern-cli\samples")) {
    |                                                                 ^
    |                                              invalid escape character
-- Error: C:\Users\user\AppData\Local\Temp\scala-repl-pp-script-with-predef12807637217054419288.sc:239:77
239 | if (false || !workspace.projectExists("C:\Users\user\Joern\joern-cli\samples")) {
    |                                                                             ^
    |                                              invalid escape character
-- Error: C:\Users\user\AppData\Local\Temp\scala-repl-pp-script-with-predef12807637217054419288.sc:239:83
239 | if (false || !workspace.projectExists("C:\Users\user\Joern\joern-cli\samples")) {
    |                                                                                   ^
    |                                              invalid escape character
-- Error: C:\Users\user\AppData\Local\Temp\scala-repl-pp-script-with-predef12807637217054419288.sc:239:93
239 | if (false || !workspace.projectExists("C:\Users\user\Joern\joern-cli\samples")) {
    |                                                                                             ^
    |                                              invalid escape character
-- Error: C:\Users\user\AppData\Local\Temp\scala-repl-pp-script-with-predef12807637217054419288.sc:241:31
241 |   .filter(_.inputPath == "C:\Users\user\Joern\joern-cli\samples")
    |                               ^
    |                          invalid character in unicode escape sequence
-- Error: C:\Users\user\AppData\Local\Temp\scala-repl-pp-script-with-predef12807637217054419288.sc:241:44
241 |   .filter(_.inputPath == "C:\Users\user\Joern\joern-cli\samples")
    |                                            ^
    |                                            invalid escape character
-- Error: C:\Users\user\AppData\Local\Temp\scala-repl-pp-script-with-predef12807637217054419288.sc:241:52
241 |   .filter(_.inputPath == "C:\Users\user\Joern\joern-cli\samples")

**Comment by max-leuthaeuser** [comment]
Can you try putting it in triple quotes?
`C:\Users\user>joern-scan """C:\Users\user\Joern\joern-cli\samples"""`

**Comment by cssaheel** [comment]
I used the """ around the path, it gives me the message "The syntax of the command is incorrect."
While also using a single double-quotes around the path string leads to the same error.

**Comment by max-leuthaeuser** [comment]
I was able to reproduce this issue locally on my Windows machine.
@mpollmeier Definitely something we have to have a look at.
