### ISSUE TITLE
[Bug] DotNetAstGen binary gets killed instantly on MacOS

### ISSUE THREAD

**Issue by karan-batavia** [joernio/joern#4019]
**Describe the bug**
The `DotNetAstGen` binaries stored in `joern-cli/frontends/csharpsrc2cpg/bin/astgen` folder are segregated by operating systems. The `dotnetastgen-macos-arm` is terminated instantly on a ARM Mac, throwing an error code of 137. The tests fail with a RuntimeException defined in code. Strangely, the `dotnetastgen-macos` works perfectly fine on the same machine, but it is not picked up by default when running the tests.

**To Reproduce**
4. ..
5. See error

**Expected behavior**
The Ast for the tests should be generated and tests should execute.

**Screenshots**

**Desktop (please complete the following information):**
 - OS - MacOS
 -  Joern Version - latest
 - Java version - 20.x

**Additional context**

**Comment by karan-batavia** [comment]
cc: @pandurangpatil

**Comment by DavidBakerEffendi** [comment]
I've encountered this too, and I've found that the default terminal is usually simulating Intel (Rosetta mode). I've tried to look at cross-architecture builds for `dotnet` but with little success.

**Comment by DavidBakerEffendi** [comment]
Ok I looked into this and seems related to https://github.com/dotnet/runtime/issues/79267

Also, running `arch` confirms my terminal is in `arm64` mode, but it runs the `x64` build of DotNetAstGen just fine so probably no need to build both variants.
