### ISSUE TITLE
[Bug] C CPG generation doesn't handle local variable declarations involving _Generic correctly.

### ISSUE THREAD

**Issue by MyEyes** [joernio/joern#4032]
**Describe the bug**
I've attached an example file that illustrates the behaviour.
Local variables in methods that are declared with a statement involving _Generic aren't recognized as generic.

**To Reproduce**
Here's some C code that reproduces the issue.
```c
#define type_num(X) _Generic((X), \
              long double: 1, \
                  default: 0,  \
                    float: 2  \
              )
 
int test_generic(void)
{
    float x = 8.0;
    const float y = 3.375;
    int z = type_num(x);
    return z;
}
```
gcc compiles the above code without issue.
Loading the snippet into joern and checking the local variables will miss the declaration of `z`.

```
joern> cpg.method.name("test_generic").local.l
val res1: List[io.shiftleft.codepropertygraph.generated.nodes.Local] = List(
  Local(
    id = 181L,
    closureBindingId = None,
    code = "float x",
    columnNumber = Some(value = 11),
    dynamicTypeHintFullName = ArraySeq(),
    lineNumber = Some(value = 13),
    name = "x",
    order = 1,
    possibleTypes = ArraySeq(),
    typeFullName = "float"
  ),
  Local(
    id = 185L,
    closureBindingId = None,
    code = "const float y",
    columnNumber = Some(value = 17),
    dynamicTypeHintFullName = ArraySeq(),
    lineNumber = Some(value = 14),
    name = "y",
    order = 3,
    possibleTypes = ArraySeq(),
    typeFullName = "float"
  )
)

```

**Expected behavior**
In the example variable `z` should also be in the methods local list.

**Desktop :**
Linux archlinux 6.5.6-arch2-1
Joern Version: 2.0.132
Java version: openjdk 21 2023-09-19

**Comment by max-leuthaeuser** [comment]
`_Generic` is a C11 feature and our parser (Eclipse CDT 10.5.0) does not support that at all.
I am not sure if later CDT versions support it but until now there is nothing we can do I guess.

**Comment by MyEyes** [comment]
Thank you for the reply.
That's really unfortunate, since it breaks for example the container_of macro in the linux kernel.

Would it be possible to work around this to at least correctly detect the declaration of the local variable?

**Comment by max-leuthaeuser** [comment]
I am not sure, but I will have a look. I'll let you know about the progress here.
