### ISSUE TITLE
Move IdentifierToCall node pass logic inside AST Creation flow itself.

### ISSUE THREAD

**Issue by pandurangpatil** [joernio/joern#4057]
`IdentifierToCall` determines, after the AstCreation, if an identifier behaves like a parenthesis-less call, and if so, replaces that node with a similar call node. This is not ideal, as base passes may treat a node differently based on the type.

This issue suggests using the `PackageContext.packageTable.methodTableMap` given to the `AstCreator` to determine if an identifier shares a name with a known method, and immediately creates a call instead.

**Comment by pandurangpatil** [comment]
@DavidBakerEffendi add more details in this ticket

**Comment by DavidBakerEffendi** [comment]
Development at [dave/ruby/identifier-call-replacement](https://github.com/joernio/joern/tree/dave/ruby/identifier-call-replacement)

**Comment by khemrajrathore** [comment]
Tried verifying against -  https://github.com/pay-rails/pay/blob/master/app/controllers/pay/webhooks/braintree_controller.rb#L9
we have `verified_event`  identifier, which is basically a call to the method `verified_event`
cc - @DavidBakerEffendi @pandurangpatil
