### ISSUE TITLE
[Bug] Running ast gen failed?

### ISSUE THREAD

**Issue by chejn** [joernio/joern#4177]
**Describe the bug**
![image](https://github.com/joernio/joern/assets/41510168/371ddec3-507c-405d-bf9a-d456e1ac321d)
in Docker dev container - java

**Comment by max-leuthaeuser** [comment]
There might be something wrong with the docker container setup there.
@mpollmeier Who would be the right person to ask?

**Comment by mpollmeier** [comment]
Hmm, the docker dev container was a user contribution back in 2022...
https://github.com/joernio/joern/blob/master/.devcontainer/Dockerfile

We're building a few other images (see e.g. https://github.com/joernio/joern/actions/runs/7927654583/job/21644420193), can you give those a try?

**Comment by chejn** [comment]
> Hmm, the docker dev container was a user contribution back in 2022...
> 
> https://github.com/joernio/joern/blob/master/.devcontainer/Dockerfile
> 
> 
> 
> We're building a few other images (see e.g. https://github.com/joernio/joern/actions/runs/7927654583/job/21644420193), can you give those a try?
> 
> 
> 
> 

Sorry i didnt mean the joern container, i'm building and running inside a docker container.

**Comment by max-leuthaeuser** [comment]
How did you install the joern distribution in your docker container?
Something like this: https://github.com/joernio/joern/blob/master/ci/Dockerfile.alma?

**Comment by chejn** [comment]
> How did you install the joern distribution in your docker container?
> 
> Something like this: https://github.com/joernio/joern/blob/master/ci/Dockerfile.alma?

mkdir joern && cd joern # optional
curl -L "https://github.com/joernio/joern/releases/latest/download/joern-install.sh" -o joern-install.sh
chmod u+x joern-install.sh
./joern-install.sh --interactive


Just this

**Comment by chejn** [comment]
I'm now building from source in github codespaces and getting the same issue

**Comment by max-leuthaeuser** [comment]
I just downloaded https://github.com/joernio/joern/releases/latest/download/joern-cli.zip, unzipped it and ran ./joern. Importing js code just worked fine.

**Comment by chejn** [comment]
So importCode.jssrc.fromString appears to work
still not the cli, quite lost :(
![image](https://github.com/joernio/joern/assets/41510168/5cc7da66-dba1-4fac-b7bc-fbfd8efdd04c)

**Comment by chejn** [comment]
ok found the issue, it was cause i was passing a path to a file and not a dir.
