### ISSUE TITLE
Receiver is not mapped for given JS example.

### ISSUE THREAD

**Issue by pandurangpatil** [joernio/joern#4211]
```
importCode.javascript.fromString("""
     | function temp (product) {
     | return {
     |     event: 'productAddToCart',
     |     price: product.sale_price || product.base_price,
     |   }
     | }
     | """)
```
In the above sample, I was trying to get `product.sale_price` `fieldAccess` node with the query `cpg.fieldAccess.where(_.and(_.fieldIdentifier.canonicalName("sale_price"),_.receiver.isIdentifier.name("product"))).l`. Query returns an empty list.

With further analysis, this query also returns an empty list `cpg.fieldAccess.receiver.isIdentifier.name("product").l`

**Comment by max-leuthaeuser** [comment]
Field access are are dispatched statically and do not have a reciever.
To query `product` check `.argument(0)`.
