### ISSUE TITLE
[ruby] Conditional `raise`

### ISSUE THREAD

**Issue by DavidBakerEffendi** [joernio/joern#4269]
A warning has been emitted on the following structure suggesting this isn't handled yet.

```ruby
raise "#{email} doesn't exist!" if !(user)
```

Note the `if` statement at the end. This should be lowered as the following:
```ruby
if (!user)
  raise "#{email} doesn't exist!"
end
```
This lowering can simply be handled in the node creator stage

**Comment by AndreiDreyer** [comment]
@DavidBakerEffendi This test may have been fixed as a side effect of one of the other tickets. Not getting any warnings when running the basic test provided here, and the AST structure looks to be generated correctly.
Test:
![image](https://github.com/joernio/joern/assets/11736140/ba73c303-43a4-489e-9d6f-620ef18960d3)

AST:
![image](https://github.com/joernio/joern/assets/11736140/de4a3ea1-7c95-4f73-8093-6c8f6ba3001d)

**Comment by DavidBakerEffendi** [comment]
Hmm interesting, let me have a look deeper

**Comment by DavidBakerEffendi** [comment]
On railsgoat, one will see the warnings
```
2024-03-11 20:21:25.023 WARN AstCreator: Could not represent expression: if (Unknown) (app/controllers/admin_controller.rb), skipping
2024-03-11 20:21:25.026 WARN AstCreator: Could not represent expression: if (Unknown) (app/controllers/admin_controller.rb), skipping
2024-03-11 20:21:25.085 WARN AstCreator: Could not represent expression: if (Unknown) (app/models/user.rb), skipping
2024-03-11 20:21:25.085 WARN AstCreator: Could not represent expression: if (Unknown) (app/models/user.rb), skipping
```
I think this suggests the following
```ruby
class AdminController < ApplicationController
  before_action :administrative, if: :admin_param, except: [:get_user]
  skip_before_action :has_info
  layout false, only: [:get_all_users, :get_user]
# ....
```
and
```ruby
class User < ApplicationRecord
  validates :password, presence: true,
                       confirmation: true,
                       length: {within: 6..40},
                       on: :create,
                       if: :password
# ...
```
respectively

**Comment by DavidBakerEffendi** [comment]
I think the crux of this is that `if:` is being interpretted as a `IfStatement` but it should be interpreted in the same way as the other tokens of this type

**Comment by DavidBakerEffendi** [comment]
These appear to be method calls
