### ISSUE TITLE
[ruby] Boolean methods

### ISSUE THREAD

**Issue by AndreiDreyer** [joernio/joern#4336]
In Ruby you get boolean methods indicated with a `?` at the end of the function name:
e.g
```ruby
def boolFunc?
end
```
To make this work properly it might require some changes to the grammar, since `boolFunc?` is probably not a valid `SimpleIdentifier` under normal circumstances, so the `node.target` is being defaulted to an `Unknown()` node, which results in the call not being resolved.

Node:
![Image](https://github.com/joernio/joern/assets/11736140/31033101-5f26-4ce6-8c37-87c12160c01e)

Test code:
```
class Foo
  def somefunc?
    true
  end

  def bar
    if somefunc?
      puts "baz"
    end
  end
end
```

**Comment by xavierpinho** [comment]
I think what's missing is a visitor for `methodOnlyIdentifier` contexts, i.e.

```scala
override def visitMethodOnlyIdentifier(ctx: RubyParser.MethodOnlyIdentifierContext): RubyNode = {
  SimpleIdentifier(None)(ctx.toTextSpan)
}
```

because in `visitMethodCallExpression` we are visiting `ctx.methodOnlyIdentifier` (to extract the target of the `SimpleCall`) which, by default, gets you an `Unknown` cf. `defaultResult()`.
