### ISSUE TITLE
[ruby] `UnlessStatement` inside `if` expr

### ISSUE THREAD

**Issue by AndreiDreyer** [joernio/joern#4337]
```ruby
def foo
  if 1 < 2
    "somestring" unless 1 < 2
  end
end
```
throws: `[WARN ] Could not represent expression: "somestring" unless 1 < 2 (UnlessExpression) (Test0.rb), skipping`. Strange that this only happens when the `UnlessExpression` is inside the if statement. The following runs fine:
```ruby
def foo
  "somestring" unless 1 < 2
end
```

**Comment by xavierpinho** [comment]
The root cause is that we presently don't handle `UnlessExpression` in `astForExpression`. So far, only statements handle `UnlessExpression`s cf. `astForUnlessStatement`.
