### ISSUE TITLE
[C#]:ERROR DotNetAstGenRunner:  - running dotnetastgen failed!

### ISSUE THREAD

**Issue by chengkenyong** [joernio/joern#4392]
"When I use Joern to traverse a web form project in C#, the console prompts the following issue. How can I resolve it?"
![QQ截图20240325164743](https://github.com/joernio/joern/assets/82140257/a3025868-9077-43c8-948f-ddf685d42097)
![QQ截图20240325171730](https://github.com/joernio/joern/assets/82140257/65e2cd2b-9106-47c5-b660-d5cc68e8c8db)

**Comment by DavidBakerEffendi** [comment]
@tuxology Are you able to reproduce something like this? It seems like it appears on Windows

**Comment by DavidBakerEffendi** [comment]
@chengkenyong Please let us know what project you tried to import or how we can reproduce this, as well as which version of Joern you're using? C# is currently in an alpha state

**Comment by chengkenyong** [comment]
sample project:
[https://github.com/chengkenyong/web-Application](url)

Okay, I just simulated a simple ASP.Net Web Form project, Upon examining the log information, it seems that all files ending with ". cs" have been parsed, but only four nodes have been generated. 
![QQ截图20240326161316](https://github.com/joernio/joern/assets/82140257/10eba1a5-a873-4e82-ae9f-c621184b1680)
![QQ截图20240326161357](https://github.com/joernio/joern/assets/82140257/77fd1680-d610-47d3-ad3f-da74512dc5c5)

Desktop (please complete the following information):

Win 11
Joern 2.0.306
