### ISSUE TITLE
[PHP] Support for PHP Composer Autoload for type resolution help

### ISSUE THREAD

**Issue by tuxology** [joernio/joern#4403]
**Is your feature request related to a problem? Please describe.**
The PHP frontend caters to very decent type resolution and the nature of PHP makes it manageable. For example:

```php
use Acme\Blog\Comment

$comment = new Comment('<h1>Hello</h1>');
echo $comment->getComment();
```

However, when Composer is used, we often see that autoload is the preferred way to manage class loading (ref. https://getcomposer.org/doc/01-basic-usage.md#autoloading). This is mose widely used in conjunction with PSR4 Autoloader (ref. https://www.php-fig.org/psr/psr-4/). In absence of external files code, we possibly miss generating fully qualified types for external/internal packages that use autoload. 

A common way this is used is as follows:

```php
// Include Composer's autoloader
require 'vendor/autoload.php';

use Segment\Client;
use MyParcelNL\Sdk\src\Model\Recipient;
// use Aws\S3\S3Client;
// use PayPalCheckoutSdk\Core\PayPalHttpClient;
// use PayPalCheckoutSdk\Core\SandboxEnvironment;

// segmentio/analytics-php
// aws/aws-sdk-php
// paypal/paypal-checkout-sdk

// Initialize Segment client
$segment = new Client([
    "writeKey" => "YOUR_SEGMENT_WRITE_KEY"
]);

// Initialize AWS S3 client
$s3 = new S3Client([
    'version' => 'latest',
    'region'  => 'us-east-1',
    'credentials' => [
        'key'    => 'YOUR_AWS_ACCESS_KEY_ID',
        'secret' => 'YOUR_AWS_SECRET_ACCESS_KEY',
    ]
]);
```

In case above, in absence of `use Aws\S3\S3Client;` we won't get typeFullName of `s3` since this is autoloaded. 

**Describe the solution you'd like**
It may be possible to fetch external vendor code (or it may already exist) first. Once this is available, we may be able to get the types already in the CPG without much issues, However, `composer.json` can also specify the mapping of class like this: https://github.com/wikimedia/mediawiki/blob/master/composer.json#L134 so we may need to parse this as well

**Comment by DavidBakerEffendi** [comment]
As per our discussion offline, it appears we can get the type recovery pass to play nicely by adding the autoloaded entities to an `ImportNode`, which we can discover in the `composer.json` (and is what I think will be the best way forward, as to not depend on building the code)

**Comment by DavidBakerEffendi** [comment]
This [AWS example](https://github.com/aws-samples/aws-php-sample/tree/master) shows nicely that anything under `require` could be autoloaded.

**Comment by DavidBakerEffendi** [comment]
Development is here https://github.com/joernio/joern/tree/dave/php/dependency-download

**Comment by DavidBakerEffendi** [comment]
Note to self: We may want to use this to parse the dependencies for types: https://github.com/hugowetterberg/php-class-parser
