### ISSUE TITLE
[Question] How to update the properties of node and apply to Cpg

### ISSUE THREAD

**Issue by d1tto** [joernio/joern#4445]
I want to add a new property to Cpg node or modify an existing property, such as modifying the `isExternal` of `Method` node, and apply the modified information to Cpg, and can be persisted (serialization).  I'm not familiar with overflowdb. if this is feasible and how to do it. Thanks!

**Comment by max-leuthaeuser** [comment]
Yes, see e.g., https://github.com/joernio/joern/blob/master/joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/ConstClosurePass.scala#L80

**Comment by d1tto** [comment]
Thanks! it helps me
