### ISSUE TITLE
Error: Could not create the Java Virtual Machine.

### ISSUE THREAD

**Issue by chengkenyong** [joernio/joern#4449]
The error message I encounter when running the ./joern command is as follows. How can I resolve this?
![微信截图_20240415094418](https://github.com/joernio/joern/assets/82140257/b2a2d9cd-460e-46bb-aacb-53dc061aced9)

joern-cli:v2.0.330

**Comment by max-leuthaeuser** [comment]
This has been fixed with https://github.com/joernio/joern/pull/4667
