### ISSUE TITLE
Extending the CPG

### ISSUE THREAD

**Issue by JannisB87** [joernio/joern#4454]
Hello, I am currently trying to write a plugin, following the directions provided [here](https://github.com/joernio/sample-plugin). Specifically, I want to extend the CPG with a new edge type and a single property for all nodes of types 'Identifier' and 'Local'.

Unfortunately for me, it is not quite clear from the tutorial, how I need to proceed. Should I create an entirely new graph as outlined in the tutorial? How would I create back references to the AST? Ideally I'd simply want to extend the existing AST by said edge type and property, however adding new edges and trying to insert them into the AST leaves me with the following runtime exception:

`java.lang.RuntimeException: Edge with type='TEST_EDGE' with direction='OUT' not supported by nodeType='IDENTIFIER'`

So clearly this is not the intended way of doing this. Can anyone point me in the right direction, how I can achieve this? Thank you very much!

**Comment by JannisB87** [comment]
Nevermind, I figured it out: You can simply access and extend the individual graphs through the CpgSchema as shown the example.

**Comment by d1tto** [comment]
@JannisB87 I meet the same problem, can you give more detailed examples? Thanks
