### ISSUE TITLE
[Bug] Parallel queries/traversals against CPG take just as long as sequential

### ISSUE THREAD

**Issue by tajobe** [joernio/joern#4471]
**Describe the bug**

My understanding is that while a CPG cannot be written to by multiple threads, it should be query-able in parallel. While queries do execute, they take just as long as in sequence as if there's some synchronization or locking.

**To Reproduce**
Using some CPG large enough to take measurable time to perform some work, eg a Java CPG from https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/javav2/example_code/, run several long tasks in parallel and compare to sequential, eg `reachableBy`s:
```scala
joern> import java.util.concurrent.TimeUnit
     | import scala.collection.parallel.CollectionConverters.ImmutableIterableIsParallelizable
     | import scala.concurrent.duration.Duration

joern> def duration[R](block: => R): Duration = {
     |   val tStart = System.currentTimeMillis
     |   block
     |   val tEnd = System.currentTimeMillis()
     |   Duration(tEnd - tStart, TimeUnit.MILLISECONDS)
     | }
def duration[R](block: => R): scala.concurrent.duration.Duration

joern> duration { 1.until(10).par.foreach(cpg.call.reachableBy(cpg.literal).l) }
val res14: scala.concurrent.duration.Duration = 10423 milliseconds

joern> duration { 1.until(10).par.foreach(cpg.call.reachableBy(cpg.literal).l) }
val res15: scala.concurrent.duration.Duration = 10439 milliseconds

joern> duration { 1.until(10).foreach(cpg.call.reachableBy(cpg.literal).l) }
val res16: scala.concurrent.duration.Duration = 10358 milliseconds

joern> duration { 1.until(10).foreach(cpg.call.reachableBy(cpg.literal).l) }
val res17: scala.concurrent.duration.Duration = 10523 milliseconds
```
The work here is somewhat nonsensical, but the goal is just something that takes enough time to measure significant differences.
The duration of a normal/sequential foreach and a `par` parallel foreach are basically the same.

**Expected behavior**
The queries running in parallel should complete noticeably quicker than the sequential queries.

**Screenshots**
See snippet above

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.2.1
 - Joern Version: 2.0.333
 - Java version: 17.0.9

**Additional context**
`par` sanity check:
```scala
joern> duration { 1.until(10).map{it=>Thread.sleep(1000);it} }
val res18: scala.concurrent.duration.Duration = 9035 milliseconds

joern> duration { 1.until(10).par.map{it=>Thread.sleep(1000);it} }
val res19: scala.concurrent.duration.Duration = 1006 milliseconds
```

**Comment by DavidBakerEffendi** [comment]
Hi @tajobe. `reachableBy` is already a process that runs in parallel, and uses dynamic programing (however the cache isn't shared between `reachableBy` queries.

**Comment by mpollmeier** [comment]
These results are indeed surprising. 

To remove the dataflowengine out of the picture I changed the cpg query to just lookup all nodes and traverse to all neighbors: `cpg.all.out.l`, but the results were still the same between parallel and sequential:

```scala
joern> duration { 1.until(10).foreach { cpg.all.out.l } }
val res14: scala.concurrent.duration.Duration = 368 milliseconds

joern> duration { 1.until(10).par.foreach { cpg.all.out.l } }
val res15: scala.concurrent.duration.Duration = 349 milliseconds
```

I then added some println debug, and :tada: that changed things entirely:
```scala
joern> duration { 1.until(10).foreach { i =>
     |   println(s"START $i")
     |   cpg.all.out.l
     |   println(s"END $i")
     | }}
     |
START 1
END 1
START 2
END 2
START 3
END 3
START 4
END 4
START 5
END 5
START 6
END 6
START 7
END 7
START 8
END 8
START 9
END 9
val res18: scala.concurrent.duration.Duration = 3088 milliseconds

joern> duration { 1.until(10).par.foreach { i =>
     |   println(s"START $i")
     |   cpg.all.out.l
     |   println(s"END $i")
     | }}
     |
START 1
START 2
START 3
START 4
START 7
START 5
START 6
START 8
START 9
END 9
END 1
END 6
END 5
END 3
END 7
END 8
END 2
END 4
val res19: scala.concurrent.duration.Duration = 593 milliseconds
```

My best guess is that the JVM's JIT is performing some ad-hoc improvement magic here...

**Comment by max-leuthaeuser** [comment]
These micro-benchmarks on the JVM using `System.currentTimeMillis` hardly result in any useful insights. See: https://jenkov.com/tutorials/java-performance/jmh.html#why-are-java-microbenchmarks-hard and https://develotters.com/posts/how-not-to-measure-elapsed-time/.

You ideally want to do this with JHM (https://openjdk.org/projects/code-tools/jmh/) and `System.nanoTime()` to ensure all benchmarks were performed with JVM pre-warming and multiple runs to automatically eliminate noise due to JIT compilation, garbage collection or undesired heap allocation patterns, and not use "wall-clock" time.

**Comment by fabsx00** [comment]
Thanks, @max-leuthaeuser. Closing for now.

**Comment by tajobe** [comment]
@DavidBakerEffendi I'm not sure if I understood correctly--Are you saying this seems like a bug in reachablyBy (different reachableBys in parallel do not seem to actually run in parallel) or that this is somewhat expected?

---

@mpollmeier
> My best guess is that the JVM's JIT is performing some ad-hoc improvement magic here...

For clarity, I am seeing this in compiled code referencing joern as a library, I was trying to get a simple reproduction for an issue here and eliminate our internal code as a source of locking. We have a bunch of "parsers" each looking for information in the CPG and performing `reachableBy`s to find the literal/call sources of certain arguments. Having these all run in parallel produces no detectable benefit (and the time taken is dominated by the `reachableBy`s), where we might take 10s * 6 parser, or in parallel 60 seconds.

---

@max-leuthaeuser Sure...my goal here wasn't benchmarking but rather reproducing/reporting an issue I was consistently seeing in some more more complicated, joern-standalone code usage. I suspect if there were JMH benhcmarks for parallel reachableBys you would similarly see a lack of performance improvements vs sequential, but I can try to get a reproduction in some JMH benchmarks at some point.

**Comment by DavidBakerEffendi** [comment]
@tajobe Rather, I was trying to reason why this could happen, but each call to `reachableBy` creates a new `Engine` object which has its own thread pool and doesn't share them, where sharing would at least explain some component of this.
