### ISSUE TITLE
Java out of memory error - java heap space

### ISSUE THREAD

**Issue by sameeshem** [joernio/joern#4486]
Hi Team,

I have started using Joern for binary analysis purpose using import code. ghidra and I am facing a java heap out of memory error while loading large executables. I tried increasing my heap space to extra 2 GB and couldn’t come out of this error. Can you please help with some guidance ?

thanks
Sameesh

**Comment by DavidBakerEffendi** [comment]
Closnig this for now, re-open if this is still an issue @sameeshem
