### ISSUE TITLE
[Bug] Is it right to link TYPE_DECL to TYPE (only) for type hierarchy

### ISSUE THREAD

**Issue by FFengIll** [joernio/joern#4487]
**Describe the bug**
I see the pass in x2cpg do type hierarchy, but it links TYPE_DECL to TYPE only.
Is it right?
How about TYPE_DECL to TYPE_DECL?

**To Reproduce**
code bellow

https://github.com/joernio/joern/blob/262c4cf7f021715d81f66ba303abfc6c15786d1c/joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/typerelations/TypeHierarchyPass.scala#L14-L28

**Comment by maltek** [comment]
Type nodes are linked to TypeDecl nodes via `referencedTypeDecl`.

If you don't want to manually type e.g. `baseType.referencedTypeDecl`, there are DSL steps on TypeDecl for this: `{derived,base}TypeDecl[Transitive]`

**Comment by FFengIll** [comment]
@maltek I believe the question is about `Hierarchy Pass Implementation`, not ref.
Do you have any clues for it?

**Comment by maltek** [comment]
What I'm saying is that since there are edges typedecl --inherits_from--> type and type --ref--> typedecl, all the info is in the graph. There is no need for any additional edges.
