### ISSUE TITLE
[JavaSrc2Cpg] - Missing type information, in case of templated object

### ISSUE THREAD

**Issue by khemrajrathore** [joernio/joern#4488]
**Is your feature request related to a problem? Please describe.**
We see missing type information in scenarios when there is usage of templated objects, 
Ex- `List<String> user`
In this case we get the type as `java.util.List`

**Describe the solution you'd like**
The type information should also show `String`, representing the true value of type

Ideally the same applies to Kotlin and languages where this holds true

**Additional context**
For the below code
```
import java.util.ArrayList;
import java.util.List;

public class Main {
    public static void main(String[] args) {
        // Create a List of Strings
        List<String> stringList = new ArrayList<>();

        // Add some elements to the list
        stringList.add("Hello");
        stringList.add("World");
        stringList.add("!");

        // Print the elements of the list
        System.out.println("Elements of the List:");
        for (String str : stringList) {
            System.out.println(str);
        }
    }
}

```
The type of `stringList` should have info of both `List` and `String` in typeFullName

**Comment by DavidBakerEffendi** [comment]
@khemrajrathore by templated objects don't you mean generic types?

**Comment by DavidBakerEffendi** [comment]
In any case, this may refer to this PR that was de-prioritized https://github.com/joernio/joern/pull/2655
