### ISSUE TITLE
[java] Add config files to the CPG

### ISSUE THREAD

**Issue by itsacoderepo** [joernio/joern#4505]
After importing a war file in joern (v2.0.349), i was not able to query the containing `web.xml` file, via `cpg.configFile.l`. 

Adding such files would improve the frontenend and one would not need to switch to the javasrc frontend and placing the web.xml into the directory.

**Comment by DavidBakerEffendi** [comment]
Ah, good point. Let me have a look at this

**Comment by DavidBakerEffendi** [comment]
@itsacoderepo Is there a last known version where this worked? The last `jimple2cpg` related changes were Soot upgrade and zip file validation, but way before that there were changes to how these archives were unpacked so it may be more related to the latter.
