### ISSUE TITLE
[ruby] Parenthesis-less Calls with `&.` Parser Rule Missing

### ISSUE THREAD

**Issue by DavidBakerEffendi** [joernio/joern#4533]
Below shows an example of the code
```ruby
class Foo
  def bar(arg)
    return arg
  end
end

foo = Foo.new
foo&.bar x # <-- no call, only `foo` identifier detected
```
What is interesting is that `foo&.bar(x)` works. So the parser rule for simply expecting the argument list does not include the way the call member is accessed. 

Might be worth determining if this is valid syntax before solving.

**Comment by AndreiDreyer** [comment]
Fixed as part of #4720
