### ISSUE TITLE
How to Perform Backward Slicing with Joern for Java Code Without Compiling the Project?

### ISSUE THREAD

**Issue by ramsey-coding** [joernio/joern#4561]
**Description**

I am working with a Java codebase and I need to perform backward slicing to analyze data dependencies and control flow. However, I am facing a challenge because I want to perform this analysis without having to compile the entire project.

**Questions**
- Is it possible to perform backward slicing on Java code using Joern without compiling the project?
- If so, what are the steps or configurations required to achieve this?
- Are there any specific prerequisites or considerations to keep in mind while performing this analysis on non-compiled Java code?

**Expected Outcome**
- I expect to be able to perform backward slicing on the Java source code to trace the dependencies and control flow without needing to compile the project. Any guidance or examples on how to achieve this would be greatly appreciated.

**Comment by ramsey-coding** [comment]
Why are these tools discontinued? :-(
https://joern.readthedocs.io/en/latest/joerntools/slice.html

**Comment by ramsey-coding** [comment]
I see similar question here: https://github.com/joernio/joern/issues/2105

**Comment by ramsey-coding** [comment]
@xavierpinho @DavidBakerEffendi can you please help?

**Comment by DavidBakerEffendi** [comment]
See https://docs.joern.io/cpg-slicing/

**Comment by ramsey-coding** [comment]
@DavidBakerEffendi do I have to provide access to?

1. the complete project or can it handle a single java class
2. can it do interprocedutal analysis?

**Comment by qlbdsc** [comment]
hi @ramsey-coding, sorry for bother you, have you found a method to generate the interprocedual backward slice? thanks

**Comment by ramsey-coding** [comment]
Nope, this tool just does not work.

**Comment by qlbdsc** [comment]
thanks for your reply. BTW, do you know how to Perform Backward Slicing with Joern for Java Code if I have compiled the project

**Comment by DavidBakerEffendi** [comment]
For best control, I recommend creating a Joern-based application using: https://github.com/joernio/standalone-ext
Then the step you need to traverse backwards via the data-flow graph is `.ddgIn`. This is similar to how one achieves this in `joern-slice`, but slicing for all variables in the way `joern-slice` does is expensive so rather use the template above to gain fine-grained control over what you need.

**Comment by DavidBakerEffendi** [comment]
> thanks for your reply. BTW, do you know how to Perform Backward Slicing with Joern for Java Code if I have compiled the project

Use the `jimple2cpg` frontend for this. It is not perfect (i.e., traps aren't supported too well) but it will model most structures.

**Comment by qlbdsc** [comment]
Thanks very much!
