### ISSUE TITLE
[Bug] Error trying to run joern on Windows after install

### ISSUE THREAD

**Issue by antongonz** [joernio/joern#4661]
Hello,

I downloaded the latest version of joern and installed JDK 22. When running joern I get this error:

`
joern-cli>joern
Improperly specified VM option 'CompressedClassSpaceSize=128m=-Dlog4j.configurationFile=C:\joern-cli\conf\log4j2.xml'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
`

I also tried using JDK17 but received the same error. How can I fix this?

Thanks!

**Comment by mpollmeier** [comment]
windows isn't really our primary platform, sorry :)
will be fixed via https://github.com/joernio/joern/pull/4667

**Comment by mpollmeier** [comment]
thanks for reporting!

**Comment by mpollmeier** [comment]
@antongonz would you mind double checking with the latest joern, e.g. https://github.com/joernio/joern/releases/tag/v2.0.409 ?
