### ISSUE TITLE
[Bug] In JS for call node additional structure getting generated

### ISSUE THREAD

**Issue by dbMundada** [joernio/joern#4662]
**Describe the bug**
Code Snippet:
`res.status(400)`
 for this JS code snippet we are getting graph structure added in screenshots

For above example graph has additional nodes
```
(<operator>.fieldAccess,res.status)
(IDENTIFIER,res,res.status(400))
(FIELD_IDENTIFIER,status,status)
```

**To Reproduce**
Simple import above code in joern.

**Expected behavior**
Should only create Call node, Identifier node & Liternal node.

**Screenshots**

![Image](https://github.com/joernio/joern/assets/5364736/4ad0c348-d682-4e01-95d5-34856af1b6ab)

**Desktop (please complete the following information):**
 - OS:  Mac
 - Joern Version : 2.0.305
 - Java version : 18.0.2.1

**Additional context**

**Comment by DavidBakerEffendi** [comment]
This is expected, the one is the `base` and the other is the `receiver`. One can observe a similar structure in Python where the receiver is `argIdx=-1` and the "self" variable is `argIdx=0`.

This is to largely model dynamic languages' approach to importing and dispatching calls, where defined calls are attached to the module as a property, and then that property (method ref) is retrieved and then dispatched.
