### ISSUE TITLE
Release builds are broken, sonatype credentials change required

### ISSUE THREAD

**Issue by mpollmeier** [joernio/joern#4669]
As of today we sonatype doesn't allow to authenticate using the main username/password any longer, instead we need to use a token. 
Can you please log into https://s01.oss.sonatype.org/ with the joern-io user, open `profile` (from the dropdown on the top right) and grab the username/password from there. Then, change the credentials for github actions secrets for the entire joern organization to those new tokens (i.e. `SONATYPE_USERNAME` and `SONATYPE_PASSWORD`). 

More context: https://central.sonatype.org/publish/generate-token/

https://github.com/joernio/joern/actions/workflows/release.yml

**Comment by fabsx00** [comment]
Ok, done.

**Comment by mpollmeier** [comment]
works, thanks!
