### ISSUE TITLE
Anyway to transfer a code graph back to source code (string) format?

### ISSUE THREAD

**Issue by HarrialX** [joernio/joern#467]
Hi Dear Authors, I'm curious whether there's some way in Joern or other tools that can transfer a parsed code property graph back. 

I understand that "code property graph" may not be an official name such as AST, CFG, etc, it is a mixture of them. Therefore, for programming languages like C/C++, is there any way to:
(1) transfer the single AST, or CFG back to the original code?
(2) transfer the mixture of AST, CFG, etc (then this is code property graph in this mixing case) back to the original code?

**Comment by NikolasBielski** [comment]
I'm also interested if there is a reply for this?

**Comment by fabsx00** [comment]
I think you're looking for something like this? https://docs.joern.io/exporting
