### ISSUE TITLE
[C#]:Type recovery and data flow completion in CPG

### ISSUE THREAD

**Issue by chengkenyong** [joernio/joern#4674]
When I use joern to scan C# projects, I encountered several issues:

1. For nodes of type 'fieldAccess', it cannot determine the type of the node. Additionally, there are occasional missing properties for other types of nodes.
![微信截图_20240618135636](https://github.com/joernio/joern/assets/82140257/f6324765-16f8-4365-8481-d3f712dde5e8)
![微信截图_20240618135942](https://github.com/joernio/joern/assets/82140257/91f228c1-0377-4d4a-bb3b-cfa14730ad75)
2. Joern seems to miss scanning content within Object Initializer (or anonymous method bodies) in C#.
![微信截图_20240618143512](https://github.com/joernio/joern/assets/82140257/1dd211a7-f0ef-4938-8ce4-2e2995c9e14c)
![微信截图_20240618142953](https://github.com/joernio/joern/assets/82140257/450c78b1-83af-4214-a941-c144f416742f)
3. There are instances where data flow is incomplete in certain nodes.
![微信截图_20240614162500](https://github.com/joernio/joern/assets/82140257/92a89fe1-5813-40df-bf57-8595e7f03c86)
I am particularly interested in understanding the principles behind attribute recovery, node recovery, and data flow completion. I would like to contribute to addressing these issues and hope you can provide me with guidance in this area. I understand you may be busy, but I sincerely hope you can offer me some relevant advice. I am committed to making a meaningful contribution. Thank you.

**Comment by DavidBakerEffendi** [comment]
Hi @chengkenyong, development of C# frontend has been largely funded by Privado, but they have since scaled it back a bit due to priorities on other languages. The C# frontend relies on two components (1) the Roslyn parser wrapped in a neat binary which can be found here https://github.com/joernio/DotNetAstGen, and (2) the AstCreation in Joern.

For the missing AST features you've described, it could be that they need to be filtered in on the parser. So that change would be in DotNetAstGen. One way to check is to create a JSON AST dump of the file you're interested in, and see if it is present. 

If the entity is there, then it probably needs a handler in one of the classes within the `astcreation` package in csharpsrc2cpg. 

Regarding type information, it is not uncommon for `fieldAccess` nodes to not have type info, especially if the receiver is an object, since this might have multiple types in the case of polymorphism. This may require a bit more of a "dynamic" query that looks at the `fieldAccess.argument(1).evalType.baseTypeDeclTransitive` step to find all possible types, and then determine which of those types have members matching the `canonicalName` of the `fieldIdentifier`.

**Comment by chengkenyong** [comment]
Hi @DavidBakerEffendi , Your explanation has been very helpful to me, and I will follow your advice to learn more about the relevant topics. Thank you for your assistance.

**Comment by chengkenyong** [comment]
Hi @DavidBakerEffendi ，Based on your suggestion, I have restored the missing type of the fieldAccess node to the desired state in the first case. However, I am still unclear about how to address the third case of missing data flow. Specifically, I want to restore the data flow in the third case where the variable childSqlMapSource cannot reach sqlMapPath through the foreach loop. Could you please provide me with some more advice on how to achieve this? Thank you!

**Comment by DavidBakerEffendi** [comment]
Hi @chengkenyong, congrats! So the simplest would be to have a look at how `javasrc2cpg` tests a similar structure, and to check using something like `dotAst`/`dotCfg`/`dotDdg` to determine what the differences are. My guess is, usually the equivalent data-flow is supported in Java, but that the resulting AST in C# might be a bit off and need adjusting in order to produce the same CFG/DDG that will eventually give you your flow. If your finding isn't obvious, feel free to post the comparison in this thread and I can continue to guide you

**Comment by chengkenyong** [comment]
Hi @DavidBakerEffendi, I'm sorry for the delay in responding lately as I had some things to handle! Since Java doesn't have the same "foreach" structure as in C#, I compared "for" and "foreach" loops using dotDdg and dotAst in C# as you suggested. 
![微信截图_20240711151637](https://github.com/joernio/joern/assets/82140257/1850533c-a609-4bec-b1a5-a9a84dae36a9)
![微信截图_20240711151708](https://github.com/joernio/joern/assets/82140257/6802e50e-70bb-4b62-ac37-a78de3455d27)
I found that in dotAst, both loops appear quite similar,
![dotAst](https://github.com/joernio/joern/assets/82140257/77c17cc2-a8bb-456c-b784-5ccc2ec3bb8f)
![dotAst_2](https://github.com/joernio/joern/assets/82140257/590023cd-50e2-4a2b-86a7-7772c733046d)
 but in dotDdg, it seems that there's a missing edge in the foreach loop,
![dotDdg_2](https://github.com/joernio/joern/assets/82140257/5700e790-d700-45ed-b11c-75dd97a49856)
![dotDdg](https://github.com/joernio/joern/assets/82140257/55630094-92bf-44da-9c84-656854f15ff0)
 which results in a lack of data flow from the identifier 'numbers' to the call 'WriteLine'.
![微信截图_20240711153226](https://github.com/joernio/joern/assets/82140257/21680993-05b9-4fd8-a01d-ecc3e572af4d)
![微信截图_20240711153326](https://github.com/joernio/joern/assets/82140257/3387f026-459c-430c-b407-b5f4e58c984b)

**Comment by DavidBakerEffendi** [comment]
@chengkenyong  Thanks for the info! This should put me in the right direction. Will have a look into it when I get some more bandwidth (most likely early next week)

**Comment by chengkenyong** [comment]
@DavidBakerEffendi When using the C# engine, I have encountered many cases where data flow becomes confused due to the use of the this identifier. To address this issue, I would like to understand the implementation logic for ensuring that two nodes have a data flow and how to add edges accordingly. However, I am currently unable to locate the specific implementation of this logic. Therefore, I am seeking your help.

**Comment by chengkenyong** [comment]
Hi @DavidBakerEffendi  ,When using the C# engine, I have encountered many cases where data flow becomes confused due to the use of the this identifier. To address this issue, I would like to understand the implementation logic for ensuring that two nodes have a data flow and how to add edges accordingly. However, I am currently unable to locate the specific implementation of this logic. Therefore, I am seeking your help.

**Comment by DavidBakerEffendi** [comment]
Sorry for the delay, back from vacation and picking up a bunch of work that's been waiting around. Will get back on this

**Comment by chengkenyong** [comment]
Hi! @DavidBakerEffend，I would be immensely grateful if you could respond to my message at your convenience. In the meantime, I have studied some of Joern's implementation logic and have done some simple work, including restoring some structure types and data flows. I will submit the relevant modifications once I have organized everything.

**Comment by chengkenyong** [comment]
It seems that the C# engine hasn't implemented special handling for polymorphism. For example, in the following code snippet, the methodFullName property of the method invocation node for a.Display() is still assigned the value IA.Display:void(). This causes an issue where it cannot correspond to the fullName of the Display method in class B (B.Display:void()), making it impossible to establish the edge from the callInvoke node in a.Display() to the methodDecl node for the Display method in class B.
![微信截图_20240816143014](https://github.com/user-attachments/assets/530bee58-b6e3-4986-93ad-ba2d9161cc55)

**Comment by DavidBakerEffendi** [comment]
Hi @chengkenyong, finally got around to it, but this should fix the missing flow in `foreach` https://github.com/joernio/joern/pull/4877

**Comment by chengkenyong** [comment]
Hi!  @DavidBakerEffendi ,Thank you very much for solving my problem! Actually, I also made some rough modifications to the foreach beforehand. The specific modifications are as follows. 
```scala 
  private def astForForEachStatement(forEachStmt: DotNetNodeInfo): Seq[Ast] = {
    val forEachNode     = controlStructureNode(forEachStmt, ControlStructureTypes.FOR, forEachStmt.code)
    val iterableAst     = astForNode(forEachStmt.json(ParserKeys.Expression))

    // ----------------------------------Add the foreach iterator variable to the previous scope-------------------------------------
    val identifierValue = forEachStmt.json(ParserKeys.Identifier)(ParserKeys.Value).str
    val _localNode =
      localNode(
        node = createDotNetNodeInfo(forEachStmt.json(ParserKeys.Type)),
        name = identifierValue,
        code = identifierValue,
        typeFullName = nodeTypeFullName(createDotNetNodeInfo(forEachStmt.json(ParserKeys.Type)))
      )
    scope.addToScope(identifierValue, _localNode)
    // -----------------------------------------------------------------------------------------------------------------

    val forEachBlockAst = astForBlock(createDotNetNodeInfo(forEachStmt.json(ParserKeys.Statement)))

    val _identifierNode =
      identifierNode(
        node = createDotNetNodeInfo(forEachStmt.json(ParserKeys.Type)),
        name = identifierValue,
        code = identifierValue,
        typeFullName = nodeTypeFullName(createDotNetNodeInfo(forEachStmt.json(ParserKeys.Type)))
      )
    val iteratorVarAst = Ast(_identifierNode)

    // ------------------------------------------ Define a custom "in" operator--------------------------------------------------
    val args         = iteratorVarAst +: iterableAst
    val iterableCode = forEachStmt.json(ParserKeys.Expression)(ParserKeys.MetaData)(ParserKeys.Code).str
    val operatorCode = s"$identifierValue in $iterableCode"
    val operatorAst = callNode(
      forEachStmt,
      operatorCode,
      "<operator>.elementOf",
      "<operator>.elementOf",
      DispatchTypes.STATIC_DISPATCH,
      None,
      Option(_identifierNode.typeFullName)
    )
    val conditionAst = Seq(callAst(operatorAst, args))
    scope.moveToScope(identifierValue)//Remove identifierValue from the scope
    // -----------------------------------------------------------------------------------------------------------------

    Seq(
      Ast(forEachNode)
        .withChildren(conditionAst)
        .withChild(forEachBlockAst)
        .withConditionEdges(forEachNode, conditionAst.flatMap(_.root).toList)
    )
  }
```

However, during testing, I encountered many minor issues. For example, in the test code sample below, 
![微信截图_20240829153939](https://github.com/user-attachments/assets/4d6afd21-7757-47b7-bd6d-5b6fe7f30c42)
there are data flow directions that violate the control flow.
![graphviz (9)](https://github.com/user-attachments/assets/d1dbd516-73ab-4375-a505-89d4553d23cf)
 But when I tested your submitted code, I found that these issues didn't exist. I'm very curious about the reason behind this (I was actually looking into the specific CFG implementation logic in Joern). I would be very grateful if you could explain this to me.
