### ISSUE TITLE
Template Method and Class Parsing

### ISSUE THREAD

**Issue by karanpanjabi** [joernio/joern#470]
Hello,

Completely new to Joern here. 
I was wondering if Joern has any capabilities for parsing template functions and classes (C++)? 
Is something like this planned for future?

Edit: I should probably create another issue for this but I wasn't sure if it's an actual bug. I've put this in gitter chat as well: I wasn't able to query and figure out the modifiers for members and classes. Neither was the isConstructor thing working. Could somebody give an example of it which works.

I tried querying by doing something like:
cpg.typeDecl.l(0).method.l(0).isPrivate

**Comment by max-leuthaeuser** [comment]
All of this works with newc.
I am closing this. Feel free to reopen if you encounter any issue here.
