### ISSUE TITLE
[Bug]Fail to get CPG for Ruby

### ISSUE THREAD

**Issue by spingARbor** [joernio/joern#4732]
**Describe the bug**
I want to construct CPG for part of code for giltab.
When I try to parse the code, I get the following exception.
![joern-bug](https://github.com/joernio/joern/assets/57784180/2d250607-1077-4d05-98e8-350bae433532)
When I try to dump Graph, I get the following exception and no output was produced.
![joern-bug-1](https://github.com/joernio/joern/assets/57784180/1de21fc7-e3cf-49ed-acde-207c80d4f11f)

**To Reproduce**
1. Prepare a 256G memory Ubuntu server
2. Install the latest release of Joern
3. Download the source code of Gitlab at https://gitlab.com/gitlab-org/gitlab/-/archive/v16.10.4-ee/gitlab-v16.10.4-ee.tar.gz
4. Extract the file to /home/ubuntu/gitlab-v16.10.4-ee  
5. Parse the code of app folder
```
joern-parse /home/ubuntu/joern/gitlab-v16.10.4-ee/app
```
and you can get the exception
```
overflowdb.SchemaViolationException: IN edge with label AST to an adjacent TYPE_DECL is mandatory, but not defined for this MEMBER node with id=43243
```
6. Dump Graph
```
joern-export --repr cpg --format=dot
```
and you can get the exception
```
ERROR CpgPassBase: Pass io.joern.dataflowengineoss.passes.reachingdef.ReachingDefPass failed
overflowdb.SchemaViolationException: OUT edge with label REF to an adjacent METHOD is mandatory, but not defined for this METHOD_REF node with id=14929
```

**Expected behavior**
Get a CPG for Gitlab code.

**Desktop (please complete the following information):**
 - OS:ubuntu 24.04 server
 - Joern Version :2.0.433
 - Java version :21.0.3

**Comment by DavidBakerEffendi** [comment]
@spingARbor Have you set `Xmx` properties somewhere so that Joern is making use of the available memory?

**Comment by DavidBakerEffendi** [comment]
One way to do it is to add `-J-Xmx20G` or something to the Joern arguments. This schema violation thing can happen at low memory

**Comment by spingARbor** [comment]
Thank you for your response!@DavidBakerEffendi 
I have set -Xmx240G in my server.And when I try to create CPG for a folder with a few ruby files, I also got the exception and without cpg dot file output.On the other hand,The running information will tell me that there is not enough memory if that happens as a result of low memory.
Sincerely，
Arbor

**Comment by DavidBakerEffendi** [comment]
@spingARbor I would hope that's enough memory! If you see that these exceptions when memory usage on the heap gets high then we know the culprit, otherwise I should have a look into where this could possibly be caused as the stacktrace suggests the AST may be malformed.

**Comment by spingARbor** [comment]
I will try again with bigger memory

**Comment by spingARbor** [comment]
@DavidBakerEffendi I tryed to parse the code for gitlab-v16.10.4-ee/app/workers and monitor memory usage at the same time.Joern’s memory usage was always lower than my settings, but I still get the same error.

**Comment by DavidBakerEffendi** [comment]
@spingARbor OK thanks for the investigation, I'll investigate on my end

**Comment by spingARbor** [comment]
Thank you @DavidBakerEffendi 
Sincerely，
Arbor

**Comment by DavidBakerEffendi** [comment]
Found a number of bugs with this that'll help us harden Ruby, see:
* https://github.com/joernio/joern/pull/4739
* https://github.com/joernio/joern/pull/4740

**Comment by spingARbor** [comment]
Thank you. @DavidBakerEffendi

**Comment by DavidBakerEffendi** [comment]
Some more hardening: https://github.com/joernio/joern/pull/4746
Next to deal with the member issue
