### ISSUE TITLE
[Bug] Cpg only contains ast edges, and fail to produce cfg (in C code)

### ISSUE THREAD

**Issue by Victor725** [joernio/joern#4744]
**Describe the bug**
Target c++ code -- named as test.cc, as follow:
```c
#include <nan.h>

extern "C" {
  #include <errno.h>
  #include <netinet/in.h>
  #include <stdio.h>
  #include <sys/socket.h>
  #include <sys/types.h>
}

sockaddr_in sockaddr_from_host_and_port(char* host, int port) {
  struct sockaddr_in addr;
  bzero((char *) &addr, sizeof(addr));
  addr.sin_family = AF_INET;
  if (!inet_pton(AF_INET, host, &(addr.sin_addr))) {
    Nan::ThrowError(Nan::ErrnoException(errno, "inet_pton", strerror(errno)));
  }
  addr.sin_port = htons(port);
  return addr;
}

NAN_METHOD(socket) {
  int fd = socket(AF_INET, SOCK_STREAM, 0);
  if (fd < 0) {
    Nan::ThrowError(Nan::ErrnoException(errno, "socket", strerror(errno)));
    return;
  }
  info.GetReturnValue().Set(fd);
}
```

I run c2cpg.sh to generate cpg:
`c2cpg.sh -o ./test_cpg.bin  -J-Xmx3976m --include /usr/include/ --include /usr/include/x86_64-linux-gnu/ --include /root/.nvm/versions/node/v20.15.0/lib/node_modules/nan/ ./test.cc`

Then, I run joern-export to export cfg:
`joern-export --out ./test_cfg --repr cfg ./test_cpg.bin`

it says:
`CPG does not have dataflow overlay. Calculating.`

and this is what i got for function sockaddr_from_host_and_port
```
digraph "sockaddr_from_host_and_port" {  

}
```

All of the output dot files are empty
I inspect the cpg:
`joern-export --out ./test_cpg --repr all ./test_cpg.bin`

and I found that, there's only ast edges in exported dot file
![image](https://github.com/joernio/joern/assets/55656122/8fbefa1b-5d6a-49ce-bfa2-1bf11459bd4e)

**Comment by max-leuthaeuser** [comment]
I guess something goes wrong during joern-export. 
Could you do a `export SL_LOGGING_LEVEL=debug` before executing it and post the logs?

**Comment by Victor725** [comment]
Sure.
I run `c2cpg.sh -o ./test_cpg.bin  -J-Xmx3976m --include /usr/include/ --include /usr/include/x86_64-linux-gnu/ --include /root/.nvm/versions/node/v20.15.0/lib/node_modules/nan/ ./test.cc`
then, `export SL_LOGGING_LEVEL=debug`
and then `export SL_LOGGING_LEVEL=debug`
I restored the output to this file:
[log.txt](https://github.com/user-attachments/files/16124722/log.txt)

**Comment by max-leuthaeuser** [comment]
None of the passes to make the dataflow work has been executed.
Please run joern-parse to generate the CPG instead of invoking c2cpg directly. See it's --help. There is also an option to pass c2cpg specific arguments.

**Comment by Victor725** [comment]
Thank you very much!
I run `joern-parse -o ./test_cpg.bin --language c ./test.cc --frontend-args -J-Xmx3976m --include /usr/include/ --include /usr/include/x86_64-linux-gnu/ --include /root/.nvm/versions/node/v20.15.0/lib/node_modules/nan/`
and it can produce cfg now.
