### ISSUE TITLE
bring back joern-slice test

### ISSUE THREAD

**Issue by mpollmeier** [joernio/joern#4783]
Hey @DavidBakerEffendi, your name appears around the joern-slice code quite a bit... can you help me get the test back to work?

I commented it out as part of the flatgraph migration, but I'm pretty sure it was broken before:
https://github.com/joernio/joern/blob/c1919cfe5611665e433a4aff93989411f735d0b8/.github/workflows/pr.yml#L99-L103

On PR runs we create a tiny test cpg which most likely doesn't have any dataflows, and then we try and slice it? That doesn't make much sense, does it? The test doesn't assert anything either, apart from the exit code of joern-slice...

What's your thoughts on having a proper integration test for this, do we need some testcode that contains actual dataflows that can be sliced?

**Comment by mpollmeier** [comment]
Sounds good. Any suggestions on the input, i.e. do we have some small testcode sample that showcases a few simple dataflows?

**Comment by DavidBakerEffendi** [comment]
I think the simplest would be to take simple interprocedural data-flows from existing data-flow tests imo
