### ISSUE TITLE
[Bug] `--language <value>` option in `joern-parse` is useless.

### ISSUE THREAD

**Issue by jiezhuzzz** [joernio/joern#4785]
**Describe the bug**

`--language <value>` option in `joern-parse` is useless. `joern-parse` will stick to file extension when parsing files.

**To Reproduce**
1. create a file `code.c`
```c
#include<stdio.h>
int main() {
    int a = 1;
    printf("a = %d", a);
}
```
2. run `joern-parse --language newc code.c` and `joern-export --repr all -o withc`
3. rename the code file as `mv code.c code.java`. Export graph as before: `joern-parse --language newc code.java`, and `joern-export --repr all -o withjava`
4. you will find two graph dot file are totally different

**Expected behavior**
`joern-parse` will ignore the file extension and use `--language` to determine which frontend to be invoked.

**Desktop (please complete the following information):**
 - OS: Fedora Linux 40
 - Joern Version: HEAD+20240318-1648
 - Java version: 21.0.3

**Comment by max-leuthaeuser** [comment]
Sorry, but this is expected. If you try to `joern-parse` a `.java` file with `--language newc` you will end up with a mostly empty CPG because `c2cpg` wont touch any `.java` file.

**Comment by jiezhuzzz** [comment]
Understood, thanks for your reply! I thought that could be a bug rather than a default behavior.
