### ISSUE TITLE
[Bug] Why JoernV4 cannot dump node with its id

### ISSUE THREAD

**Issue by Flying-Tom** [joernio/joern#4976]
**Describe the bug**

In joern v4, use `cpg.graph.allNodes.map(node=>node).toJsonPretty` cannot get the node id, which can be done in joern v2

**Expected behavior**

`cpg.graph.allNodes.map(node=>node).toJsonPretty` can get the node id as joern v2

**Desktop (please complete the following information):**
 - OS: ubuntu20.04
 - Joern Version: v4.0.90
 - Java version: 19.0.2

**Additional context**

When using `cpg.graph.allNodes.map(node=>node).toJsonPretty`, `node.id` can get the `GNode`'s id but it won't appear in the output json str.

**Comment by max-leuthaeuser** [comment]
Due to the change from odb to flatgraph there are no IDs anymore.
You can read more here: https://github.com/joernio/joern/blob/master/changelog/4.0.0-flatgraph.md

**Comment by Flying-Tom** [comment]
May I ask what it exactly means by "no IDs" in the flatgraph? I refer the [joern migration PR](https://github.com/joernio/joern/pull/4630/files) and `node.id()` is still used (e.g. [DataFlowSlicing.scala](https://github.com/joernio/joern/pull/4630/files#diff-27483e6b7720efdbba3fb8107f33cafd4b2641043368a58297cea0b829d87fe9)). 

And if there is no IDs of nodes and I need to get a list of nodes, edges and their connections, how can I definite which nodes a edge is connecting (no identifier can specify them).

To be more specifically, `cpg.graph.allNodes.outE.map(edge=>List(edge.dst.id, edge.src.id, edge.label, edge.property))` can give the edge's src and dst node id (but the id is stranger compared with joern V2, e.g., id `510` in V2 may change to `111669149719` in V4), is this node id available or this is a tmp/random value?

**Comment by max-leuthaeuser** [comment]
Sorry, I guess I mixed something up.
Let's wait for a profound explanation from @bbrehm or @mpollmeier

**Comment by mpollmeier** [comment]
I agree that the ID should appear in the json output. Thanks for reporting, I'll take a look shortly. 

Some relevant context: the node id ist now a synthetic value which is comprised of the node's `kind` (essentially the label, e.g. METHOD, IDENTIFIER, ...) and the `seqId` which is the sequential ID within that kind.

**Comment by mpollmeier** [comment]
https://github.com/joernio/joern/pull/4979
