### ISSUE TITLE
[Bug] Build fails on the Homebrew formulae

### ISSUE THREAD

**Issue by eleanordoesntcode** [joernio/joern#5029]
**Describe the bug**
While trying to update the Homebrew formulae (which allows Linux/macOS users to install your software easily), the tests ran into a couple of issues. I got the error message java.lang.NullPointerException: Cannot read the array length because "$this" is null (a link to the full log with context is at the bottom of this issue). Here is a link to the pull request for context: Homebrew/homebrew-core#195610.

**To Reproduce**
1. Try to compile the project on macOS/Linux with the specifications noted in https://github.com/eleanordoesntcode/homebrew-core/blob/bump-joern-4.0.120/Formula/j/joern.rb
2. Notice that the build doesn't complete

**Expected behavior**
I expected the project to build correctly.

**Desktop (please complete the following information):**
 - Linux (seems to be Ubuntu 22.04)/macOS 13
 - Joern 4.0.120 
 - OpenJDK 23 or 21 (both tried)

**Additional context**
Here is a direct link to the error, with the full log: https://github.com/Homebrew/homebrew-core/actions/runs/11524054403/job/32083491897#step:4:622

**Comment by max-leuthaeuser** [comment]
I have seen this in the past already. It might be due to a broken download of the astgen binary (joern/astgen). Try rerunning it.

**Comment by eleanordoesntcode** [comment]
It already ran twice with the same errors, but I can try locally.

**Comment by eleanordoesntcode** [comment]
I can confirm I'm getting the same error locally after running `sbt stage`. I ran the command 3 times to check if it wasn't some bad download.

**Comment by max-leuthaeuser** [comment]
Well, Joern PR, master, and release builds do the same (sbt stage) and they are fine. 
Maybe @mpollmeier can help. 

Did you run `sbt clean` in between your local `stage` runs to delete anything that might be broken?

**Comment by eleanordoesntcode** [comment]
I did

**Comment by max-leuthaeuser** [comment]
You may want to test the following branch: https://github.com/joernio/joern/pull/5033

**Comment by mpollmeier** [comment]
(which is now on master)
Another thing to try is delete the local cache in the joern repo root `.local`.

**Comment by eleanordoesntcode** [comment]
I'll try rerunning the tests with the next tag. Thanks for the help!

**Comment by eleanordoesntcode** [comment]
I can confirm the bug has been fixed on my machine, and it should work on the GitHub runners. Thanks for the help!
