### ISSUE TITLE
Empty response from joern-slice

### ISSUE THREAD

**Issue by xcx1r3** [joernio/joern#5072]
Hello @DavidBakerEffendi ,
I’m a beginner in SAST and I’m trying to run code slicing on the ThemesController.add method in my Spring project. I used the following command:
`joern-slice data-flow --method-name-filter "cc.iteachyou.cms.controller.admin.ThemesController.add" --method-parameter-filter "themePath" --out themePath_slice.json cpg.bin`
However, I received an empty response: "Empty slice, no file generated."
![image](https://github.com/user-attachments/assets/c318d6d2-e89f-458c-94b6-d1cee4bd179f)
Could you help me figure out what might be going wrong?

**Comment by DavidBakerEffendi** [comment]
Hi @xcx1r3, the method name filter uses regex, and you should consider how the method full names are represented in the CPG to figure out how the match might go. Try `cc.iteachyou.cms.controller.admin.ThemesController.add.*`. The `.*` will match any signature. If this still doesn't give results, then I may need more information to reproduce

**Comment by xcx1r3** [comment]
Thank you for your response. I still receive an empty response even after using `.*`. Below is the code snippet of the controller:

```
package cc.iteachyou.cms.controller.admin;

import java.io.File;
import java.io.IOException;
import ...

@Controller
@RequestMapping("admin/theme")
public class ThemesController extends BaseController {	
	@Log(operType = OperatorType.PAGE, module = "主题管理", content = "主题分页列表")
	@RequestMapping({"","/list"})
	@RequiresPermissions("system:theme:page")
	public String list(Model model, SearchEntity params) {
		...
	}
	
	@Log(operType = OperatorType.INSERT, module = "主题管理", content = "添加主题")
	@RequestMapping("/add")
	@RequiresPermissions("system:theme:add")
	public String add(String themePath) throws IOException, CmsException {
		...
	}
```
and my command below:
![image](https://github.com/user-attachments/assets/dd3c0622-a626-4752-9d27-746c9ff0477d)
and the project repository:
https://github.com/iteachyou-wjn/dreamer_cms/blob/Previous_Releases_4.1.3/src/main/java/cc/iteachyou/cms/controller/admin/ThemesController.java#L71

**Comment by DavidBakerEffendi** [comment]
Hi @xcx1r3, I see what is wrong, I've re-read the usage information for the slicing and it appears you're using the arguments wrong. The best I can do with the intended slicing you want is

```
./joern-slice data-flow --method-name-filter "add" --method-parameter-filter ".*String" --out themePath_slice.json slicing.cpg
```

The name filter is not full name based, and the parameter filter is based on types (full names) not parameter names. See https://docs.joern.io/cpg-slicing/#general

**Comment by xcx1r3** [comment]
oh it works, thank you!
