### ISSUE TITLE
Access specifier not detected in C++

### ISSUE THREAD

**Issue by MaxwellMasaitis** [joernio/joern#515]
In the following code block, the public modifier is not detected by Joern: all of ```cpg.typeDecl.modifier.l```, ```cpg.member.modifier.l```, or ```cpg.method.modifier.l``` produce empty lists.
```
#ifndef FUNC2_HPP
#define FUNC2_HPP

#include <string>

std::string func2_hello();

class ExampleClass {
public:
  int a;
  int b;
  void setA(int a) {
    this->a = a;
  }
  void setB(int b) {
    this->b = b;
  }
};
#endif
```

**Comment by max-leuthaeuser** [comment]
All of this works with newc.
I am closing this. Feel free to reopen if you encounter any issue here.
