### ISSUE TITLE
Uniform initialization not detected in C++

### ISSUE THREAD

**Issue by MaxwellMasaitis** [joernio/joern#516]
The lines for ```int brace{10};``` and ```int uniform[]{0,1,2};``` are equivalent to ```int brace=10``` and ```int uniform[]={0,1,2};```, respectively, but are interpreted by Joern as Block nodes.
```
#include <iostream>

using namespace std;

int main() {
	
  int brace{10};
  
  cout<<brace<<endl;
    
  int uniform[]{0,1,2};
  
  for (int i : uniform) {
      cout<<i<<endl;
  }
	
  return 0;
}
```

**Comment by johannescoetzee** [comment]
With the new front-end, the situation is somewhat improved. The `{10}` and `{0, 1, 2}` are treated as array initializers, but still not as assignments. Thsi can be seen from the truncated AST

![image](https://user-images.githubusercontent.com/25384566/141273183-78b34976-eb81-422a-9c05-711b47b57643.png)
