### ISSUE TITLE
Joern server data loss

### ISSUE THREAD

**Issue by IzaiahSun** [joernio/joern#544]
I use the version of commit 7755b3adc7b9b9662cada774ef16d5bb6aacf49f.
When I run `joern --server` and use `cpgqls_client` to access the http api, I found that the result is not complete.
The result should include key-value pairs, in forms of `key = value`, but the key is lost like this(lost key should in the red boxes in the picture)
![image](https://user-images.githubusercontent.com/34444372/120919682-7789cb00-c6ed-11eb-8a17-c7f8b66df40b.png)
The source code of the script is
```python
from cpgqls_client import CPGQLSClient, import_code_query, workspace_query

def get_function_ast(client,function_name,filename=""):
    if filename != "":
        query="cpg.method.filename(\"%s\").name(\"%s\").ast.l" % (filename,function_name)
    else:
        query="cpg.method.name(\"%s\").ast.l" % function_name
    return client.execute(query)

server_endpoint = "localhost:8080"
basic_auth_credentials = ("username", "password")
client = CPGQLSClient(server_endpoint, auth_credentials=basic_auth_credentials)

load_cpg_query="loadCpg(\"./workspace/libwebsockets/cpg.bin\")"
result=client.execute(load_cpg_query)

res=get_function_ast(client,"lws_ssl_capable_read_no_ssl")
print(res)
```

**Comment by ursachec** [comment]
Thanks for the report @IzaiahSun, I've started looking into it, will post updates in the next couple of days
