### ISSUE TITLE
joern cannot work with cpp file

### ISSUE THREAD

**Issue by YeJZ** [joernio/joern#561]
I hava this code:

`
int main()
{
    std:map<int,string> personnel;
    personnel.insert(pair<int,string>(1,"jack"));
    personnel.insert(pair<int,string>(2,"rose"));
    personnel.insert(pair<int,string>(3,"lucy"));

    map<int,string>::iterator iter;
    for(iter = personnel.begin(); iter != personnel.end();iter ++)
    {
        if(iter->second == "rose")
        {
            personnel.erase(iter);
        }
    }

    return 0;
}
`

and the file name is X42.c. 

then i write a rule to dectect the problem due to erase,it works fine when the file name is X42.c.

`joern> importCode(inputPath="/usr1/code/joern/code/",projectName="x42-c")`
`joern> cpg.call.find(y => {y.name.contains("erase")})
res12: Option[Call] = Some(
  value = Call(
    id -> 1000151L,
    code -> "personnel.erase(iter)",
    name -> "personnel.erase",
    order -> 1,
    methodFullName -> "personnel.erase",
    argumentIndex -> 1,
    signature -> "TODO",
    lineNumber -> Some(value = 42),
    columnNumber -> Some(value = 5),
    methodInstFullName -> None,
    typeFullName -> "",
    depthFirstOrder -> None,
    internalFlags -> None,
    dispatchType -> "STATIC_DISPATCH",
    dynamicTypeHintFullName -> List()
  )
)
`

But when i rename the file to X42.cpp, joern cannot find the "erase" call:
`joern> importCode(inputPath="/usr1/code/joern/code/",projectName="x42-cpp")`

`joern> cpg.call.find(y => {y.name.contains("erase")})
res14: Option[Call] = None
`

**Comment by johannescoetzee** [comment]
C++ support is much better with the new Eclipse CDT based frontend (which is now the default C/C++ frontend in Joern). The `personnel.erase(iter)` call is represented differently, however, so your query would not work. What you could do, however, is
```
joern> importCode.c("x42.cpp")

joern> cpg.call.code(".*erase.*").l 
res2: List[Call] = List(
  Call(
    code -> "personnel.erase(iter)",
    methodFullName -> "",
    name -> "",
    ... // truncated for brevity
  ),
  Call(
    code -> "personnel.erase",
    methodFullName -> "<operator>.fieldAccess",
    name -> "<operator>.fieldAccess",
    ...
  )
)
```

If you want a more precise result, you could do either
```
joern> cpg.call.code(".*erase\\(.*").l 
```
to find an explicit call to `erase`, or
```
joern> cpg.call.name(".*fieldAccess").where(_.argument.isFieldIdentifier.canonicalName("erase")).astParent.l 
```

This works because of the new AST structure:
![image](https://user-images.githubusercontent.com/25384566/141265685-10eb2e89-c405-48f9-b333-1482da9e7f2a.png)
