### ISSUE TITLE
How to get PDG in json format given a dictionary full of .cpp file

### ISSUE THREAD

**Issue by for-just-we** [joernio/joern#565]
There are 1000 cpp files in the tmp dictionary.

![图片](https://user-images.githubusercontent.com/49546352/127774200-f6b04bfa-771b-4964-ad03-871126b17fdf.png)

what command should I run to get a json file that contains the PDG for all functions in those 1000 cpp files.

I'm not familiar with scala, I always come across errors with graph-for-funcs.sc.

**Comment by ursachec** [comment]
please provide more information about what you tried out first, and someone might help you solve your task. best place for doing this is the Discord channel
