### ISSUE TITLE
joern server responded 404

### ISSUE THREAD

**Issue by NicK2oo3** [joernio/joern#618]
![image](https://user-images.githubusercontent.com/47672646/134916554-17208355-a0c3-46c1-8c7c-173ea538e732.png)
how can i solve it?

**Comment by ursachec** [comment]
@NicK2oo3 can you post the contents of `main.py` so it's clear what the request looks like?

**Comment by NicK2oo3** [comment]
> @NicK2oo3 can you post the contents of `main.py` so it's clear what the request looks like?

you can see it in https://github.com/epicosy/devign.

**Comment by ursachec** [comment]
if i'm looking at the correct spot in your code, it looks like you're trying to fetch query results from the incorrect HTTP endpoint provided by the Joern server https://github.com/epicosy/devign/blob/master/src/prepare/cpg_client_wrapper.py#L24

you can either use the cpgqls client logic directly to send the query or implement your own following what's in there + the test suite
https://github.com/joernio/cpgqls-client-python/blob/master/cpgqls_client/client.py#L61

here is where the routes are defined:
https://github.com/ShiftLeftSecurity/codepropertygraph/blob/ca3834850eb84babd41c6e530593950252233289/console/src/main/scala/io/shiftleft/console/cpgqlserver/CPGQLServer.scala#L111-L122

and the general API for the HTTP framework used https://com-lihaoyi.github.io/cask/#minimal-example

does this answer your question?

**Comment by NicK2oo3** [comment]
could you provide more detail?i don't know how to do

**Comment by ursachec** [comment]
@NicK2oo3 you should have all the info necessary in the links I posted in my previous comment. You could start by getting the examples from _cpgqls-client-python_ to run, and then slowly adapt them to your needs
