### ISSUE TITLE
PARSE FAILED: ./java-cp/X42.jar is neither a file nor a directory

### ISSUE THREAD

**Issue by SkysunPrincess** [joernio/joern#668]
The documentation (https://docs.joern.io/organizing-projects/) indicates that Joern can analyze Java programs. However, when we use it to analyze a jar file, an error is reported as "PARSE FAILED: ./java-cp/X42.jar is neither a file nor a directory" .

The command we use is
”joern> importCode("./x42/java-cp/X42.jar", "x42-java")“

I would like to know whether our usage is wrong.
Hope your reply. 
Thank you very much!

**Comment by DavidBakerEffendi** [comment]
On the Joern repo itself, the X42.jar is immediately on the root of the project. When pulling Joern and opening `./joern` I do not get unexpected output when running:
```scala
 importCode("./X42.jar","x42-java") 
 ```
 Just note the directory path when compared to your command.

**Comment by DavidBakerEffendi** [comment]
Closed due to inactivity
