### ISSUE TITLE
[javasrc2cpg] Inconsistent number of paths found in first `try` dataflow test

### ISSUE THREAD

**Issue by johannescoetzee** [joernio/joern#689]
The first testcase in the dataflow test suite for `try` statements usually finds 3 paths, but on rare occasions 2. It's unclear why this is happening, and I haven't been able to reproduce this issue through the `joern` console. My suspicion is that it's some weird concurrency bug caused by the interaction between the cpg generator and scalatest. If something similar pops up, this should be investigated more thoroughly.

**Comment by fabsx00** [comment]
Fixed by https://github.com/joernio/joern/pull/695
