### ISSUE TITLE
c2cpg: Code inside disabled preprocessor directive not parsed

### ISSUE THREAD

**Issue by raymontag** [joernio/joern#762]
While the code at https://github.com/joernio/joern/blob/master/joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/CdtParser.scala#L40 reads as if code inside disabled preprocessor directives should be parsed, this doesn't work for me.

Take, e.g., https://github.com/LibVNC/libvncserver - the code in `libvncclient/zrle.c` is not parsed when importing the directory with `importCode()`.

I would understand that this is the case if there is an #else directive but that's not the case for that example. 

Even better would be if we were able to define our own preprocessor directores like with the `-D` option for gcc/clang.

**Comment by max-leuthaeuser** [comment]
There is the `--define` argument for c2cpg.
So a `--define LIBVNCSERVER_HAVE_LIBZ` should do the trick.

**Comment by raymontag** [comment]
That should do the trick but is the define option exposed to joern-scan or the joern shell? Can't find a way to use it :(
