### ISSUE TITLE
Readme: Installation with wrong permissions?

### ISSUE THREAD

**Issue by mal-tee** [joernio/joern#779]
If I install joern according to the steps in the readme, I can't run `joern` as regular user, only with sudo.

This initially occured on my ubuntu desktop machine. I reproduced this with a fresh ubuntu21.10 lxc container.

```sh
wget https://github.com/joernio/joern/releases/latest/download/joern-install.sh
chmod +x ./joern-install.sh
sudo ./joern-install.sh
joern # <-- doesn't work, needs sudo
```

**Comment by mpollmeier** [comment]
Thanks for reporting this one!

Context: joern-install.sh installs the distribution to `~/bin/joern`, which resolves to `/root/bin/joern` if run as `sudo`. 
`root` typically lacks the `x` flag for 'other' users - for good reasons. Unfortunately, that also means that our beautifully crafted symlink doesn't work. 

@fabsx00 how should we handle this one? possible options include:
* using a different default location for user==root, e.g. `/usr/local/lib/joern` or so?
* not supporting system-wide install
* change the default installation procedure in the readme

**Comment by fabsx00** [comment]
Let's use a different install location.

**Comment by mpollmeier** [comment]
the internet seems to suggest `/opt` for our use case...
https://github.com/joernio/joern/issues/779
