### ISSUE TITLE
[Help] Cannot parse Node.js addon C++ code using NEWC

### ISSUE THREAD

**Issue by VainlyStrain** [joernio/joern#788]
Hi,

I'm facing an issue with the latest version of joern, that I cannot parse any C++ code related to Node.js addons.

When I try to import the code, joern throws an error that no suitable CPG generator was found. When I force it to use CPP or C using `importCode.cpp` (resp. `importCode.c`), the graph generated only contains the following nodes: a top-level entry method, a method return node, and the entire source code of the CPP files in an `UNKNOWN` node.

Here are some example apps where I replicated this behaviour:
https://github.com/mapbox/node-sqlite3 (the CPP files in the src/ directory)
https://nodejs.org/api/addons.html#hello-world
https://nodejs.org/api/addons.html#context-aware-addons (the last snippet before the Worker support section)

Is CPP not yet entirely supported by the new Eclipse-based parser, or am I facing an installation issue (i.e. missing a dependency)? I have installed Joern using the installer script as noted in the description.

Using the importCode.oldc parser, the addon code is mostly parsed fine. However, for some more complex structures (as the `exports->set` line in https://nodejs.org/api/addons.html#context-aware-addons), the whole line is parsed as one graph node.

Is there a way for me to debug this?

My system:

OS: Fedora 34 x86-64
Joern version: 1.1.359

Thanks!

**Comment by max-leuthaeuser** [comment]
We simply forgot to add .cc files to the list of valid C++ extension. The linked PR fixes that.

**Comment by VainlyStrain** [comment]
Hi!

I tested it out, and renaming the files to ".cpp" mostly fixed the issue.

When I use a "normal" importCode, joern still reports that no suitable parser was found, but when I use importCode.cpp, the app from https://nodejs.org/api/addons.html#hello-world was indeed parsed correctly.

However, for the example of https://nodejs.org/api/addons.html#context-aware-addons, joern still had problems parsing the initialization method of the addon. This part of the code is put in an UNKNOWN node:

```
// Initialize this addon to be context-aware.
NODE_MODULE_INIT(/* exports, module, context */) {
  Isolate* isolate = context->GetIsolate();

  // Create a new instance of `AddonData` for this instance of the addon and
  // tie its life cycle to that of the Node.js environment.
  AddonData* data = new AddonData(isolate);

  // Wrap the data in a `v8::External` so we can pass it to the method we
  // expose.
  Local<External> external = External::New(isolate, data);

  // Expose the method `Method` to JavaScript, and make sure it receives the
  // per-addon-instance data we created above by passing `external` as the
  // third parameter to the `FunctionTemplate` constructor.
  exports->Set(context,
               String::NewFromUtf8(isolate, "method").ToLocalChecked(),
               FunctionTemplate::New(isolate, Method, external)
                  ->GetFunction(context).ToLocalChecked()).FromJust();
} 
```

Thank you very much for the PR :+1:

**Comment by max-leuthaeuser** [comment]
I guess the macro definition for NODE_MODULE_INIT is in node.h?
Then this should be available (e.g., in the same folder). Otherwise, Eclipse CDT won't be able to expand the macro.

**Comment by max-leuthaeuser** [comment]
> When I use a "normal" importCode, joern still reports that no suitable parser was found

Yes, this  touches a different piece of code.
I think @mpollmeier did some work there recently and maybe he is able to fix that.

**Comment by VainlyStrain** [comment]
> Then this should be available

That was the issue! The file was installed in a directory which is not included by default. Now, it works fine! Thank you very much for the help!

**Comment by mpollmeier** [comment]
added more file endings in https://github.com/joernio/joern/issues/788
