### ISSUE TITLE
ghidra2cpg work with stripped binary

### ISSUE THREAD

**Issue by zi0Black** [joernio/joern#800]
I'm currently working with a stripped binary (ARM), after importing it and running `gpc.call(".*").name.l` the only things I get is *UNKNOWN*, I think the problem resides in the fact that the binary doesn't have symbols.
I'm currently trying to obtain a binary with symbols from ghidra and then analyze it, but having build-in support for importing symbols or opening a ghidra project would be great.

![image](https://user-images.githubusercontent.com/13380579/144835728-ae1a9bc0-7e01-4f5a-afba-8842242962fa.png)

**Comment by itsacoderepo** [comment]
Hi zi0Black, 

this issues is already fixed with https://github.com/joernio/joern/pull/797. 

You should see (more) call names with the latest version of joern. Also you should  be able to traverse call stacks.

**Comment by zi0Black** [comment]
I was asking for a way to import symbols for a stripped binary where I have defined hundred of functions manually or with libraries. I'm exploring some ways to obtain this.
I was unlucky since the release you suggested a few days ago; I have had some issues during the CPG creation after the decompile phase. I'm going to test an old release.

![image](https://user-images.githubusercontent.com/13380579/145177622-472470e5-5e79-40ae-9f6d-c53d87024d0b.png)
