### ISSUE TITLE
OldC vs NewC Parsing: Type difference for pointers

### ISSUE THREAD

**Issue by jryerb** [joernio/joern#892]
NewC parser drops the * in the type field for identifiers declared as pointers.

```
joern> val code = """
              void test_func() {
              char * badChar = malloc(0x100);
              free(badChar);
              return;
              }""".stripMargin  

joern> importCode.oldc.fromString(code) 
...
joern> cpg.identifier.evalType.l 
res14: List[String] = List("char *", "char *")
...
joern> importCode.c.fromString(code) 
...
joern> cpg.identifier.evalType.l 
res17: List[String] = List("char", "char")
```

**Comment by max-leuthaeuser** [comment]
I think this change was intentional. You can receive the information (pointer or not) via the CODE field.

**Comment by jryerb** [comment]
Hmmm, ok. A brief mea culpa that my example here doesn't represent my use case. Since the pointer information is no longer included in an identifier's type, with the newc parser is there a straight forward way to tell if an identifier returned by a query is a pointer or not? 
For example the results of something like 
`cpg.method("someFunc").callIn.argument(1).isIdentifier`
Previous I could `.evalType(".*.")` on the end of that to get all the pointers.

**Comment by max-leuthaeuser** [comment]
You may do it like this: https://github.com/joernio/joern/pull/934/files#diff-b83c4a9abd7e24df79598900377d20b9d9ba7a397f42ac53181e104c938914b5R104-R107

**Comment by jryerb** [comment]
Looks good to me. Thanks a lot.
