### ISSUE TITLE
Data-Flow Analysis of fscanf

### ISSUE THREAD

**Issue by monkbai** [joernio/joern#913]
Is joern able to analyze the data-flow of functions like `fscanf`? For example, if I have the code below

``` c
void foo()
{
    char data;
    data = ' ';
    fscanf (stdin, "%c", &data);

    char result = data + 1;
    printf("%c\n", result);
}
```
how could I get the data-flow from `fscanf` to `result`?

**Comment by max-leuthaeuser** [comment]
This can now be done like this: https://github.com/joernio/joern/pull/934/files#diff-735dff781c87fdd020336c8833cbe6b12dd35a1ddbe75e39fc6aed9f4adbfa91R1687-R1716
