### ISSUE TITLE
multiple Returns in one function

### ISSUE THREAD

**Issue by kilimnik** [joernio/joern#947]
I noticed, that the following code does not produce the expected results:
```cpp
int main(int argc, char *argv[])
{
    if (argc == 1) {
        return 1;
    }

    return 2;
}
```

I would expect `cpg.methodReturn.toReturn.l` to output both returns, but the actual results is:
```
res34: List[Return] = List(
  Return(
    id -> 3074457345618258683L,
    argumentIndex -> 1,
    argumentName -> None,
    code -> "return 1;",
    columnNumber -> Some(value = 8),
    lineNumber -> Some(value = 4),
    order -> 1
  )
)
```

Intrestingly when looking at the `cpg.methodReturn.l` output, there are three results but only one of them has a line number set:
```
res35: List[MethodReturn] = List(
  MethodReturn(
    id -> 3074457345618258687L,
    code -> "int",
    columnNumber -> Some(value = 0),
    dynamicTypeHintFullName -> ArraySeq(),
    evaluationStrategy -> "BY_VALUE",
    lineNumber -> Some(value = 1),
    order -> 4,
    typeFullName -> "int"
  ),
  MethodReturn(
    id -> 3074457345618258689L,
    code -> "RET",
    columnNumber -> None,
    dynamicTypeHintFullName -> ArraySeq(),
    evaluationStrategy -> "BY_VALUE",
    lineNumber -> None,
    order -> 2,
    typeFullName -> "ANY"
  ),
  MethodReturn(
    id -> 3074457345618258700L,
    code -> "RET",
    columnNumber -> None,
    dynamicTypeHintFullName -> ArraySeq(),
    evaluationStrategy -> "BY_VALUE",
    lineNumber -> None,
    order -> -1,
    typeFullName -> "ANY"
  )
)
```

This does happen on the new as well as on the old C frontend. The difference to the old c frontend, is that  `cpg.methodReturn.l` outputs only two entries.

**Comment by max-leuthaeuser** [comment]
This should work now. See: https://github.com/joernio/joern/pull/948/files#diff-1d64c96a43ab0900b20a698dcceeb0a3865a9ed1d30a30ddb21fd95089370a99R43

Feel free to close this issue once you verified this for yourself.

**Comment by kilimnik** [comment]
Thank you all for the fast resolution. It works now.
