### ISSUE TITLE
c frontend, call missing in cpg.call

### ISSUE THREAD

**Issue by kilimnik** [joernio/joern#964]
I am not sure, why that happens and I wasn't able to produce a minimal example. But when importing the code from [here](https://github.com/ytisf/theZoo/raw/master/malware/Source/Original/Win32.Mirai.2016/Win32.Mirai.2016.zip) (Keep in mind this is actual malware ;) . the password is `infected`) and executing `cpg.call("recv").size` I only get 11 results, despite having 12 calls to the `recv` function.

The old c frontend does output all 12.

**Comment by max-leuthaeuser** [comment]
The missing call is in:
```
> mirai/bot/scanner.c
39:    int ret = recv(sock, buf, len, flags);
```

Thats because the whole content there is gated behind a `#ifdef MIRAI_TELNET`.
The old C frontend ignored this completely.

With the new C frontend you will get it e.g., with:
`joern> importCode.c("/path/to/source/", args=List("--define","MIRAI_TELNET"))`

**Comment by kilimnik** [comment]
Oh, my bad. Is there a way to ignore all gates?

**Comment by max-leuthaeuser** [comment]
Sadly no as the underlying parser (Eclipse CDT) sadly does not support this.
You can however run c2cpg beforehand with `--print-ifdef-only` which will print a comma-separated list of all preprocessor ifdef and if statements and does not create a CPG. With this information you may be able to figure out which ones to set.
