### ISSUE TITLE
Two-edges between two nodes in the Control Flow Graphs

### ISSUE THREAD

**Issue by joseadp** [joernio/joern#969]
I am using Joern to extract the Control Flow Graphs (CFGs) of a large dataset that contains C/C++ vulnerable functions. In my initial analysis, I noticed a behavior that I wanted to double check with you or anyone from the Joern development team. I am not sure if it was implemented like that as a feature, or if it is a bug, or if it is something that I'm not using Joern properly.

The behavior I am noticing is the presence of two edges in the same direction between two  same nodes in a CFG. I saw this behavior in three specific code constructs:

- A conditional ternary, such as the following source code:
    `return server_banner ? server_banner : AP_SERVER_BASEVERSION;`
- A for, in the node of the condition of the for loop.
- A switch, in which more than one case goes to the same instruction line.

Is this the expected behavior? Or is it something that should have been mapped differently in the CFG?
Could you help me with that?

**Comment by max-leuthaeuser** [comment]
Please double check your nodes again. Do not get confused with object identity and equality.
E.g.: `server_banner` in you first example refers to the same C AST identifier but within the CPG two different CPG identifiers are created (different objects but same attributes). Hence, you will get two CFG edges to the same CPG nodes (two identifiers having the same attributes) but these are actually two different instances (check the `id` property).

**Comment by joseadp** [comment]
@max-leuthaeuser , thank you for your reply!

The CFG that I have for the example that I sent you is the following one:

```
digraph "ap_get_server_banner" {
"1393968" [label = "(RETURN,return server_banner ? server_banner : AP_SERVER_BASEVERSION;,return server_banner ? server_banner : AP_SERVER_BASEVERSION;)" ]
"1393969" [label = "(<operator>.conditional,server_banner ? server_banner : AP_SERVER_BASEVERSION)" ]
"1393965" [label = "(METHOD,ap_get_server_banner)" ]
"1393973" [label = "(METHOD_RETURN,int)" ]
  "1393968" -> "1393973"
  "1393969" -> "1393968"
  "1393965" -> "1393969"
  "1393965" -> "1393969"
}
```

Should I consider the AST or the CPG instead? How do I check the `id` property? I thought they were the values before each node (e.g., "1393965").
Would it be the same for the conditional loop (for) case?

**Comment by max-leuthaeuser** [comment]
I found a minimal reproducer for this behavior: 
```
bool a;
bool b;

bool test() {
  return a ? a : b;
}
```

In joern:
```
> cpg.method.name("test").dotCfg.l.head
res1 = digraph "test" {  
"3074457345618258678" [label = "(RETURN,return a ? a : b;,return a ? a : b;)" ]
"3074457345618258679" [label = "(<operator>.conditional,a ? a : b)" ]
"3074457345618258676" [label = "(METHOD,test)" ]
"3074457345618258683" [label = "(METHOD_RETURN,bool)" ]
  "3074457345618258678" -> "3074457345618258683" 
  "3074457345618258679" -> "3074457345618258678" 
  "3074457345618258676" -> "3074457345618258679" 
  "3074457345618258676" -> "3074457345618258679" 
}
```
There we can see, that the method node (3074457345618258676) has two edges to the conditional call (3074457345618258679). 
There might be something wrong with the [CfgGenerator](https://github.com/ShiftLeftSecurity/codepropertygraph/blob/master/semanticcpg/src/main/scala/io/shiftleft/semanticcpg/dotgenerator/CfgGenerator.scala#L19). I was able to debug up to that point and these duplicated edges are generated somewhere there. 
@fabsx00 If you got some time please have a look.

**Comment by joseadp** [comment]
@max-leuthaeuser , thank you for your reply.

Another example when the two edges are added is when a `for` is present: https://github.com/mozilla/gecko-dev/blob/065ae1e01e85845b2948ded3b0ae3378fbd959ed/js/src/vm/TypeInference.cpp#L1928

It generates the CFG that I added below. However, it seems to happen for all cases that I analyzed. After the `<operator>.lessThan`, two edges for the first statements of the for-block are added.

I am just trying to understand if this is the expected behavior or not. It seems it is not the expected behavior, but maybe I am missing something.

```
digraph "TemporaryTypeSet::hasObjectFlags" {
"1004140" [label = "(<operator>.assignment,count = getObjectCount())" ]
"1004168" [label = "(RETURN,return false;,return false;)" ]
"1004128" [label = "(unknownObject,unknownObject())" ]
"1004133" [label = "(<operator>.equals,baseObjectCount() == 0)" ]
"1004142" [label = "(getObjectCount,getObjectCount())" ]
"1004145" [label = "(<operator>.assignment,i = 0)" ]
"1004148" [label = "(<operator>.lessThan,i < count)" ]
"1004151" [label = "(<operator>.postIncrement,i++)" ]
"1004130" [label = "(RETURN,return true;,return true;)" ]
"1004134" [label = "(baseObjectCount,baseObjectCount())" ]
"1004137" [label = "(RETURN,return true;,return true;)" ]
"1004155" [label = "(<operator>.assignment,* key = getObject(i))" ]
"1004157" [label = "(getObject,getObject(i))" ]
"1004160" [label = "(<operator>.logicalAnd,key && key->hasFlags(constraints, flags))" ]
"1004162" [label = "(key->hasFlags,key->hasFlags(constraints, flags))" ]
"1004166" [label = "(RETURN,return true;,return true;)" ]
"1004123" [label = "(METHOD,TemporaryTypeSet::hasObjectFlags)" ]
"1004170" [label = "(METHOD_RETURN,bool)" ]
  "1004140" -> "1004145"
  "1004168" -> "1004170"
  "1004128" -> "1004134"
  "1004128" -> "1004130"
  "1004133" -> "1004137"
  "1004133" -> "1004142"
  "1004142" -> "1004140"
  "1004145" -> "1004148"
  "1004148" -> "1004157"
  "1004148" -> "1004157"
  "1004148" -> "1004168"
  "1004151" -> "1004148"
  "1004130" -> "1004170"
  "1004134" -> "1004133"
  "1004137" -> "1004170"
  "1004155" -> "1004160"
  "1004155" -> "1004162"
  "1004157" -> "1004155"
  "1004160" -> "1004166"
  "1004160" -> "1004151"
  "1004162" -> "1004160"
  "1004166" -> "1004170"
  "1004123" -> "1004128"
}
```

**Comment by max-leuthaeuser** [comment]
> It seems it is not the expected behavior

Yes, I agree with that. I will have another look later this week.
