### ISSUE TITLE
[newc] Missing data flow 

### ISSUE THREAD

**Issue by itsacoderepo** [joernio/joern#974]
Given the following code it seems that it is not possible to find a data flow starting from `foo`:

```
#include <stdio.h>
#include <string.h>

typedef struct {
  char *buf1;
} FooStruct;

void doFoo(FooStruct *str) {
  char onebuf[100];
  memset(onebuf,'1',sizeof onebuf);
  str->buf1 = onebuf;
}

int main(void) {
  FooStruct foo;
  doFoo(&foo);
  return 0;
}
```

Joern queries:
```
importCode("/tmp/test")
run.ossdataflow
def source = cpg.local.name("foo").referencingIdentifiers
def sink = cpg.call.code("doFoo.*").argument
sink.reachableByFlows(source).p
```

![image](https://user-images.githubusercontent.com/5180740/151797216-508bf1a7-b7b1-45d3-9be4-985b517817de.png)

**Comment by max-leuthaeuser** [comment]
I did some initial analysis already:

- the indirection (`Operators.addressOf` for `&foo` call) is handled already here: https://github.com/joernio/joern/blob/master/dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/UsageAnalyzer.scala#L110

- looks like these calls are filtered out here: https://github.com/joernio/joern/blob/master/dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/ReachingDefProblem.scala#L143 when initializing the map that contains generated definitions for each flow graph node. When tweaking this to allow at least `Operators.addressOf` calls everything works fine the given example.
